/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as path from 'node:path';
import * as process from 'node:process';
import { fileURLToPath } from 'node:url';

globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url));

import * as runtime from '@prisma/client/runtime/library';
import * as $Enums from './enums';
import * as $Class from './internal/class';
import * as Prisma from './internal/prismaNamespace';

export * as $Enums from './enums';
export * from './enums';
/**
 * ## Prisma Client
 *
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more ExpertWeeks
 * const expertWeeks = await prisma.expertWeek.findMany()
 * ```
 *
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname);
export type PrismaClient<
  LogOpts extends Prisma.LogLevel = never,
  OmitOpts extends Prisma.PrismaClientOptions['omit'] = Prisma.PrismaClientOptions['omit'],
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>;
export { Prisma };

// file annotations for bundling tools to include these files
path.join(__dirname, 'libquery_engine-debian-openssl-3.0.x.so.node');
path.join(
  process.cwd(),
  'src/server/db/generated-mongodb/libquery_engine-debian-openssl-3.0.x.so.node'
);

/**
 * Model UserProfile
 *
 */
export type UserProfile = Prisma.UserProfileModel;
/**
 * Model EmployeeProfile
 *
 */
export type EmployeeProfile = Prisma.EmployeeProfileModel;
/**
 * Model EmployeeSkillAssignment
 *
 */
export type EmployeeSkillAssignment = Prisma.EmployeeSkillAssignmentModel;
/**
 * Model EmployerProfile
 *
 */
export type EmployerProfile = Prisma.EmployerProfileModel;
/**
 * Model UserAddress
 *
 */
export type UserAddress = Prisma.UserAddressModel;
/**
 * Model FileMetadata
 *
 */
export type FileMetadata = Prisma.FileMetadataModel;
/**
 * Model TotpDevice
 *
 */
export type TotpDevice = Prisma.TotpDeviceModel;
/**
 * Model TotpActivity
 *
 */
export type TotpActivity = Prisma.TotpActivityModel;
/**
 * Model LoginEvent
 *
 */
export type LoginEvent = Prisma.LoginEventModel;
/**
 * Model UserPlanUser
 *
 */
export type UserPlanUser = Prisma.UserPlanUserModel;
/**
 * Model BayernBoxAccess
 *
 */
export type BayernBoxAccess = Prisma.BayernBoxAccessModel;
/**
 * Model WatchedCategory
 *
 */
export type WatchedCategory = Prisma.WatchedCategoryModel;
/**
 * Model ExpertWeek
 *
 */
export type ExpertWeek = Prisma.ExpertWeekModel;
/**
 * Model UserMongo
 *
 */
export type UserMongo = Prisma.UserMongoModel;
