/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ConsultationData` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model ConsultationData
 *
 */
export type ConsultationDataModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ConsultationDataPayload>;

export type AggregateConsultationData = {
  _count: ConsultationDataCountAggregateOutputType | null;
  _avg: ConsultationDataAvgAggregateOutputType | null;
  _sum: ConsultationDataSumAggregateOutputType | null;
  _min: ConsultationDataMinAggregateOutputType | null;
  _max: ConsultationDataMaxAggregateOutputType | null;
};

export type ConsultationDataAvgAggregateOutputType = {
  id: number | null;
  version: number | null;
  timeStart: number | null;
  timeEnd: number | null;
  period: number | null;
  basisWebDataId: number | null;
};

export type ConsultationDataSumAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  timeStart: number | null;
  timeEnd: number | null;
  period: number | null;
  basisWebDataId: bigint | null;
};

export type ConsultationDataMinAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  date: Date | null;
  timeStart: number | null;
  timeEnd: number | null;
  dateSignedOff: Date | null;
  archived: boolean | null;
  type: string | null;
  state: string | null;
  period: number | null;
  appointmentType: string | null;
  paymentType: string | null;
  noWarnings: boolean | null;
  comment: string | null;
  requireReporting: boolean | null;
  bookNumber: string | null;
  basisWebDataId: bigint | null;
  class: string | null;
};

export type ConsultationDataMaxAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  date: Date | null;
  timeStart: number | null;
  timeEnd: number | null;
  dateSignedOff: Date | null;
  archived: boolean | null;
  type: string | null;
  state: string | null;
  period: number | null;
  appointmentType: string | null;
  paymentType: string | null;
  noWarnings: boolean | null;
  comment: string | null;
  requireReporting: boolean | null;
  bookNumber: string | null;
  basisWebDataId: bigint | null;
  class: string | null;
};

export type ConsultationDataCountAggregateOutputType = {
  id: number;
  version: number;
  date: number;
  timeStart: number;
  timeEnd: number;
  dateSignedOff: number;
  archived: number;
  type: number;
  state: number;
  base: number;
  body: number;
  warnings: number;
  onboarding: number;
  standard: number;
  signedOffBy: number;
  appointment: number;
  location: number;
  period: number;
  appointmentType: number;
  customer: number;
  job: number;
  paymentType: number;
  doctor: number;
  history: number;
  document: number;
  incarceration: number;
  referral: number;
  psych: number;
  treatment: number;
  noWarnings: number;
  comment: number;
  requireReporting: number;
  bookNumber: number;
  basisWebDataId: number;
  class: number;
  _all: number;
};

export type ConsultationDataAvgAggregateInputType = {
  id?: true;
  version?: true;
  timeStart?: true;
  timeEnd?: true;
  period?: true;
  basisWebDataId?: true;
};

export type ConsultationDataSumAggregateInputType = {
  id?: true;
  version?: true;
  timeStart?: true;
  timeEnd?: true;
  period?: true;
  basisWebDataId?: true;
};

export type ConsultationDataMinAggregateInputType = {
  id?: true;
  version?: true;
  date?: true;
  timeStart?: true;
  timeEnd?: true;
  dateSignedOff?: true;
  archived?: true;
  type?: true;
  state?: true;
  period?: true;
  appointmentType?: true;
  paymentType?: true;
  noWarnings?: true;
  comment?: true;
  requireReporting?: true;
  bookNumber?: true;
  basisWebDataId?: true;
  class?: true;
};

export type ConsultationDataMaxAggregateInputType = {
  id?: true;
  version?: true;
  date?: true;
  timeStart?: true;
  timeEnd?: true;
  dateSignedOff?: true;
  archived?: true;
  type?: true;
  state?: true;
  period?: true;
  appointmentType?: true;
  paymentType?: true;
  noWarnings?: true;
  comment?: true;
  requireReporting?: true;
  bookNumber?: true;
  basisWebDataId?: true;
  class?: true;
};

export type ConsultationDataCountAggregateInputType = {
  id?: true;
  version?: true;
  date?: true;
  timeStart?: true;
  timeEnd?: true;
  dateSignedOff?: true;
  archived?: true;
  type?: true;
  state?: true;
  base?: true;
  body?: true;
  warnings?: true;
  onboarding?: true;
  standard?: true;
  signedOffBy?: true;
  appointment?: true;
  location?: true;
  period?: true;
  appointmentType?: true;
  customer?: true;
  job?: true;
  paymentType?: true;
  doctor?: true;
  history?: true;
  document?: true;
  incarceration?: true;
  referral?: true;
  psych?: true;
  treatment?: true;
  noWarnings?: true;
  comment?: true;
  requireReporting?: true;
  bookNumber?: true;
  basisWebDataId?: true;
  class?: true;
  _all?: true;
};

export type ConsultationDataAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ConsultationData to aggregate.
   */
  where?: Prisma.ConsultationDataWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ConsultationData to fetch.
   */
  orderBy?:
    | Prisma.ConsultationDataOrderByWithRelationInput
    | Prisma.ConsultationDataOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ConsultationDataWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ConsultationData from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ConsultationData.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ConsultationData
   **/
  _count?: true | ConsultationDataCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: ConsultationDataAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: ConsultationDataSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ConsultationDataMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ConsultationDataMaxAggregateInputType;
};

export type GetConsultationDataAggregateType<T extends ConsultationDataAggregateArgs> = {
  [P in keyof T & keyof AggregateConsultationData]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConsultationData[P]>
    : Prisma.GetScalarType<T[P], AggregateConsultationData[P]>;
};

export type ConsultationDataGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ConsultationDataWhereInput;
  orderBy?:
    | Prisma.ConsultationDataOrderByWithAggregationInput
    | Prisma.ConsultationDataOrderByWithAggregationInput[];
  by: Prisma.ConsultationDataScalarFieldEnum[] | Prisma.ConsultationDataScalarFieldEnum;
  having?: Prisma.ConsultationDataScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ConsultationDataCountAggregateInputType | true;
  _avg?: ConsultationDataAvgAggregateInputType;
  _sum?: ConsultationDataSumAggregateInputType;
  _min?: ConsultationDataMinAggregateInputType;
  _max?: ConsultationDataMaxAggregateInputType;
};

export type ConsultationDataGroupByOutputType = {
  id: bigint;
  version: bigint | null;
  date: Date | null;
  timeStart: number | null;
  timeEnd: number | null;
  dateSignedOff: Date | null;
  archived: boolean | null;
  type: string | null;
  state: string | null;
  base: runtime.JsonValue | null;
  body: runtime.JsonValue | null;
  warnings: runtime.JsonValue | null;
  onboarding: runtime.JsonValue | null;
  standard: runtime.JsonValue | null;
  signedOffBy: runtime.JsonValue | null;
  appointment: runtime.JsonValue | null;
  location: runtime.JsonValue | null;
  period: number | null;
  appointmentType: string | null;
  customer: runtime.JsonValue | null;
  job: runtime.JsonValue | null;
  paymentType: string | null;
  doctor: runtime.JsonValue | null;
  history: runtime.JsonValue | null;
  document: runtime.JsonValue | null;
  incarceration: runtime.JsonValue | null;
  referral: runtime.JsonValue | null;
  psych: runtime.JsonValue | null;
  treatment: runtime.JsonValue | null;
  noWarnings: boolean | null;
  comment: string | null;
  requireReporting: boolean | null;
  bookNumber: string | null;
  basisWebDataId: bigint | null;
  class: string | null;
  _count: ConsultationDataCountAggregateOutputType | null;
  _avg: ConsultationDataAvgAggregateOutputType | null;
  _sum: ConsultationDataSumAggregateOutputType | null;
  _min: ConsultationDataMinAggregateOutputType | null;
  _max: ConsultationDataMaxAggregateOutputType | null;
};

type GetConsultationDataGroupByPayload<T extends ConsultationDataGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<ConsultationDataGroupByOutputType, T['by']> & {
        [P in keyof T & keyof ConsultationDataGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConsultationDataGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConsultationDataGroupByOutputType[P]>;
      }
    >
  >;

export type ConsultationDataWhereInput = {
  AND?: Prisma.ConsultationDataWhereInput | Prisma.ConsultationDataWhereInput[];
  OR?: Prisma.ConsultationDataWhereInput[];
  NOT?: Prisma.ConsultationDataWhereInput | Prisma.ConsultationDataWhereInput[];
  id?: Prisma.BigIntFilter<'ConsultationData'> | bigint | number;
  version?: Prisma.BigIntNullableFilter<'ConsultationData'> | bigint | number | null;
  date?: Prisma.DateTimeNullableFilter<'ConsultationData'> | Date | string | null;
  timeStart?: Prisma.IntNullableFilter<'ConsultationData'> | number | null;
  timeEnd?: Prisma.IntNullableFilter<'ConsultationData'> | number | null;
  dateSignedOff?: Prisma.DateTimeNullableFilter<'ConsultationData'> | Date | string | null;
  archived?: Prisma.BoolNullableFilter<'ConsultationData'> | boolean | null;
  type?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
  state?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
  base?: Prisma.JsonNullableFilter<'ConsultationData'>;
  body?: Prisma.JsonNullableFilter<'ConsultationData'>;
  warnings?: Prisma.JsonNullableFilter<'ConsultationData'>;
  onboarding?: Prisma.JsonNullableFilter<'ConsultationData'>;
  standard?: Prisma.JsonNullableFilter<'ConsultationData'>;
  signedOffBy?: Prisma.JsonNullableFilter<'ConsultationData'>;
  appointment?: Prisma.JsonNullableFilter<'ConsultationData'>;
  location?: Prisma.JsonNullableFilter<'ConsultationData'>;
  period?: Prisma.IntNullableFilter<'ConsultationData'> | number | null;
  appointmentType?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
  customer?: Prisma.JsonNullableFilter<'ConsultationData'>;
  job?: Prisma.JsonNullableFilter<'ConsultationData'>;
  paymentType?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
  doctor?: Prisma.JsonNullableFilter<'ConsultationData'>;
  history?: Prisma.JsonNullableFilter<'ConsultationData'>;
  document?: Prisma.JsonNullableFilter<'ConsultationData'>;
  incarceration?: Prisma.JsonNullableFilter<'ConsultationData'>;
  referral?: Prisma.JsonNullableFilter<'ConsultationData'>;
  psych?: Prisma.JsonNullableFilter<'ConsultationData'>;
  treatment?: Prisma.JsonNullableFilter<'ConsultationData'>;
  noWarnings?: Prisma.BoolNullableFilter<'ConsultationData'> | boolean | null;
  comment?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
  requireReporting?: Prisma.BoolNullableFilter<'ConsultationData'> | boolean | null;
  bookNumber?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
  basisWebDataId?: Prisma.BigIntNullableFilter<'ConsultationData'> | bigint | number | null;
  class?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
};

export type ConsultationDataOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  date?: Prisma.SortOrder;
  timeStart?: Prisma.SortOrder;
  timeEnd?: Prisma.SortOrder;
  dateSignedOff?: Prisma.SortOrder;
  archived?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  state?: Prisma.SortOrder;
  base?: Prisma.SortOrder;
  body?: Prisma.SortOrder;
  warnings?: Prisma.SortOrder;
  onboarding?: Prisma.SortOrder;
  standard?: Prisma.SortOrder;
  signedOffBy?: Prisma.SortOrder;
  appointment?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  period?: Prisma.SortOrder;
  appointmentType?: Prisma.SortOrder;
  customer?: Prisma.SortOrder;
  job?: Prisma.SortOrder;
  paymentType?: Prisma.SortOrder;
  doctor?: Prisma.SortOrder;
  history?: Prisma.SortOrder;
  document?: Prisma.SortOrder;
  incarceration?: Prisma.SortOrder;
  referral?: Prisma.SortOrder;
  psych?: Prisma.SortOrder;
  treatment?: Prisma.SortOrder;
  noWarnings?: Prisma.SortOrder;
  comment?: Prisma.SortOrder;
  requireReporting?: Prisma.SortOrder;
  bookNumber?: Prisma.SortOrder;
  basisWebDataId?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type ConsultationDataWhereUniqueInput = Prisma.AtLeast<
  {
    id?: bigint | number;
    AND?: Prisma.ConsultationDataWhereInput | Prisma.ConsultationDataWhereInput[];
    OR?: Prisma.ConsultationDataWhereInput[];
    NOT?: Prisma.ConsultationDataWhereInput | Prisma.ConsultationDataWhereInput[];
    version?: Prisma.BigIntNullableFilter<'ConsultationData'> | bigint | number | null;
    date?: Prisma.DateTimeNullableFilter<'ConsultationData'> | Date | string | null;
    timeStart?: Prisma.IntNullableFilter<'ConsultationData'> | number | null;
    timeEnd?: Prisma.IntNullableFilter<'ConsultationData'> | number | null;
    dateSignedOff?: Prisma.DateTimeNullableFilter<'ConsultationData'> | Date | string | null;
    archived?: Prisma.BoolNullableFilter<'ConsultationData'> | boolean | null;
    type?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
    state?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
    base?: Prisma.JsonNullableFilter<'ConsultationData'>;
    body?: Prisma.JsonNullableFilter<'ConsultationData'>;
    warnings?: Prisma.JsonNullableFilter<'ConsultationData'>;
    onboarding?: Prisma.JsonNullableFilter<'ConsultationData'>;
    standard?: Prisma.JsonNullableFilter<'ConsultationData'>;
    signedOffBy?: Prisma.JsonNullableFilter<'ConsultationData'>;
    appointment?: Prisma.JsonNullableFilter<'ConsultationData'>;
    location?: Prisma.JsonNullableFilter<'ConsultationData'>;
    period?: Prisma.IntNullableFilter<'ConsultationData'> | number | null;
    appointmentType?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
    customer?: Prisma.JsonNullableFilter<'ConsultationData'>;
    job?: Prisma.JsonNullableFilter<'ConsultationData'>;
    paymentType?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
    doctor?: Prisma.JsonNullableFilter<'ConsultationData'>;
    history?: Prisma.JsonNullableFilter<'ConsultationData'>;
    document?: Prisma.JsonNullableFilter<'ConsultationData'>;
    incarceration?: Prisma.JsonNullableFilter<'ConsultationData'>;
    referral?: Prisma.JsonNullableFilter<'ConsultationData'>;
    psych?: Prisma.JsonNullableFilter<'ConsultationData'>;
    treatment?: Prisma.JsonNullableFilter<'ConsultationData'>;
    noWarnings?: Prisma.BoolNullableFilter<'ConsultationData'> | boolean | null;
    comment?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
    requireReporting?: Prisma.BoolNullableFilter<'ConsultationData'> | boolean | null;
    bookNumber?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
    basisWebDataId?: Prisma.BigIntNullableFilter<'ConsultationData'> | bigint | number | null;
    class?: Prisma.StringNullableFilter<'ConsultationData'> | string | null;
  },
  'id'
>;

export type ConsultationDataOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  date?: Prisma.SortOrder;
  timeStart?: Prisma.SortOrder;
  timeEnd?: Prisma.SortOrder;
  dateSignedOff?: Prisma.SortOrder;
  archived?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  state?: Prisma.SortOrder;
  base?: Prisma.SortOrder;
  body?: Prisma.SortOrder;
  warnings?: Prisma.SortOrder;
  onboarding?: Prisma.SortOrder;
  standard?: Prisma.SortOrder;
  signedOffBy?: Prisma.SortOrder;
  appointment?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  period?: Prisma.SortOrder;
  appointmentType?: Prisma.SortOrder;
  customer?: Prisma.SortOrder;
  job?: Prisma.SortOrder;
  paymentType?: Prisma.SortOrder;
  doctor?: Prisma.SortOrder;
  history?: Prisma.SortOrder;
  document?: Prisma.SortOrder;
  incarceration?: Prisma.SortOrder;
  referral?: Prisma.SortOrder;
  psych?: Prisma.SortOrder;
  treatment?: Prisma.SortOrder;
  noWarnings?: Prisma.SortOrder;
  comment?: Prisma.SortOrder;
  requireReporting?: Prisma.SortOrder;
  bookNumber?: Prisma.SortOrder;
  basisWebDataId?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
  _count?: Prisma.ConsultationDataCountOrderByAggregateInput;
  _avg?: Prisma.ConsultationDataAvgOrderByAggregateInput;
  _max?: Prisma.ConsultationDataMaxOrderByAggregateInput;
  _min?: Prisma.ConsultationDataMinOrderByAggregateInput;
  _sum?: Prisma.ConsultationDataSumOrderByAggregateInput;
};

export type ConsultationDataScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ConsultationDataScalarWhereWithAggregatesInput
    | Prisma.ConsultationDataScalarWhereWithAggregatesInput[];
  OR?: Prisma.ConsultationDataScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.ConsultationDataScalarWhereWithAggregatesInput
    | Prisma.ConsultationDataScalarWhereWithAggregatesInput[];
  id?: Prisma.BigIntWithAggregatesFilter<'ConsultationData'> | bigint | number;
  version?: Prisma.BigIntNullableWithAggregatesFilter<'ConsultationData'> | bigint | number | null;
  date?: Prisma.DateTimeNullableWithAggregatesFilter<'ConsultationData'> | Date | string | null;
  timeStart?: Prisma.IntNullableWithAggregatesFilter<'ConsultationData'> | number | null;
  timeEnd?: Prisma.IntNullableWithAggregatesFilter<'ConsultationData'> | number | null;
  dateSignedOff?:
    | Prisma.DateTimeNullableWithAggregatesFilter<'ConsultationData'>
    | Date
    | string
    | null;
  archived?: Prisma.BoolNullableWithAggregatesFilter<'ConsultationData'> | boolean | null;
  type?: Prisma.StringNullableWithAggregatesFilter<'ConsultationData'> | string | null;
  state?: Prisma.StringNullableWithAggregatesFilter<'ConsultationData'> | string | null;
  base?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  body?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  warnings?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  onboarding?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  standard?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  signedOffBy?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  appointment?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  location?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  period?: Prisma.IntNullableWithAggregatesFilter<'ConsultationData'> | number | null;
  appointmentType?: Prisma.StringNullableWithAggregatesFilter<'ConsultationData'> | string | null;
  customer?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  job?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  paymentType?: Prisma.StringNullableWithAggregatesFilter<'ConsultationData'> | string | null;
  doctor?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  history?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  document?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  incarceration?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  referral?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  psych?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  treatment?: Prisma.JsonNullableWithAggregatesFilter<'ConsultationData'>;
  noWarnings?: Prisma.BoolNullableWithAggregatesFilter<'ConsultationData'> | boolean | null;
  comment?: Prisma.StringNullableWithAggregatesFilter<'ConsultationData'> | string | null;
  requireReporting?: Prisma.BoolNullableWithAggregatesFilter<'ConsultationData'> | boolean | null;
  bookNumber?: Prisma.StringNullableWithAggregatesFilter<'ConsultationData'> | string | null;
  basisWebDataId?:
    | Prisma.BigIntNullableWithAggregatesFilter<'ConsultationData'>
    | bigint
    | number
    | null;
  class?: Prisma.StringNullableWithAggregatesFilter<'ConsultationData'> | string | null;
};

export type ConsultationDataCreateInput = {
  id: bigint | number;
  version?: bigint | number | null;
  date?: Date | string | null;
  timeStart?: number | null;
  timeEnd?: number | null;
  dateSignedOff?: Date | string | null;
  archived?: boolean | null;
  type?: string | null;
  state?: string | null;
  base?: runtime.InputJsonValue | null;
  body?: runtime.InputJsonValue | null;
  warnings?: runtime.InputJsonValue | null;
  onboarding?: runtime.InputJsonValue | null;
  standard?: runtime.InputJsonValue | null;
  signedOffBy?: runtime.InputJsonValue | null;
  appointment?: runtime.InputJsonValue | null;
  location?: runtime.InputJsonValue | null;
  period?: number | null;
  appointmentType?: string | null;
  customer?: runtime.InputJsonValue | null;
  job?: runtime.InputJsonValue | null;
  paymentType?: string | null;
  doctor?: runtime.InputJsonValue | null;
  history?: runtime.InputJsonValue | null;
  document?: runtime.InputJsonValue | null;
  incarceration?: runtime.InputJsonValue | null;
  referral?: runtime.InputJsonValue | null;
  psych?: runtime.InputJsonValue | null;
  treatment?: runtime.InputJsonValue | null;
  noWarnings?: boolean | null;
  comment?: string | null;
  requireReporting?: boolean | null;
  bookNumber?: string | null;
  basisWebDataId?: bigint | number | null;
  class?: string | null;
};

export type ConsultationDataUncheckedCreateInput = {
  id: bigint | number;
  version?: bigint | number | null;
  date?: Date | string | null;
  timeStart?: number | null;
  timeEnd?: number | null;
  dateSignedOff?: Date | string | null;
  archived?: boolean | null;
  type?: string | null;
  state?: string | null;
  base?: runtime.InputJsonValue | null;
  body?: runtime.InputJsonValue | null;
  warnings?: runtime.InputJsonValue | null;
  onboarding?: runtime.InputJsonValue | null;
  standard?: runtime.InputJsonValue | null;
  signedOffBy?: runtime.InputJsonValue | null;
  appointment?: runtime.InputJsonValue | null;
  location?: runtime.InputJsonValue | null;
  period?: number | null;
  appointmentType?: string | null;
  customer?: runtime.InputJsonValue | null;
  job?: runtime.InputJsonValue | null;
  paymentType?: string | null;
  doctor?: runtime.InputJsonValue | null;
  history?: runtime.InputJsonValue | null;
  document?: runtime.InputJsonValue | null;
  incarceration?: runtime.InputJsonValue | null;
  referral?: runtime.InputJsonValue | null;
  psych?: runtime.InputJsonValue | null;
  treatment?: runtime.InputJsonValue | null;
  noWarnings?: boolean | null;
  comment?: string | null;
  requireReporting?: boolean | null;
  bookNumber?: string | null;
  basisWebDataId?: bigint | number | null;
  class?: string | null;
};

export type ConsultationDataUpdateInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  timeStart?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  timeEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  dateSignedOff?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  base?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  body?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  warnings?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  onboarding?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  standard?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  signedOffBy?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  appointment?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  location?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  period?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  appointmentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  customer?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  job?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  doctor?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  history?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  document?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  incarceration?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  referral?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  psych?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  treatment?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  noWarnings?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  requireReporting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  bookNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  basisWebDataId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ConsultationDataUncheckedUpdateInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  timeStart?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  timeEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  dateSignedOff?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  base?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  body?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  warnings?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  onboarding?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  standard?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  signedOffBy?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  appointment?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  location?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  period?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  appointmentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  customer?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  job?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  doctor?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  history?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  document?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  incarceration?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  referral?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  psych?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  treatment?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  noWarnings?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  requireReporting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  bookNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  basisWebDataId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ConsultationDataCreateManyInput = {
  id: bigint | number;
  version?: bigint | number | null;
  date?: Date | string | null;
  timeStart?: number | null;
  timeEnd?: number | null;
  dateSignedOff?: Date | string | null;
  archived?: boolean | null;
  type?: string | null;
  state?: string | null;
  base?: runtime.InputJsonValue | null;
  body?: runtime.InputJsonValue | null;
  warnings?: runtime.InputJsonValue | null;
  onboarding?: runtime.InputJsonValue | null;
  standard?: runtime.InputJsonValue | null;
  signedOffBy?: runtime.InputJsonValue | null;
  appointment?: runtime.InputJsonValue | null;
  location?: runtime.InputJsonValue | null;
  period?: number | null;
  appointmentType?: string | null;
  customer?: runtime.InputJsonValue | null;
  job?: runtime.InputJsonValue | null;
  paymentType?: string | null;
  doctor?: runtime.InputJsonValue | null;
  history?: runtime.InputJsonValue | null;
  document?: runtime.InputJsonValue | null;
  incarceration?: runtime.InputJsonValue | null;
  referral?: runtime.InputJsonValue | null;
  psych?: runtime.InputJsonValue | null;
  treatment?: runtime.InputJsonValue | null;
  noWarnings?: boolean | null;
  comment?: string | null;
  requireReporting?: boolean | null;
  bookNumber?: string | null;
  basisWebDataId?: bigint | number | null;
  class?: string | null;
};

export type ConsultationDataUpdateManyMutationInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  timeStart?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  timeEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  dateSignedOff?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  base?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  body?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  warnings?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  onboarding?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  standard?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  signedOffBy?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  appointment?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  location?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  period?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  appointmentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  customer?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  job?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  doctor?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  history?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  document?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  incarceration?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  referral?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  psych?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  treatment?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  noWarnings?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  requireReporting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  bookNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  basisWebDataId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ConsultationDataUncheckedUpdateManyInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  timeStart?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  timeEnd?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  dateSignedOff?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  archived?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  base?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  body?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  warnings?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  onboarding?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  standard?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  signedOffBy?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  appointment?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  location?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  period?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  appointmentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  customer?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  job?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  paymentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  doctor?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  history?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  document?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  incarceration?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  referral?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  psych?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  treatment?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  noWarnings?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  comment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  requireReporting?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  bookNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  basisWebDataId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ConsultationDataCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  date?: Prisma.SortOrder;
  timeStart?: Prisma.SortOrder;
  timeEnd?: Prisma.SortOrder;
  dateSignedOff?: Prisma.SortOrder;
  archived?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  state?: Prisma.SortOrder;
  base?: Prisma.SortOrder;
  body?: Prisma.SortOrder;
  warnings?: Prisma.SortOrder;
  onboarding?: Prisma.SortOrder;
  standard?: Prisma.SortOrder;
  signedOffBy?: Prisma.SortOrder;
  appointment?: Prisma.SortOrder;
  location?: Prisma.SortOrder;
  period?: Prisma.SortOrder;
  appointmentType?: Prisma.SortOrder;
  customer?: Prisma.SortOrder;
  job?: Prisma.SortOrder;
  paymentType?: Prisma.SortOrder;
  doctor?: Prisma.SortOrder;
  history?: Prisma.SortOrder;
  document?: Prisma.SortOrder;
  incarceration?: Prisma.SortOrder;
  referral?: Prisma.SortOrder;
  psych?: Prisma.SortOrder;
  treatment?: Prisma.SortOrder;
  noWarnings?: Prisma.SortOrder;
  comment?: Prisma.SortOrder;
  requireReporting?: Prisma.SortOrder;
  bookNumber?: Prisma.SortOrder;
  basisWebDataId?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type ConsultationDataAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  timeStart?: Prisma.SortOrder;
  timeEnd?: Prisma.SortOrder;
  period?: Prisma.SortOrder;
  basisWebDataId?: Prisma.SortOrder;
};

export type ConsultationDataMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  date?: Prisma.SortOrder;
  timeStart?: Prisma.SortOrder;
  timeEnd?: Prisma.SortOrder;
  dateSignedOff?: Prisma.SortOrder;
  archived?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  state?: Prisma.SortOrder;
  period?: Prisma.SortOrder;
  appointmentType?: Prisma.SortOrder;
  paymentType?: Prisma.SortOrder;
  noWarnings?: Prisma.SortOrder;
  comment?: Prisma.SortOrder;
  requireReporting?: Prisma.SortOrder;
  bookNumber?: Prisma.SortOrder;
  basisWebDataId?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type ConsultationDataMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  date?: Prisma.SortOrder;
  timeStart?: Prisma.SortOrder;
  timeEnd?: Prisma.SortOrder;
  dateSignedOff?: Prisma.SortOrder;
  archived?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  state?: Prisma.SortOrder;
  period?: Prisma.SortOrder;
  appointmentType?: Prisma.SortOrder;
  paymentType?: Prisma.SortOrder;
  noWarnings?: Prisma.SortOrder;
  comment?: Prisma.SortOrder;
  requireReporting?: Prisma.SortOrder;
  bookNumber?: Prisma.SortOrder;
  basisWebDataId?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type ConsultationDataSumOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  timeStart?: Prisma.SortOrder;
  timeEnd?: Prisma.SortOrder;
  period?: Prisma.SortOrder;
  basisWebDataId?: Prisma.SortOrder;
};

export type ConsultationDataSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    version?: boolean;
    date?: boolean;
    timeStart?: boolean;
    timeEnd?: boolean;
    dateSignedOff?: boolean;
    archived?: boolean;
    type?: boolean;
    state?: boolean;
    base?: boolean;
    body?: boolean;
    warnings?: boolean;
    onboarding?: boolean;
    standard?: boolean;
    signedOffBy?: boolean;
    appointment?: boolean;
    location?: boolean;
    period?: boolean;
    appointmentType?: boolean;
    customer?: boolean;
    job?: boolean;
    paymentType?: boolean;
    doctor?: boolean;
    history?: boolean;
    document?: boolean;
    incarceration?: boolean;
    referral?: boolean;
    psych?: boolean;
    treatment?: boolean;
    noWarnings?: boolean;
    comment?: boolean;
    requireReporting?: boolean;
    bookNumber?: boolean;
    basisWebDataId?: boolean;
    class?: boolean;
  },
  ExtArgs['result']['consultationData']
>;

export type ConsultationDataSelectScalar = {
  id?: boolean;
  version?: boolean;
  date?: boolean;
  timeStart?: boolean;
  timeEnd?: boolean;
  dateSignedOff?: boolean;
  archived?: boolean;
  type?: boolean;
  state?: boolean;
  base?: boolean;
  body?: boolean;
  warnings?: boolean;
  onboarding?: boolean;
  standard?: boolean;
  signedOffBy?: boolean;
  appointment?: boolean;
  location?: boolean;
  period?: boolean;
  appointmentType?: boolean;
  customer?: boolean;
  job?: boolean;
  paymentType?: boolean;
  doctor?: boolean;
  history?: boolean;
  document?: boolean;
  incarceration?: boolean;
  referral?: boolean;
  psych?: boolean;
  treatment?: boolean;
  noWarnings?: boolean;
  comment?: boolean;
  requireReporting?: boolean;
  bookNumber?: boolean;
  basisWebDataId?: boolean;
  class?: boolean;
};

export type ConsultationDataOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'version'
  | 'date'
  | 'timeStart'
  | 'timeEnd'
  | 'dateSignedOff'
  | 'archived'
  | 'type'
  | 'state'
  | 'base'
  | 'body'
  | 'warnings'
  | 'onboarding'
  | 'standard'
  | 'signedOffBy'
  | 'appointment'
  | 'location'
  | 'period'
  | 'appointmentType'
  | 'customer'
  | 'job'
  | 'paymentType'
  | 'doctor'
  | 'history'
  | 'document'
  | 'incarceration'
  | 'referral'
  | 'psych'
  | 'treatment'
  | 'noWarnings'
  | 'comment'
  | 'requireReporting'
  | 'bookNumber'
  | 'basisWebDataId'
  | 'class',
  ExtArgs['result']['consultationData']
>;

export type $ConsultationDataPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'ConsultationData';
  objects: {};
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: bigint;
      version: bigint | null;
      date: Date | null;
      timeStart: number | null;
      timeEnd: number | null;
      dateSignedOff: Date | null;
      archived: boolean | null;
      type: string | null;
      state: string | null;
      base: runtime.JsonValue | null;
      body: runtime.JsonValue | null;
      warnings: runtime.JsonValue | null;
      onboarding: runtime.JsonValue | null;
      standard: runtime.JsonValue | null;
      signedOffBy: runtime.JsonValue | null;
      appointment: runtime.JsonValue | null;
      location: runtime.JsonValue | null;
      period: number | null;
      appointmentType: string | null;
      customer: runtime.JsonValue | null;
      job: runtime.JsonValue | null;
      paymentType: string | null;
      doctor: runtime.JsonValue | null;
      history: runtime.JsonValue | null;
      document: runtime.JsonValue | null;
      incarceration: runtime.JsonValue | null;
      referral: runtime.JsonValue | null;
      psych: runtime.JsonValue | null;
      treatment: runtime.JsonValue | null;
      noWarnings: boolean | null;
      comment: string | null;
      requireReporting: boolean | null;
      bookNumber: string | null;
      basisWebDataId: bigint | null;
      class: string | null;
    },
    ExtArgs['result']['consultationData']
  >;
  composites: {};
};

export type ConsultationDataGetPayload<
  S extends boolean | null | undefined | ConsultationDataDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ConsultationDataPayload, S>;

export type ConsultationDataCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ConsultationDataFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ConsultationDataCountAggregateInputType | true;
};

export interface ConsultationDataDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['ConsultationData'];
    meta: { name: 'ConsultationData' };
  };
  /**
   * Find zero or one ConsultationData that matches the filter.
   * @param {ConsultationDataFindUniqueArgs} args - Arguments to find a ConsultationData
   * @example
   * // Get one ConsultationData
   * const consultationData = await prisma.consultationData.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConsultationDataFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ConsultationDataFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__ConsultationDataClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one ConsultationData that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConsultationDataFindUniqueOrThrowArgs} args - Arguments to find a ConsultationData
   * @example
   * // Get one ConsultationData
   * const consultationData = await prisma.consultationData.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConsultationDataFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ConsultationDataFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ConsultationDataClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ConsultationData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultationDataFindFirstArgs} args - Arguments to find a ConsultationData
   * @example
   * // Get one ConsultationData
   * const consultationData = await prisma.consultationData.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConsultationDataFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ConsultationDataFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__ConsultationDataClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ConsultationData that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultationDataFindFirstOrThrowArgs} args - Arguments to find a ConsultationData
   * @example
   * // Get one ConsultationData
   * const consultationData = await prisma.consultationData.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConsultationDataFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ConsultationDataFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ConsultationDataClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ConsultationData that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultationDataFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ConsultationData
   * const consultationData = await prisma.consultationData.findMany()
   *
   * // Get first 10 ConsultationData
   * const consultationData = await prisma.consultationData.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const consultationDataWithIdOnly = await prisma.consultationData.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ConsultationDataFindManyArgs>(
    args?: Prisma.SelectSubset<T, ConsultationDataFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a ConsultationData.
   * @param {ConsultationDataCreateArgs} args - Arguments to create a ConsultationData.
   * @example
   * // Create one ConsultationData
   * const ConsultationData = await prisma.consultationData.create({
   *   data: {
   *     // ... data to create a ConsultationData
   *   }
   * })
   *
   */
  create<T extends ConsultationDataCreateArgs>(
    args: Prisma.SelectSubset<T, ConsultationDataCreateArgs<ExtArgs>>
  ): Prisma.Prisma__ConsultationDataClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many ConsultationData.
   * @param {ConsultationDataCreateManyArgs} args - Arguments to create many ConsultationData.
   * @example
   * // Create many ConsultationData
   * const consultationData = await prisma.consultationData.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ConsultationDataCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ConsultationDataCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Delete a ConsultationData.
   * @param {ConsultationDataDeleteArgs} args - Arguments to delete one ConsultationData.
   * @example
   * // Delete one ConsultationData
   * const ConsultationData = await prisma.consultationData.delete({
   *   where: {
   *     // ... filter to delete one ConsultationData
   *   }
   * })
   *
   */
  delete<T extends ConsultationDataDeleteArgs>(
    args: Prisma.SelectSubset<T, ConsultationDataDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__ConsultationDataClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one ConsultationData.
   * @param {ConsultationDataUpdateArgs} args - Arguments to update one ConsultationData.
   * @example
   * // Update one ConsultationData
   * const consultationData = await prisma.consultationData.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ConsultationDataUpdateArgs>(
    args: Prisma.SelectSubset<T, ConsultationDataUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__ConsultationDataClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more ConsultationData.
   * @param {ConsultationDataDeleteManyArgs} args - Arguments to filter ConsultationData to delete.
   * @example
   * // Delete a few ConsultationData
   * const { count } = await prisma.consultationData.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ConsultationDataDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ConsultationDataDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ConsultationData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultationDataUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ConsultationData
   * const consultationData = await prisma.consultationData.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ConsultationDataUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ConsultationDataUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create or update one ConsultationData.
   * @param {ConsultationDataUpsertArgs} args - Arguments to update or create a ConsultationData.
   * @example
   * // Update or create a ConsultationData
   * const consultationData = await prisma.consultationData.upsert({
   *   create: {
   *     // ... data to create a ConsultationData
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ConsultationData we want to update
   *   }
   * })
   */
  upsert<T extends ConsultationDataUpsertArgs>(
    args: Prisma.SelectSubset<T, ConsultationDataUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__ConsultationDataClient<
    runtime.Types.Result.GetResult<
      Prisma.$ConsultationDataPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ConsultationData that matches the filter.
   * @param {ConsultationDataFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const consultationData = await prisma.consultationData.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.ConsultationDataFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>;

  /**
   * Perform aggregation operations on a ConsultationData.
   * @param {ConsultationDataAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const consultationData = await prisma.consultationData.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(
    args?: Prisma.ConsultationDataAggregateRawArgs
  ): Prisma.PrismaPromise<Prisma.JsonObject>;

  /**
   * Count the number of ConsultationData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultationDataCountArgs} args - Arguments to filter ConsultationData to count.
   * @example
   * // Count the number of ConsultationData
   * const count = await prisma.consultationData.count({
   *   where: {
   *     // ... the filter for the ConsultationData we want to count
   *   }
   * })
   **/
  count<T extends ConsultationDataCountArgs>(
    args?: Prisma.Subset<T, ConsultationDataCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConsultationDataCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a ConsultationData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultationDataAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ConsultationDataAggregateArgs>(
    args: Prisma.Subset<T, ConsultationDataAggregateArgs>
  ): Prisma.PrismaPromise<GetConsultationDataAggregateType<T>>;

  /**
   * Group by ConsultationData.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultationDataGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ConsultationDataGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConsultationDataGroupByArgs['orderBy'] }
      : { orderBy?: ConsultationDataGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, ConsultationDataGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors
    ? GetConsultationDataGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ConsultationData model
   */
  readonly fields: ConsultationDataFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ConsultationData.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConsultationDataClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ConsultationData model
 */
export interface ConsultationDataFieldRefs {
  readonly id: Prisma.FieldRef<'ConsultationData', 'BigInt'>;
  readonly version: Prisma.FieldRef<'ConsultationData', 'BigInt'>;
  readonly date: Prisma.FieldRef<'ConsultationData', 'DateTime'>;
  readonly timeStart: Prisma.FieldRef<'ConsultationData', 'Int'>;
  readonly timeEnd: Prisma.FieldRef<'ConsultationData', 'Int'>;
  readonly dateSignedOff: Prisma.FieldRef<'ConsultationData', 'DateTime'>;
  readonly archived: Prisma.FieldRef<'ConsultationData', 'Boolean'>;
  readonly type: Prisma.FieldRef<'ConsultationData', 'String'>;
  readonly state: Prisma.FieldRef<'ConsultationData', 'String'>;
  readonly base: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly body: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly warnings: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly onboarding: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly standard: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly signedOffBy: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly appointment: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly location: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly period: Prisma.FieldRef<'ConsultationData', 'Int'>;
  readonly appointmentType: Prisma.FieldRef<'ConsultationData', 'String'>;
  readonly customer: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly job: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly paymentType: Prisma.FieldRef<'ConsultationData', 'String'>;
  readonly doctor: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly history: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly document: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly incarceration: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly referral: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly psych: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly treatment: Prisma.FieldRef<'ConsultationData', 'Json'>;
  readonly noWarnings: Prisma.FieldRef<'ConsultationData', 'Boolean'>;
  readonly comment: Prisma.FieldRef<'ConsultationData', 'String'>;
  readonly requireReporting: Prisma.FieldRef<'ConsultationData', 'Boolean'>;
  readonly bookNumber: Prisma.FieldRef<'ConsultationData', 'String'>;
  readonly basisWebDataId: Prisma.FieldRef<'ConsultationData', 'BigInt'>;
  readonly class: Prisma.FieldRef<'ConsultationData', 'String'>;
}

// Custom InputTypes
/**
 * ConsultationData findUnique
 */
export type ConsultationDataFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * Filter, which ConsultationData to fetch.
   */
  where: Prisma.ConsultationDataWhereUniqueInput;
};

/**
 * ConsultationData findUniqueOrThrow
 */
export type ConsultationDataFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * Filter, which ConsultationData to fetch.
   */
  where: Prisma.ConsultationDataWhereUniqueInput;
};

/**
 * ConsultationData findFirst
 */
export type ConsultationDataFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * Filter, which ConsultationData to fetch.
   */
  where?: Prisma.ConsultationDataWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ConsultationData to fetch.
   */
  orderBy?:
    | Prisma.ConsultationDataOrderByWithRelationInput
    | Prisma.ConsultationDataOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ConsultationData.
   */
  cursor?: Prisma.ConsultationDataWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ConsultationData from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ConsultationData.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ConsultationData.
   */
  distinct?: Prisma.ConsultationDataScalarFieldEnum | Prisma.ConsultationDataScalarFieldEnum[];
};

/**
 * ConsultationData findFirstOrThrow
 */
export type ConsultationDataFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * Filter, which ConsultationData to fetch.
   */
  where?: Prisma.ConsultationDataWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ConsultationData to fetch.
   */
  orderBy?:
    | Prisma.ConsultationDataOrderByWithRelationInput
    | Prisma.ConsultationDataOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ConsultationData.
   */
  cursor?: Prisma.ConsultationDataWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ConsultationData from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ConsultationData.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ConsultationData.
   */
  distinct?: Prisma.ConsultationDataScalarFieldEnum | Prisma.ConsultationDataScalarFieldEnum[];
};

/**
 * ConsultationData findMany
 */
export type ConsultationDataFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * Filter, which ConsultationData to fetch.
   */
  where?: Prisma.ConsultationDataWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ConsultationData to fetch.
   */
  orderBy?:
    | Prisma.ConsultationDataOrderByWithRelationInput
    | Prisma.ConsultationDataOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ConsultationData.
   */
  cursor?: Prisma.ConsultationDataWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ConsultationData from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ConsultationData.
   */
  skip?: number;
  distinct?: Prisma.ConsultationDataScalarFieldEnum | Prisma.ConsultationDataScalarFieldEnum[];
};

/**
 * ConsultationData create
 */
export type ConsultationDataCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * The data needed to create a ConsultationData.
   */
  data: Prisma.XOR<Prisma.ConsultationDataCreateInput, Prisma.ConsultationDataUncheckedCreateInput>;
};

/**
 * ConsultationData createMany
 */
export type ConsultationDataCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ConsultationData.
   */
  data: Prisma.ConsultationDataCreateManyInput | Prisma.ConsultationDataCreateManyInput[];
};

/**
 * ConsultationData update
 */
export type ConsultationDataUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * The data needed to update a ConsultationData.
   */
  data: Prisma.XOR<Prisma.ConsultationDataUpdateInput, Prisma.ConsultationDataUncheckedUpdateInput>;
  /**
   * Choose, which ConsultationData to update.
   */
  where: Prisma.ConsultationDataWhereUniqueInput;
};

/**
 * ConsultationData updateMany
 */
export type ConsultationDataUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ConsultationData.
   */
  data: Prisma.XOR<
    Prisma.ConsultationDataUpdateManyMutationInput,
    Prisma.ConsultationDataUncheckedUpdateManyInput
  >;
  /**
   * Filter which ConsultationData to update
   */
  where?: Prisma.ConsultationDataWhereInput;
  /**
   * Limit how many ConsultationData to update.
   */
  limit?: number;
};

/**
 * ConsultationData upsert
 */
export type ConsultationDataUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * The filter to search for the ConsultationData to update in case it exists.
   */
  where: Prisma.ConsultationDataWhereUniqueInput;
  /**
   * In case the ConsultationData found by the `where` argument doesn't exist, create a new ConsultationData with this data.
   */
  create: Prisma.XOR<
    Prisma.ConsultationDataCreateInput,
    Prisma.ConsultationDataUncheckedCreateInput
  >;
  /**
   * In case the ConsultationData was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.ConsultationDataUpdateInput,
    Prisma.ConsultationDataUncheckedUpdateInput
  >;
};

/**
 * ConsultationData delete
 */
export type ConsultationDataDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
  /**
   * Filter which ConsultationData to delete.
   */
  where: Prisma.ConsultationDataWhereUniqueInput;
};

/**
 * ConsultationData deleteMany
 */
export type ConsultationDataDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ConsultationData to delete
   */
  where?: Prisma.ConsultationDataWhereInput;
  /**
   * Limit how many ConsultationData to delete.
   */
  limit?: number;
};

/**
 * ConsultationData findRaw
 */
export type ConsultationDataFindRawArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue;
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue;
};

/**
 * ConsultationData aggregateRaw
 */
export type ConsultationDataAggregateRawArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[];
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue;
};

/**
 * ConsultationData without action
 */
export type ConsultationDataDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationData
   */
  select?: Prisma.ConsultationDataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationData
   */
  omit?: Prisma.ConsultationDataOmit<ExtArgs> | null;
};
