/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ConsultationJob` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model ConsultationJob
 *
 */
export type ConsultationJobModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ConsultationJobPayload>;

export type ConsultationJobNullableCompositeFilter = {
  equals?: Prisma.ConsultationJobObjectEqualityInput | null;
  is?: Prisma.ConsultationJobWhereInput | null;
  isNot?: Prisma.ConsultationJobWhereInput | null;
  isSet?: boolean;
};

export type ConsultationJobOrderByInput = {
  id?: Prisma.SortOrder;
  title?: Prisma.SortOrder;
  code?: Prisma.SortOrder;
  shortcode?: Prisma.SortOrder;
  expertTitle?: Prisma.SortOrder;
  color?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
};

export type ConsultationJobNullableCreateEnvelopeInput = {
  set?: Prisma.ConsultationJobCreateInput | null;
};

export type ConsultationJobNullableUpdateEnvelopeInput = {
  set?: Prisma.ConsultationJobCreateInput | null;
  upsert?: Prisma.ConsultationJobUpsertInput;
  unset?: boolean;
};

export type ConsultationJobWhereInput = {
  AND?: Prisma.ConsultationJobWhereInput | Prisma.ConsultationJobWhereInput[];
  OR?: Prisma.ConsultationJobWhereInput[];
  NOT?: Prisma.ConsultationJobWhereInput | Prisma.ConsultationJobWhereInput[];
  id?: Prisma.BigIntNullableFilter<'ConsultationJob'> | bigint | number | null;
  title?: Prisma.StringNullableFilter<'ConsultationJob'> | string | null;
  code?: Prisma.StringNullableFilter<'ConsultationJob'> | string | null;
  shortcode?: Prisma.StringNullableFilter<'ConsultationJob'> | string | null;
  expertTitle?: Prisma.StringNullableFilter<'ConsultationJob'> | string | null;
  color?: Prisma.StringNullableFilter<'ConsultationJob'> | string | null;
  type?: Prisma.StringNullableFilter<'ConsultationJob'> | string | null;
};

export type ConsultationJobUpsertInput = {
  set: Prisma.ConsultationJobCreateInput | null;
  update: Prisma.ConsultationJobUpdateInput;
};

export type ConsultationJobUpdateInput = {
  id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  shortcode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  expertTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ConsultationJobSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    title?: boolean;
    code?: boolean;
    shortcode?: boolean;
    expertTitle?: boolean;
    color?: boolean;
    type?: boolean;
  },
  ExtArgs['result']['consultationJob']
>;

export type ConsultationJobSelectScalar = {
  id?: boolean;
  title?: boolean;
  code?: boolean;
  shortcode?: boolean;
  expertTitle?: boolean;
  color?: boolean;
  type?: boolean;
};

export type ConsultationJobOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'title' | 'code' | 'shortcode' | 'expertTitle' | 'color' | 'type',
  ExtArgs['result']['consultationJob']
>;

export type $ConsultationJobPayload = {
  name: 'ConsultationJob';
  objects: {};
  scalars: {
    id: bigint | null;
    title: string | null;
    code: string | null;
    shortcode: string | null;
    expertTitle: string | null;
    color: string | null;
    type: string | null;
  };
  composites: {};
};

export type ConsultationJobGetPayload<
  S extends boolean | null | undefined | ConsultationJobDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ConsultationJobPayload, S>;

/**
 * Fields of the ConsultationJob model
 */
export interface ConsultationJobFieldRefs {
  readonly id: Prisma.FieldRef<'ConsultationJob', 'BigInt'>;
  readonly title: Prisma.FieldRef<'ConsultationJob', 'String'>;
  readonly code: Prisma.FieldRef<'ConsultationJob', 'String'>;
  readonly shortcode: Prisma.FieldRef<'ConsultationJob', 'String'>;
  readonly expertTitle: Prisma.FieldRef<'ConsultationJob', 'String'>;
  readonly color: Prisma.FieldRef<'ConsultationJob', 'String'>;
  readonly type: Prisma.FieldRef<'ConsultationJob', 'String'>;
}

// Custom InputTypes
/**
 * ConsultationJob without action
 */
export type ConsultationJobDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationJob
   */
  select?: Prisma.ConsultationJobSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationJob
   */
  omit?: Prisma.ConsultationJobOmit<ExtArgs> | null;
};
