/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ConsultationCustomer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model ConsultationCustomer
 *
 */
export type ConsultationCustomerModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ConsultationCustomerPayload>;

export type ConsultationCustomerNullableCompositeFilter = {
  equals?: Prisma.ConsultationCustomerObjectEqualityInput | null;
  is?: Prisma.ConsultationCustomerWhereInput | null;
  isNot?: Prisma.ConsultationCustomerWhereInput | null;
  isSet?: boolean;
};

export type ConsultationCustomerOrderByInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  displayName?: Prisma.SortOrder;
};

export type ConsultationCustomerNullableCreateEnvelopeInput = {
  set?: Prisma.ConsultationCustomerCreateInput | null;
};

export type ConsultationCustomerNullableUpdateEnvelopeInput = {
  set?: Prisma.ConsultationCustomerCreateInput | null;
  upsert?: Prisma.ConsultationCustomerUpsertInput;
  unset?: boolean;
};

export type ConsultationCustomerWhereInput = {
  AND?: Prisma.ConsultationCustomerWhereInput | Prisma.ConsultationCustomerWhereInput[];
  OR?: Prisma.ConsultationCustomerWhereInput[];
  NOT?: Prisma.ConsultationCustomerWhereInput | Prisma.ConsultationCustomerWhereInput[];
  id?: Prisma.BigIntNullableFilter<'ConsultationCustomer'> | bigint | number | null;
  name?: Prisma.StringNullableFilter<'ConsultationCustomer'> | string | null;
  displayName?: Prisma.StringNullableFilter<'ConsultationCustomer'> | string | null;
};

export type ConsultationCustomerUpsertInput = {
  set: Prisma.ConsultationCustomerCreateInput | null;
  update: Prisma.ConsultationCustomerUpdateInput;
};

export type ConsultationCustomerUpdateInput = {
  id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ConsultationCustomerSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    displayName?: boolean;
  },
  ExtArgs['result']['consultationCustomer']
>;

export type ConsultationCustomerSelectScalar = {
  id?: boolean;
  name?: boolean;
  displayName?: boolean;
};

export type ConsultationCustomerOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'name' | 'displayName',
  ExtArgs['result']['consultationCustomer']
>;

export type $ConsultationCustomerPayload = {
  name: 'ConsultationCustomer';
  objects: {};
  scalars: {
    id: bigint | null;
    name: string | null;
    displayName: string | null;
  };
  composites: {};
};

export type ConsultationCustomerGetPayload<
  S extends boolean | null | undefined | ConsultationCustomerDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ConsultationCustomerPayload, S>;

/**
 * Fields of the ConsultationCustomer model
 */
export interface ConsultationCustomerFieldRefs {
  readonly id: Prisma.FieldRef<'ConsultationCustomer', 'BigInt'>;
  readonly name: Prisma.FieldRef<'ConsultationCustomer', 'String'>;
  readonly displayName: Prisma.FieldRef<'ConsultationCustomer', 'String'>;
}

// Custom InputTypes
/**
 * ConsultationCustomer without action
 */
export type ConsultationCustomerDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ConsultationCustomer
   */
  select?: Prisma.ConsultationCustomerSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ConsultationCustomer
   */
  omit?: Prisma.ConsultationCustomerOmit<ExtArgs> | null;
};
