/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `EmployeeSkillAssignment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model EmployeeSkillAssignment
 *
 */
export type EmployeeSkillAssignmentModel =
  runtime.Types.Result.DefaultSelection<Prisma.$EmployeeSkillAssignmentPayload>;

export type EmployeeSkillAssignmentOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type EmployeeSkillAssignmentCompositeListFilter = {
  equals?: Prisma.EmployeeSkillAssignmentObjectEqualityInput[];
  every?: Prisma.EmployeeSkillAssignmentWhereInput;
  some?: Prisma.EmployeeSkillAssignmentWhereInput;
  none?: Prisma.EmployeeSkillAssignmentWhereInput;
  isEmpty?: boolean;
  isSet?: boolean;
};

export type EmployeeSkillAssignmentWhereInput = {
  AND?: Prisma.EmployeeSkillAssignmentWhereInput | Prisma.EmployeeSkillAssignmentWhereInput[];
  OR?: Prisma.EmployeeSkillAssignmentWhereInput[];
  NOT?: Prisma.EmployeeSkillAssignmentWhereInput | Prisma.EmployeeSkillAssignmentWhereInput[];
  id?: Prisma.StringNullableFilter<'EmployeeSkillAssignment'> | string | null;
  active?: Prisma.BoolNullableFilter<'EmployeeSkillAssignment'> | boolean | null;
  dateCertification?:
    | Prisma.DateTimeNullableFilter<'EmployeeSkillAssignment'>
    | Date
    | string
    | null;
  certification?: Prisma.XOR<
    Prisma.FileMetadataNullableCompositeFilter,
    Prisma.FileMetadataObjectEqualityInput
  > | null;
};

export type EmployeeSkillAssignmentListUpdateEnvelopeInput = {
  set?: Prisma.EmployeeSkillAssignmentCreateInput | Prisma.EmployeeSkillAssignmentCreateInput[];
  push?: Prisma.EmployeeSkillAssignmentCreateInput | Prisma.EmployeeSkillAssignmentCreateInput[];
  updateMany?: Prisma.EmployeeSkillAssignmentUpdateManyInput;
  deleteMany?: Prisma.EmployeeSkillAssignmentDeleteManyInput;
};

export type EmployeeSkillAssignmentUpdateManyInput = {
  where: Prisma.EmployeeSkillAssignmentWhereInput;
  data: Prisma.EmployeeSkillAssignmentUpdateInput;
};

export type EmployeeSkillAssignmentDeleteManyInput = {
  where: Prisma.EmployeeSkillAssignmentWhereInput;
};

export type EmployeeSkillAssignmentUpdateInput = {
  id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  active?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  dateCertification?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  certification?: Prisma.XOR<
    Prisma.FileMetadataNullableUpdateEnvelopeInput,
    Prisma.FileMetadataCreateInput
  > | null;
};

export type EmployeeSkillAssignmentSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    active?: boolean;
    dateCertification?: boolean;
    certification?: boolean | Prisma.FileMetadataDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['employeeSkillAssignment']
>;

export type EmployeeSkillAssignmentSelectScalar = {
  id?: boolean;
  active?: boolean;
  dateCertification?: boolean;
};

export type EmployeeSkillAssignmentOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'active' | 'dateCertification' | 'certification',
  ExtArgs['result']['employeeSkillAssignment']
>;
export type EmployeeSkillAssignmentInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $EmployeeSkillAssignmentPayload = {
  name: 'EmployeeSkillAssignment';
  objects: {};
  scalars: {
    id: string | null;
    active: boolean | null;
    dateCertification: Date | null;
  };
  composites: {
    certification: Prisma.$FileMetadataPayload | null;
  };
};

export type EmployeeSkillAssignmentGetPayload<
  S extends boolean | null | undefined | EmployeeSkillAssignmentDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$EmployeeSkillAssignmentPayload, S>;

/**
 * Fields of the EmployeeSkillAssignment model
 */
export interface EmployeeSkillAssignmentFieldRefs {
  readonly id: Prisma.FieldRef<'EmployeeSkillAssignment', 'String'>;
  readonly active: Prisma.FieldRef<'EmployeeSkillAssignment', 'Boolean'>;
  readonly dateCertification: Prisma.FieldRef<'EmployeeSkillAssignment', 'DateTime'>;
}

// Custom InputTypes
/**
 * EmployeeSkillAssignment without action
 */
export type EmployeeSkillAssignmentDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EmployeeSkillAssignment
   */
  select?: Prisma.EmployeeSkillAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EmployeeSkillAssignment
   */
  omit?: Prisma.EmployeeSkillAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeSkillAssignmentInclude<ExtArgs> | null;
};
