/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `EmployeeProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model EmployeeProfile
 *
 */
export type EmployeeProfileModel =
  runtime.Types.Result.DefaultSelection<Prisma.$EmployeeProfilePayload>;

export type EmployeeProfileNullableCompositeFilter = {
  equals?: Prisma.EmployeeProfileObjectEqualityInput | null;
  is?: Prisma.EmployeeProfileWhereInput | null;
  isNot?: Prisma.EmployeeProfileWhereInput | null;
  isSet?: boolean;
};

export type EmployeeProfileOrderByInput = {
  id?: Prisma.SortOrder;
  email2?: Prisma.SortOrder;
  activeSince?: Prisma.SortOrder;
  bank?: Prisma.SortOrder;
  iban?: Prisma.SortOrder;
  bic?: Prisma.SortOrder;
  taxid?: Prisma.SortOrder;
  uid?: Prisma.SortOrder;
  mailInvoice?: Prisma.SortOrder;
  postInvoice?: Prisma.SortOrder;
  shift?: Prisma.SortOrder;
  appointment?: Prisma.SortOrder;
  therapy?: Prisma.SortOrder;
  skills?: Prisma.EmployeeSkillAssignmentOrderByCompositeAggregateInput;
  exclusionCriteria?: Prisma.SortOrder;
  imageSignature?: Prisma.FileMetadataOrderByInput;
  bayernBoxAccess?: Prisma.BayernBoxAccessOrderByInput;
  categoriesWatched?: Prisma.WatchedCategoryOrderByCompositeAggregateInput;
};

export type EmployeeProfileNullableCreateEnvelopeInput = {
  set?: Prisma.EmployeeProfileCreateInput | null;
};

export type EmployeeProfileNullableUpdateEnvelopeInput = {
  set?: Prisma.EmployeeProfileCreateInput | null;
  upsert?: Prisma.EmployeeProfileUpsertInput;
  unset?: boolean;
};

export type EmployeeProfileWhereInput = {
  AND?: Prisma.EmployeeProfileWhereInput | Prisma.EmployeeProfileWhereInput[];
  OR?: Prisma.EmployeeProfileWhereInput[];
  NOT?: Prisma.EmployeeProfileWhereInput | Prisma.EmployeeProfileWhereInput[];
  id?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  email2?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  activeSince?: Prisma.DateTimeNullableFilter<'EmployeeProfile'> | Date | string | null;
  bank?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  iban?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  bic?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  taxid?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  uid?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  mailInvoice?: Prisma.BoolNullableFilter<'EmployeeProfile'> | boolean | null;
  postInvoice?: Prisma.BoolNullableFilter<'EmployeeProfile'> | boolean | null;
  shift?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  appointment?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  therapy?: Prisma.StringNullableFilter<'EmployeeProfile'> | string | null;
  skills?:
    | Prisma.EmployeeSkillAssignmentCompositeListFilter
    | Prisma.EmployeeSkillAssignmentObjectEqualityInput[];
  exclusionCriteria?: Prisma.StringNullableListFilter<'EmployeeProfile'>;
  imageSignature?: Prisma.XOR<
    Prisma.FileMetadataNullableCompositeFilter,
    Prisma.FileMetadataObjectEqualityInput
  > | null;
  bayernBoxAccess?: Prisma.XOR<
    Prisma.BayernBoxAccessNullableCompositeFilter,
    Prisma.BayernBoxAccessObjectEqualityInput
  > | null;
  categoriesWatched?:
    | Prisma.WatchedCategoryCompositeListFilter
    | Prisma.WatchedCategoryObjectEqualityInput[];
};

export type EmployeeSkillAssignmentObjectEqualityInput = {
  id?: string | null;
  active?: boolean | null;
  dateCertification?: Date | string | null;
  certification?: Prisma.FileMetadataObjectEqualityInput | null;
};

export type BayernBoxAccessObjectEqualityInput = {
  username?: string | null;
  password?: string | null;
};

export type WatchedCategoryObjectEqualityInput = {
  categoryId?: bigint | number | null;
  date?: Date | string | null;
};

export type EmployeeSkillAssignmentCreateInput = {
  id?: string | null;
  active?: boolean | null;
  dateCertification?: Date | string | null;
  certification?: Prisma.FileMetadataCreateInput | null;
};

export type EmployeeProfileCreateexclusionCriteriaInput = {
  set: string[];
};

export type BayernBoxAccessCreateInput = {
  username?: string | null;
  password?: string | null;
};

export type WatchedCategoryCreateInput = {
  categoryId?: bigint | number | null;
  date?: Date | string | null;
};

export type EmployeeProfileUpsertInput = {
  set: Prisma.EmployeeProfileCreateInput | null;
  update: Prisma.EmployeeProfileUpdateInput;
};

export type EmployeeProfileUpdateInput = {
  id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  email2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  activeSince?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  bank?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  iban?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  bic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  taxid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  uid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  mailInvoice?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  postInvoice?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  shift?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  appointment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  therapy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  skills?:
    | Prisma.XOR<
        Prisma.EmployeeSkillAssignmentListUpdateEnvelopeInput,
        Prisma.EmployeeSkillAssignmentCreateInput
      >
    | Prisma.EmployeeSkillAssignmentCreateInput[];
  exclusionCriteria?: Prisma.EmployeeProfileUpdateexclusionCriteriaInput | string[];
  imageSignature?: Prisma.XOR<
    Prisma.FileMetadataNullableUpdateEnvelopeInput,
    Prisma.FileMetadataCreateInput
  > | null;
  bayernBoxAccess?: Prisma.XOR<
    Prisma.BayernBoxAccessNullableUpdateEnvelopeInput,
    Prisma.BayernBoxAccessCreateInput
  > | null;
  categoriesWatched?:
    | Prisma.XOR<Prisma.WatchedCategoryListUpdateEnvelopeInput, Prisma.WatchedCategoryCreateInput>
    | Prisma.WatchedCategoryCreateInput[];
};

export type EmployeeProfileUpdateexclusionCriteriaInput = {
  set?: string[];
  push?: string | string[];
};

export type EmployeeProfileSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    email2?: boolean;
    activeSince?: boolean;
    bank?: boolean;
    iban?: boolean;
    bic?: boolean;
    taxid?: boolean;
    uid?: boolean;
    mailInvoice?: boolean;
    postInvoice?: boolean;
    shift?: boolean;
    appointment?: boolean;
    therapy?: boolean;
    skills?: boolean | Prisma.EmployeeSkillAssignmentDefaultArgs<ExtArgs>;
    exclusionCriteria?: boolean;
    imageSignature?: boolean | Prisma.FileMetadataDefaultArgs<ExtArgs>;
    bayernBoxAccess?: boolean | Prisma.BayernBoxAccessDefaultArgs<ExtArgs>;
    categoriesWatched?: boolean | Prisma.WatchedCategoryDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['employeeProfile']
>;

export type EmployeeProfileSelectScalar = {
  id?: boolean;
  email2?: boolean;
  activeSince?: boolean;
  bank?: boolean;
  iban?: boolean;
  bic?: boolean;
  taxid?: boolean;
  uid?: boolean;
  mailInvoice?: boolean;
  postInvoice?: boolean;
  shift?: boolean;
  appointment?: boolean;
  therapy?: boolean;
  exclusionCriteria?: boolean;
};

export type EmployeeProfileOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'email2'
  | 'activeSince'
  | 'bank'
  | 'iban'
  | 'bic'
  | 'taxid'
  | 'uid'
  | 'mailInvoice'
  | 'postInvoice'
  | 'shift'
  | 'appointment'
  | 'therapy'
  | 'skills'
  | 'exclusionCriteria'
  | 'imageSignature'
  | 'bayernBoxAccess'
  | 'categoriesWatched',
  ExtArgs['result']['employeeProfile']
>;
export type EmployeeProfileInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $EmployeeProfilePayload = {
  name: 'EmployeeProfile';
  objects: {};
  scalars: {
    id: string | null;
    email2: string | null;
    activeSince: Date | null;
    bank: string | null;
    iban: string | null;
    bic: string | null;
    taxid: string | null;
    uid: string | null;
    mailInvoice: boolean | null;
    postInvoice: boolean | null;
    shift: string | null;
    appointment: string | null;
    therapy: string | null;
    exclusionCriteria: string[];
  };
  composites: {
    skills: Prisma.$EmployeeSkillAssignmentPayload[];
    imageSignature: Prisma.$FileMetadataPayload | null;
    bayernBoxAccess: Prisma.$BayernBoxAccessPayload | null;
    categoriesWatched: Prisma.$WatchedCategoryPayload[];
  };
};

export type EmployeeProfileGetPayload<
  S extends boolean | null | undefined | EmployeeProfileDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$EmployeeProfilePayload, S>;

/**
 * Fields of the EmployeeProfile model
 */
export interface EmployeeProfileFieldRefs {
  readonly id: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly email2: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly activeSince: Prisma.FieldRef<'EmployeeProfile', 'DateTime'>;
  readonly bank: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly iban: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly bic: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly taxid: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly uid: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly mailInvoice: Prisma.FieldRef<'EmployeeProfile', 'Boolean'>;
  readonly postInvoice: Prisma.FieldRef<'EmployeeProfile', 'Boolean'>;
  readonly shift: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly appointment: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly therapy: Prisma.FieldRef<'EmployeeProfile', 'String'>;
  readonly exclusionCriteria: Prisma.FieldRef<'EmployeeProfile', 'String[]'>;
}

// Custom InputTypes
/**
 * EmployeeProfile without action
 */
export type EmployeeProfileDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EmployeeProfile
   */
  select?: Prisma.EmployeeProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EmployeeProfile
   */
  omit?: Prisma.EmployeeProfileOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeeProfileInclude<ExtArgs> | null;
};
