/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ExpertWeek` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model ExpertWeek
 *
 */
export type ExpertWeekModel = runtime.Types.Result.DefaultSelection<Prisma.$ExpertWeekPayload>;

export type AggregateExpertWeek = {
  _count: ExpertWeekCountAggregateOutputType | null;
  _avg: ExpertWeekAvgAggregateOutputType | null;
  _sum: ExpertWeekSumAggregateOutputType | null;
  _min: ExpertWeekMinAggregateOutputType | null;
  _max: ExpertWeekMaxAggregateOutputType | null;
};

export type ExpertWeekAvgAggregateOutputType = {
  id: number | null;
  version: number | null;
  userId: number | null;
  slotsMo: number | null;
  slotsTu: number | null;
  slotsWe: number | null;
  slotsTh: number | null;
  slotsFr: number | null;
  slotsSa: number | null;
  slotsSu: number | null;
};

export type ExpertWeekSumAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  userId: bigint | null;
  slotsMo: number[];
  slotsTu: number[];
  slotsWe: number[];
  slotsTh: number[];
  slotsFr: number[];
  slotsSa: number[];
  slotsSu: number[];
};

export type ExpertWeekMinAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  userId: bigint | null;
  type: string | null;
  dateChanged: Date | null;
  dateCreated: Date | null;
  class: string | null;
};

export type ExpertWeekMaxAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  userId: bigint | null;
  type: string | null;
  dateChanged: Date | null;
  dateCreated: Date | null;
  class: string | null;
};

export type ExpertWeekCountAggregateOutputType = {
  id: number;
  version: number;
  userId: number;
  type: number;
  slotsMo: number;
  slotsTu: number;
  slotsWe: number;
  slotsTh: number;
  slotsFr: number;
  slotsSa: number;
  slotsSu: number;
  dateChanged: number;
  dateCreated: number;
  class: number;
  _all: number;
};

export type ExpertWeekAvgAggregateInputType = {
  id?: true;
  version?: true;
  userId?: true;
  slotsMo?: true;
  slotsTu?: true;
  slotsWe?: true;
  slotsTh?: true;
  slotsFr?: true;
  slotsSa?: true;
  slotsSu?: true;
};

export type ExpertWeekSumAggregateInputType = {
  id?: true;
  version?: true;
  userId?: true;
  slotsMo?: true;
  slotsTu?: true;
  slotsWe?: true;
  slotsTh?: true;
  slotsFr?: true;
  slotsSa?: true;
  slotsSu?: true;
};

export type ExpertWeekMinAggregateInputType = {
  id?: true;
  version?: true;
  userId?: true;
  type?: true;
  dateChanged?: true;
  dateCreated?: true;
  class?: true;
};

export type ExpertWeekMaxAggregateInputType = {
  id?: true;
  version?: true;
  userId?: true;
  type?: true;
  dateChanged?: true;
  dateCreated?: true;
  class?: true;
};

export type ExpertWeekCountAggregateInputType = {
  id?: true;
  version?: true;
  userId?: true;
  type?: true;
  slotsMo?: true;
  slotsTu?: true;
  slotsWe?: true;
  slotsTh?: true;
  slotsFr?: true;
  slotsSa?: true;
  slotsSu?: true;
  dateChanged?: true;
  dateCreated?: true;
  class?: true;
  _all?: true;
};

export type ExpertWeekAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ExpertWeek to aggregate.
   */
  where?: Prisma.ExpertWeekWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ExpertWeeks to fetch.
   */
  orderBy?: Prisma.ExpertWeekOrderByWithRelationInput | Prisma.ExpertWeekOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ExpertWeekWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ExpertWeeks from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ExpertWeeks.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ExpertWeeks
   **/
  _count?: true | ExpertWeekCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: ExpertWeekAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: ExpertWeekSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ExpertWeekMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ExpertWeekMaxAggregateInputType;
};

export type GetExpertWeekAggregateType<T extends ExpertWeekAggregateArgs> = {
  [P in keyof T & keyof AggregateExpertWeek]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExpertWeek[P]>
    : Prisma.GetScalarType<T[P], AggregateExpertWeek[P]>;
};

export type ExpertWeekGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ExpertWeekWhereInput;
  orderBy?:
    | Prisma.ExpertWeekOrderByWithAggregationInput
    | Prisma.ExpertWeekOrderByWithAggregationInput[];
  by: Prisma.ExpertWeekScalarFieldEnum[] | Prisma.ExpertWeekScalarFieldEnum;
  having?: Prisma.ExpertWeekScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ExpertWeekCountAggregateInputType | true;
  _avg?: ExpertWeekAvgAggregateInputType;
  _sum?: ExpertWeekSumAggregateInputType;
  _min?: ExpertWeekMinAggregateInputType;
  _max?: ExpertWeekMaxAggregateInputType;
};

export type ExpertWeekGroupByOutputType = {
  id: bigint;
  version: bigint | null;
  userId: bigint | null;
  type: string | null;
  slotsMo: number[];
  slotsTu: number[];
  slotsWe: number[];
  slotsTh: number[];
  slotsFr: number[];
  slotsSa: number[];
  slotsSu: number[];
  dateChanged: Date | null;
  dateCreated: Date | null;
  class: string | null;
  _count: ExpertWeekCountAggregateOutputType | null;
  _avg: ExpertWeekAvgAggregateOutputType | null;
  _sum: ExpertWeekSumAggregateOutputType | null;
  _min: ExpertWeekMinAggregateOutputType | null;
  _max: ExpertWeekMaxAggregateOutputType | null;
};

type GetExpertWeekGroupByPayload<T extends ExpertWeekGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExpertWeekGroupByOutputType, T['by']> & {
      [P in keyof T & keyof ExpertWeekGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], ExpertWeekGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], ExpertWeekGroupByOutputType[P]>;
    }
  >
>;

export type ExpertWeekWhereInput = {
  AND?: Prisma.ExpertWeekWhereInput | Prisma.ExpertWeekWhereInput[];
  OR?: Prisma.ExpertWeekWhereInput[];
  NOT?: Prisma.ExpertWeekWhereInput | Prisma.ExpertWeekWhereInput[];
  id?: Prisma.BigIntFilter<'ExpertWeek'> | bigint | number;
  version?: Prisma.BigIntNullableFilter<'ExpertWeek'> | bigint | number | null;
  userId?: Prisma.BigIntNullableFilter<'ExpertWeek'> | bigint | number | null;
  type?: Prisma.StringNullableFilter<'ExpertWeek'> | string | null;
  slotsMo?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsTu?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsWe?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsTh?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsFr?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsSa?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsSu?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  dateChanged?: Prisma.DateTimeNullableFilter<'ExpertWeek'> | Date | string | null;
  dateCreated?: Prisma.DateTimeNullableFilter<'ExpertWeek'> | Date | string | null;
  class?: Prisma.StringNullableFilter<'ExpertWeek'> | string | null;
};

export type ExpertWeekOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  slotsMo?: Prisma.SortOrder;
  slotsTu?: Prisma.SortOrder;
  slotsWe?: Prisma.SortOrder;
  slotsTh?: Prisma.SortOrder;
  slotsFr?: Prisma.SortOrder;
  slotsSa?: Prisma.SortOrder;
  slotsSu?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type ExpertWeekWhereUniqueInput = Prisma.AtLeast<
  {
    id?: bigint | number;
    AND?: Prisma.ExpertWeekWhereInput | Prisma.ExpertWeekWhereInput[];
    OR?: Prisma.ExpertWeekWhereInput[];
    NOT?: Prisma.ExpertWeekWhereInput | Prisma.ExpertWeekWhereInput[];
    version?: Prisma.BigIntNullableFilter<'ExpertWeek'> | bigint | number | null;
    userId?: Prisma.BigIntNullableFilter<'ExpertWeek'> | bigint | number | null;
    type?: Prisma.StringNullableFilter<'ExpertWeek'> | string | null;
    slotsMo?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
    slotsTu?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
    slotsWe?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
    slotsTh?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
    slotsFr?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
    slotsSa?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
    slotsSu?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
    dateChanged?: Prisma.DateTimeNullableFilter<'ExpertWeek'> | Date | string | null;
    dateCreated?: Prisma.DateTimeNullableFilter<'ExpertWeek'> | Date | string | null;
    class?: Prisma.StringNullableFilter<'ExpertWeek'> | string | null;
  },
  'id'
>;

export type ExpertWeekOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  slotsMo?: Prisma.SortOrder;
  slotsTu?: Prisma.SortOrder;
  slotsWe?: Prisma.SortOrder;
  slotsTh?: Prisma.SortOrder;
  slotsFr?: Prisma.SortOrder;
  slotsSa?: Prisma.SortOrder;
  slotsSu?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
  _count?: Prisma.ExpertWeekCountOrderByAggregateInput;
  _avg?: Prisma.ExpertWeekAvgOrderByAggregateInput;
  _max?: Prisma.ExpertWeekMaxOrderByAggregateInput;
  _min?: Prisma.ExpertWeekMinOrderByAggregateInput;
  _sum?: Prisma.ExpertWeekSumOrderByAggregateInput;
};

export type ExpertWeekScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ExpertWeekScalarWhereWithAggregatesInput
    | Prisma.ExpertWeekScalarWhereWithAggregatesInput[];
  OR?: Prisma.ExpertWeekScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.ExpertWeekScalarWhereWithAggregatesInput
    | Prisma.ExpertWeekScalarWhereWithAggregatesInput[];
  id?: Prisma.BigIntWithAggregatesFilter<'ExpertWeek'> | bigint | number;
  version?: Prisma.BigIntNullableWithAggregatesFilter<'ExpertWeek'> | bigint | number | null;
  userId?: Prisma.BigIntNullableWithAggregatesFilter<'ExpertWeek'> | bigint | number | null;
  type?: Prisma.StringNullableWithAggregatesFilter<'ExpertWeek'> | string | null;
  slotsMo?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsTu?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsWe?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsTh?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsFr?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsSa?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  slotsSu?: Prisma.FloatNullableListFilter<'ExpertWeek'>;
  dateChanged?: Prisma.DateTimeNullableWithAggregatesFilter<'ExpertWeek'> | Date | string | null;
  dateCreated?: Prisma.DateTimeNullableWithAggregatesFilter<'ExpertWeek'> | Date | string | null;
  class?: Prisma.StringNullableWithAggregatesFilter<'ExpertWeek'> | string | null;
};

export type ExpertWeekCreateInput = {
  id: bigint | number;
  version?: bigint | number | null;
  userId?: bigint | number | null;
  type?: string | null;
  slotsMo?: Prisma.ExpertWeekCreateslotsMoInput | number[];
  slotsTu?: Prisma.ExpertWeekCreateslotsTuInput | number[];
  slotsWe?: Prisma.ExpertWeekCreateslotsWeInput | number[];
  slotsTh?: Prisma.ExpertWeekCreateslotsThInput | number[];
  slotsFr?: Prisma.ExpertWeekCreateslotsFrInput | number[];
  slotsSa?: Prisma.ExpertWeekCreateslotsSaInput | number[];
  slotsSu?: Prisma.ExpertWeekCreateslotsSuInput | number[];
  dateChanged?: Date | string | null;
  dateCreated?: Date | string | null;
  class?: string | null;
};

export type ExpertWeekUncheckedCreateInput = {
  id: bigint | number;
  version?: bigint | number | null;
  userId?: bigint | number | null;
  type?: string | null;
  slotsMo?: Prisma.ExpertWeekCreateslotsMoInput | number[];
  slotsTu?: Prisma.ExpertWeekCreateslotsTuInput | number[];
  slotsWe?: Prisma.ExpertWeekCreateslotsWeInput | number[];
  slotsTh?: Prisma.ExpertWeekCreateslotsThInput | number[];
  slotsFr?: Prisma.ExpertWeekCreateslotsFrInput | number[];
  slotsSa?: Prisma.ExpertWeekCreateslotsSaInput | number[];
  slotsSu?: Prisma.ExpertWeekCreateslotsSuInput | number[];
  dateChanged?: Date | string | null;
  dateCreated?: Date | string | null;
  class?: string | null;
};

export type ExpertWeekUpdateInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  userId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  slotsMo?: Prisma.ExpertWeekUpdateslotsMoInput | number[];
  slotsTu?: Prisma.ExpertWeekUpdateslotsTuInput | number[];
  slotsWe?: Prisma.ExpertWeekUpdateslotsWeInput | number[];
  slotsTh?: Prisma.ExpertWeekUpdateslotsThInput | number[];
  slotsFr?: Prisma.ExpertWeekUpdateslotsFrInput | number[];
  slotsSa?: Prisma.ExpertWeekUpdateslotsSaInput | number[];
  slotsSu?: Prisma.ExpertWeekUpdateslotsSuInput | number[];
  dateChanged?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ExpertWeekUncheckedUpdateInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  userId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  slotsMo?: Prisma.ExpertWeekUpdateslotsMoInput | number[];
  slotsTu?: Prisma.ExpertWeekUpdateslotsTuInput | number[];
  slotsWe?: Prisma.ExpertWeekUpdateslotsWeInput | number[];
  slotsTh?: Prisma.ExpertWeekUpdateslotsThInput | number[];
  slotsFr?: Prisma.ExpertWeekUpdateslotsFrInput | number[];
  slotsSa?: Prisma.ExpertWeekUpdateslotsSaInput | number[];
  slotsSu?: Prisma.ExpertWeekUpdateslotsSuInput | number[];
  dateChanged?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ExpertWeekCreateManyInput = {
  id: bigint | number;
  version?: bigint | number | null;
  userId?: bigint | number | null;
  type?: string | null;
  slotsMo?: Prisma.ExpertWeekCreateslotsMoInput | number[];
  slotsTu?: Prisma.ExpertWeekCreateslotsTuInput | number[];
  slotsWe?: Prisma.ExpertWeekCreateslotsWeInput | number[];
  slotsTh?: Prisma.ExpertWeekCreateslotsThInput | number[];
  slotsFr?: Prisma.ExpertWeekCreateslotsFrInput | number[];
  slotsSa?: Prisma.ExpertWeekCreateslotsSaInput | number[];
  slotsSu?: Prisma.ExpertWeekCreateslotsSuInput | number[];
  dateChanged?: Date | string | null;
  dateCreated?: Date | string | null;
  class?: string | null;
};

export type ExpertWeekUpdateManyMutationInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  userId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  slotsMo?: Prisma.ExpertWeekUpdateslotsMoInput | number[];
  slotsTu?: Prisma.ExpertWeekUpdateslotsTuInput | number[];
  slotsWe?: Prisma.ExpertWeekUpdateslotsWeInput | number[];
  slotsTh?: Prisma.ExpertWeekUpdateslotsThInput | number[];
  slotsFr?: Prisma.ExpertWeekUpdateslotsFrInput | number[];
  slotsSa?: Prisma.ExpertWeekUpdateslotsSaInput | number[];
  slotsSu?: Prisma.ExpertWeekUpdateslotsSuInput | number[];
  dateChanged?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type ExpertWeekUncheckedUpdateManyInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  userId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  slotsMo?: Prisma.ExpertWeekUpdateslotsMoInput | number[];
  slotsTu?: Prisma.ExpertWeekUpdateslotsTuInput | number[];
  slotsWe?: Prisma.ExpertWeekUpdateslotsWeInput | number[];
  slotsTh?: Prisma.ExpertWeekUpdateslotsThInput | number[];
  slotsFr?: Prisma.ExpertWeekUpdateslotsFrInput | number[];
  slotsSa?: Prisma.ExpertWeekUpdateslotsSaInput | number[];
  slotsSu?: Prisma.ExpertWeekUpdateslotsSuInput | number[];
  dateChanged?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type FloatNullableListFilter<$PrismaModel = never> = {
  equals?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null;
  has?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null;
  hasEvery?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  hasSome?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
  isEmpty?: boolean;
};

export type ExpertWeekCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  slotsMo?: Prisma.SortOrder;
  slotsTu?: Prisma.SortOrder;
  slotsWe?: Prisma.SortOrder;
  slotsTh?: Prisma.SortOrder;
  slotsFr?: Prisma.SortOrder;
  slotsSa?: Prisma.SortOrder;
  slotsSu?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type ExpertWeekAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  slotsMo?: Prisma.SortOrder;
  slotsTu?: Prisma.SortOrder;
  slotsWe?: Prisma.SortOrder;
  slotsTh?: Prisma.SortOrder;
  slotsFr?: Prisma.SortOrder;
  slotsSa?: Prisma.SortOrder;
  slotsSu?: Prisma.SortOrder;
};

export type ExpertWeekMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type ExpertWeekMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type ExpertWeekSumOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  slotsMo?: Prisma.SortOrder;
  slotsTu?: Prisma.SortOrder;
  slotsWe?: Prisma.SortOrder;
  slotsTh?: Prisma.SortOrder;
  slotsFr?: Prisma.SortOrder;
  slotsSa?: Prisma.SortOrder;
  slotsSu?: Prisma.SortOrder;
};

export type ExpertWeekCreateslotsMoInput = {
  set: number[];
};

export type ExpertWeekCreateslotsTuInput = {
  set: number[];
};

export type ExpertWeekCreateslotsWeInput = {
  set: number[];
};

export type ExpertWeekCreateslotsThInput = {
  set: number[];
};

export type ExpertWeekCreateslotsFrInput = {
  set: number[];
};

export type ExpertWeekCreateslotsSaInput = {
  set: number[];
};

export type ExpertWeekCreateslotsSuInput = {
  set: number[];
};

export type NullableBigIntFieldUpdateOperationsInput = {
  set?: bigint | number | null;
  increment?: bigint | number;
  decrement?: bigint | number;
  multiply?: bigint | number;
  divide?: bigint | number;
  unset?: boolean;
};

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null;
  unset?: boolean;
};

export type ExpertWeekUpdateslotsMoInput = {
  set?: number[];
  push?: number | number[];
};

export type ExpertWeekUpdateslotsTuInput = {
  set?: number[];
  push?: number | number[];
};

export type ExpertWeekUpdateslotsWeInput = {
  set?: number[];
  push?: number | number[];
};

export type ExpertWeekUpdateslotsThInput = {
  set?: number[];
  push?: number | number[];
};

export type ExpertWeekUpdateslotsFrInput = {
  set?: number[];
  push?: number | number[];
};

export type ExpertWeekUpdateslotsSaInput = {
  set?: number[];
  push?: number | number[];
};

export type ExpertWeekUpdateslotsSuInput = {
  set?: number[];
  push?: number | number[];
};

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null;
  unset?: boolean;
};

export type ExpertWeekSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    version?: boolean;
    userId?: boolean;
    type?: boolean;
    slotsMo?: boolean;
    slotsTu?: boolean;
    slotsWe?: boolean;
    slotsTh?: boolean;
    slotsFr?: boolean;
    slotsSa?: boolean;
    slotsSu?: boolean;
    dateChanged?: boolean;
    dateCreated?: boolean;
    class?: boolean;
  },
  ExtArgs['result']['expertWeek']
>;

export type ExpertWeekSelectScalar = {
  id?: boolean;
  version?: boolean;
  userId?: boolean;
  type?: boolean;
  slotsMo?: boolean;
  slotsTu?: boolean;
  slotsWe?: boolean;
  slotsTh?: boolean;
  slotsFr?: boolean;
  slotsSa?: boolean;
  slotsSu?: boolean;
  dateChanged?: boolean;
  dateCreated?: boolean;
  class?: boolean;
};

export type ExpertWeekOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'version'
  | 'userId'
  | 'type'
  | 'slotsMo'
  | 'slotsTu'
  | 'slotsWe'
  | 'slotsTh'
  | 'slotsFr'
  | 'slotsSa'
  | 'slotsSu'
  | 'dateChanged'
  | 'dateCreated'
  | 'class',
  ExtArgs['result']['expertWeek']
>;

export type $ExpertWeekPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'ExpertWeek';
  objects: {};
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: bigint;
      version: bigint | null;
      userId: bigint | null;
      type: string | null;
      slotsMo: number[];
      slotsTu: number[];
      slotsWe: number[];
      slotsTh: number[];
      slotsFr: number[];
      slotsSa: number[];
      slotsSu: number[];
      dateChanged: Date | null;
      dateCreated: Date | null;
      class: string | null;
    },
    ExtArgs['result']['expertWeek']
  >;
  composites: {};
};

export type ExpertWeekGetPayload<S extends boolean | null | undefined | ExpertWeekDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$ExpertWeekPayload, S>;

export type ExpertWeekCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ExpertWeekFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ExpertWeekCountAggregateInputType | true;
};

export interface ExpertWeekDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['ExpertWeek'];
    meta: { name: 'ExpertWeek' };
  };
  /**
   * Find zero or one ExpertWeek that matches the filter.
   * @param {ExpertWeekFindUniqueArgs} args - Arguments to find a ExpertWeek
   * @example
   * // Get one ExpertWeek
   * const expertWeek = await prisma.expertWeek.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExpertWeekFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ExpertWeekFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__ExpertWeekClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one ExpertWeek that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExpertWeekFindUniqueOrThrowArgs} args - Arguments to find a ExpertWeek
   * @example
   * // Get one ExpertWeek
   * const expertWeek = await prisma.expertWeek.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExpertWeekFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ExpertWeekFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ExpertWeekClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ExpertWeek that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpertWeekFindFirstArgs} args - Arguments to find a ExpertWeek
   * @example
   * // Get one ExpertWeek
   * const expertWeek = await prisma.expertWeek.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExpertWeekFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ExpertWeekFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__ExpertWeekClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ExpertWeek that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpertWeekFindFirstOrThrowArgs} args - Arguments to find a ExpertWeek
   * @example
   * // Get one ExpertWeek
   * const expertWeek = await prisma.expertWeek.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExpertWeekFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ExpertWeekFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ExpertWeekClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ExpertWeeks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpertWeekFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ExpertWeeks
   * const expertWeeks = await prisma.expertWeek.findMany()
   *
   * // Get first 10 ExpertWeeks
   * const expertWeeks = await prisma.expertWeek.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const expertWeekWithIdOnly = await prisma.expertWeek.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ExpertWeekFindManyArgs>(
    args?: Prisma.SelectSubset<T, ExpertWeekFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a ExpertWeek.
   * @param {ExpertWeekCreateArgs} args - Arguments to create a ExpertWeek.
   * @example
   * // Create one ExpertWeek
   * const ExpertWeek = await prisma.expertWeek.create({
   *   data: {
   *     // ... data to create a ExpertWeek
   *   }
   * })
   *
   */
  create<T extends ExpertWeekCreateArgs>(
    args: Prisma.SelectSubset<T, ExpertWeekCreateArgs<ExtArgs>>
  ): Prisma.Prisma__ExpertWeekClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many ExpertWeeks.
   * @param {ExpertWeekCreateManyArgs} args - Arguments to create many ExpertWeeks.
   * @example
   * // Create many ExpertWeeks
   * const expertWeek = await prisma.expertWeek.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ExpertWeekCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ExpertWeekCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Delete a ExpertWeek.
   * @param {ExpertWeekDeleteArgs} args - Arguments to delete one ExpertWeek.
   * @example
   * // Delete one ExpertWeek
   * const ExpertWeek = await prisma.expertWeek.delete({
   *   where: {
   *     // ... filter to delete one ExpertWeek
   *   }
   * })
   *
   */
  delete<T extends ExpertWeekDeleteArgs>(
    args: Prisma.SelectSubset<T, ExpertWeekDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__ExpertWeekClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one ExpertWeek.
   * @param {ExpertWeekUpdateArgs} args - Arguments to update one ExpertWeek.
   * @example
   * // Update one ExpertWeek
   * const expertWeek = await prisma.expertWeek.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ExpertWeekUpdateArgs>(
    args: Prisma.SelectSubset<T, ExpertWeekUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__ExpertWeekClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more ExpertWeeks.
   * @param {ExpertWeekDeleteManyArgs} args - Arguments to filter ExpertWeeks to delete.
   * @example
   * // Delete a few ExpertWeeks
   * const { count } = await prisma.expertWeek.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ExpertWeekDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ExpertWeekDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ExpertWeeks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpertWeekUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ExpertWeeks
   * const expertWeek = await prisma.expertWeek.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ExpertWeekUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ExpertWeekUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create or update one ExpertWeek.
   * @param {ExpertWeekUpsertArgs} args - Arguments to update or create a ExpertWeek.
   * @example
   * // Update or create a ExpertWeek
   * const expertWeek = await prisma.expertWeek.upsert({
   *   create: {
   *     // ... data to create a ExpertWeek
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ExpertWeek we want to update
   *   }
   * })
   */
  upsert<T extends ExpertWeekUpsertArgs>(
    args: Prisma.SelectSubset<T, ExpertWeekUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__ExpertWeekClient<
    runtime.Types.Result.GetResult<
      Prisma.$ExpertWeekPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ExpertWeeks that matches the filter.
   * @param {ExpertWeekFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const expertWeek = await prisma.expertWeek.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.ExpertWeekFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>;

  /**
   * Perform aggregation operations on a ExpertWeek.
   * @param {ExpertWeekAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const expertWeek = await prisma.expertWeek.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.ExpertWeekAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>;

  /**
   * Count the number of ExpertWeeks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpertWeekCountArgs} args - Arguments to filter ExpertWeeks to count.
   * @example
   * // Count the number of ExpertWeeks
   * const count = await prisma.expertWeek.count({
   *   where: {
   *     // ... the filter for the ExpertWeeks we want to count
   *   }
   * })
   **/
  count<T extends ExpertWeekCountArgs>(
    args?: Prisma.Subset<T, ExpertWeekCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExpertWeekCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a ExpertWeek.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpertWeekAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ExpertWeekAggregateArgs>(
    args: Prisma.Subset<T, ExpertWeekAggregateArgs>
  ): Prisma.PrismaPromise<GetExpertWeekAggregateType<T>>;

  /**
   * Group by ExpertWeek.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExpertWeekGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ExpertWeekGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExpertWeekGroupByArgs['orderBy'] }
      : { orderBy?: ExpertWeekGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, ExpertWeekGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetExpertWeekGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ExpertWeek model
   */
  readonly fields: ExpertWeekFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ExpertWeek.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExpertWeekClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ExpertWeek model
 */
export interface ExpertWeekFieldRefs {
  readonly id: Prisma.FieldRef<'ExpertWeek', 'BigInt'>;
  readonly version: Prisma.FieldRef<'ExpertWeek', 'BigInt'>;
  readonly userId: Prisma.FieldRef<'ExpertWeek', 'BigInt'>;
  readonly type: Prisma.FieldRef<'ExpertWeek', 'String'>;
  readonly slotsMo: Prisma.FieldRef<'ExpertWeek', 'Float[]'>;
  readonly slotsTu: Prisma.FieldRef<'ExpertWeek', 'Float[]'>;
  readonly slotsWe: Prisma.FieldRef<'ExpertWeek', 'Float[]'>;
  readonly slotsTh: Prisma.FieldRef<'ExpertWeek', 'Float[]'>;
  readonly slotsFr: Prisma.FieldRef<'ExpertWeek', 'Float[]'>;
  readonly slotsSa: Prisma.FieldRef<'ExpertWeek', 'Float[]'>;
  readonly slotsSu: Prisma.FieldRef<'ExpertWeek', 'Float[]'>;
  readonly dateChanged: Prisma.FieldRef<'ExpertWeek', 'DateTime'>;
  readonly dateCreated: Prisma.FieldRef<'ExpertWeek', 'DateTime'>;
  readonly class: Prisma.FieldRef<'ExpertWeek', 'String'>;
}

// Custom InputTypes
/**
 * ExpertWeek findUnique
 */
export type ExpertWeekFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * Filter, which ExpertWeek to fetch.
   */
  where: Prisma.ExpertWeekWhereUniqueInput;
};

/**
 * ExpertWeek findUniqueOrThrow
 */
export type ExpertWeekFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * Filter, which ExpertWeek to fetch.
   */
  where: Prisma.ExpertWeekWhereUniqueInput;
};

/**
 * ExpertWeek findFirst
 */
export type ExpertWeekFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * Filter, which ExpertWeek to fetch.
   */
  where?: Prisma.ExpertWeekWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ExpertWeeks to fetch.
   */
  orderBy?: Prisma.ExpertWeekOrderByWithRelationInput | Prisma.ExpertWeekOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ExpertWeeks.
   */
  cursor?: Prisma.ExpertWeekWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ExpertWeeks from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ExpertWeeks.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ExpertWeeks.
   */
  distinct?: Prisma.ExpertWeekScalarFieldEnum | Prisma.ExpertWeekScalarFieldEnum[];
};

/**
 * ExpertWeek findFirstOrThrow
 */
export type ExpertWeekFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * Filter, which ExpertWeek to fetch.
   */
  where?: Prisma.ExpertWeekWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ExpertWeeks to fetch.
   */
  orderBy?: Prisma.ExpertWeekOrderByWithRelationInput | Prisma.ExpertWeekOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ExpertWeeks.
   */
  cursor?: Prisma.ExpertWeekWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ExpertWeeks from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ExpertWeeks.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ExpertWeeks.
   */
  distinct?: Prisma.ExpertWeekScalarFieldEnum | Prisma.ExpertWeekScalarFieldEnum[];
};

/**
 * ExpertWeek findMany
 */
export type ExpertWeekFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * Filter, which ExpertWeeks to fetch.
   */
  where?: Prisma.ExpertWeekWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ExpertWeeks to fetch.
   */
  orderBy?: Prisma.ExpertWeekOrderByWithRelationInput | Prisma.ExpertWeekOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ExpertWeeks.
   */
  cursor?: Prisma.ExpertWeekWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ExpertWeeks from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ExpertWeeks.
   */
  skip?: number;
  distinct?: Prisma.ExpertWeekScalarFieldEnum | Prisma.ExpertWeekScalarFieldEnum[];
};

/**
 * ExpertWeek create
 */
export type ExpertWeekCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * The data needed to create a ExpertWeek.
   */
  data: Prisma.XOR<Prisma.ExpertWeekCreateInput, Prisma.ExpertWeekUncheckedCreateInput>;
};

/**
 * ExpertWeek createMany
 */
export type ExpertWeekCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ExpertWeeks.
   */
  data: Prisma.ExpertWeekCreateManyInput | Prisma.ExpertWeekCreateManyInput[];
};

/**
 * ExpertWeek update
 */
export type ExpertWeekUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * The data needed to update a ExpertWeek.
   */
  data: Prisma.XOR<Prisma.ExpertWeekUpdateInput, Prisma.ExpertWeekUncheckedUpdateInput>;
  /**
   * Choose, which ExpertWeek to update.
   */
  where: Prisma.ExpertWeekWhereUniqueInput;
};

/**
 * ExpertWeek updateMany
 */
export type ExpertWeekUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ExpertWeeks.
   */
  data: Prisma.XOR<
    Prisma.ExpertWeekUpdateManyMutationInput,
    Prisma.ExpertWeekUncheckedUpdateManyInput
  >;
  /**
   * Filter which ExpertWeeks to update
   */
  where?: Prisma.ExpertWeekWhereInput;
  /**
   * Limit how many ExpertWeeks to update.
   */
  limit?: number;
};

/**
 * ExpertWeek upsert
 */
export type ExpertWeekUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * The filter to search for the ExpertWeek to update in case it exists.
   */
  where: Prisma.ExpertWeekWhereUniqueInput;
  /**
   * In case the ExpertWeek found by the `where` argument doesn't exist, create a new ExpertWeek with this data.
   */
  create: Prisma.XOR<Prisma.ExpertWeekCreateInput, Prisma.ExpertWeekUncheckedCreateInput>;
  /**
   * In case the ExpertWeek was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExpertWeekUpdateInput, Prisma.ExpertWeekUncheckedUpdateInput>;
};

/**
 * ExpertWeek delete
 */
export type ExpertWeekDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
  /**
   * Filter which ExpertWeek to delete.
   */
  where: Prisma.ExpertWeekWhereUniqueInput;
};

/**
 * ExpertWeek deleteMany
 */
export type ExpertWeekDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ExpertWeeks to delete
   */
  where?: Prisma.ExpertWeekWhereInput;
  /**
   * Limit how many ExpertWeeks to delete.
   */
  limit?: number;
};

/**
 * ExpertWeek findRaw
 */
export type ExpertWeekFindRawArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue;
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue;
};

/**
 * ExpertWeek aggregateRaw
 */
export type ExpertWeekAggregateRawArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[];
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue;
};

/**
 * ExpertWeek without action
 */
export type ExpertWeekDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExpertWeek
   */
  select?: Prisma.ExpertWeekSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExpertWeek
   */
  omit?: Prisma.ExpertWeekOmit<ExtArgs> | null;
};
