/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `FileMetadata` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model FileMetadata
 *
 */
export type FileMetadataModel = runtime.Types.Result.DefaultSelection<Prisma.$FileMetadataPayload>;

export type FileMetadataOrderByInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  mime?: Prisma.SortOrder;
  size?: Prisma.SortOrder;
  checksum?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
};

export type FileMetadataNullableCompositeFilter = {
  equals?: Prisma.FileMetadataObjectEqualityInput | null;
  is?: Prisma.FileMetadataWhereInput | null;
  isNot?: Prisma.FileMetadataWhereInput | null;
  isSet?: boolean;
};

export type FileMetadataWhereInput = {
  AND?: Prisma.FileMetadataWhereInput | Prisma.FileMetadataWhereInput[];
  OR?: Prisma.FileMetadataWhereInput[];
  NOT?: Prisma.FileMetadataWhereInput | Prisma.FileMetadataWhereInput[];
  id?: Prisma.StringNullableFilter<'FileMetadata'> | string | null;
  name?: Prisma.StringNullableFilter<'FileMetadata'> | string | null;
  mime?: Prisma.StringNullableFilter<'FileMetadata'> | string | null;
  size?: Prisma.BigIntNullableFilter<'FileMetadata'> | bigint | number | null;
  checksum?: Prisma.StringNullableFilter<'FileMetadata'> | string | null;
  type?: Prisma.StringNullableFilter<'FileMetadata'> | string | null;
  dateCreated?: Prisma.DateTimeNullableFilter<'FileMetadata'> | Date | string | null;
};

export type FileMetadataNullableUpdateEnvelopeInput = {
  set?: Prisma.FileMetadataCreateInput | null;
  upsert?: Prisma.FileMetadataUpsertInput;
  unset?: boolean;
};

export type FileMetadataUpsertInput = {
  set: Prisma.FileMetadataCreateInput | null;
  update: Prisma.FileMetadataUpdateInput;
};

export type FileMetadataUpdateInput = {
  id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  mime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  size?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type FileMetadataSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    mime?: boolean;
    size?: boolean;
    checksum?: boolean;
    type?: boolean;
    dateCreated?: boolean;
  },
  ExtArgs['result']['fileMetadata']
>;

export type FileMetadataSelectScalar = {
  id?: boolean;
  name?: boolean;
  mime?: boolean;
  size?: boolean;
  checksum?: boolean;
  type?: boolean;
  dateCreated?: boolean;
};

export type FileMetadataOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'name' | 'mime' | 'size' | 'checksum' | 'type' | 'dateCreated',
  ExtArgs['result']['fileMetadata']
>;

export type $FileMetadataPayload = {
  name: 'FileMetadata';
  objects: {};
  scalars: {
    id: string | null;
    name: string | null;
    mime: string | null;
    size: bigint | null;
    checksum: string | null;
    type: string | null;
    dateCreated: Date | null;
  };
  composites: {};
};

export type FileMetadataGetPayload<S extends boolean | null | undefined | FileMetadataDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$FileMetadataPayload, S>;

/**
 * Fields of the FileMetadata model
 */
export interface FileMetadataFieldRefs {
  readonly id: Prisma.FieldRef<'FileMetadata', 'String'>;
  readonly name: Prisma.FieldRef<'FileMetadata', 'String'>;
  readonly mime: Prisma.FieldRef<'FileMetadata', 'String'>;
  readonly size: Prisma.FieldRef<'FileMetadata', 'BigInt'>;
  readonly checksum: Prisma.FieldRef<'FileMetadata', 'String'>;
  readonly type: Prisma.FieldRef<'FileMetadata', 'String'>;
  readonly dateCreated: Prisma.FieldRef<'FileMetadata', 'DateTime'>;
}

// Custom InputTypes
/**
 * FileMetadata without action
 */
export type FileMetadataDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FileMetadata
   */
  select?: Prisma.FileMetadataSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the FileMetadata
   */
  omit?: Prisma.FileMetadataOmit<ExtArgs> | null;
};
