/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `LoginEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model LoginEvent
 *
 */
export type LoginEventModel = runtime.Types.Result.DefaultSelection<Prisma.$LoginEventPayload>;

export type LoginEventCompositeListFilter = {
  equals?: Prisma.LoginEventObjectEqualityInput[];
  every?: Prisma.LoginEventWhereInput;
  some?: Prisma.LoginEventWhereInput;
  none?: Prisma.LoginEventWhereInput;
  isEmpty?: boolean;
  isSet?: boolean;
};

export type LoginEventOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type LoginEventListCreateEnvelopeInput = {
  set?: Prisma.LoginEventCreateInput | Prisma.LoginEventCreateInput[];
};

export type LoginEventListUpdateEnvelopeInput = {
  set?: Prisma.LoginEventCreateInput | Prisma.LoginEventCreateInput[];
  push?: Prisma.LoginEventCreateInput | Prisma.LoginEventCreateInput[];
  updateMany?: Prisma.LoginEventUpdateManyInput;
  deleteMany?: Prisma.LoginEventDeleteManyInput;
};

export type LoginEventWhereInput = {
  AND?: Prisma.LoginEventWhereInput | Prisma.LoginEventWhereInput[];
  OR?: Prisma.LoginEventWhereInput[];
  NOT?: Prisma.LoginEventWhereInput | Prisma.LoginEventWhereInput[];
  ip?: Prisma.StringNullableFilter<'LoginEvent'> | string | null;
  date?: Prisma.DateTimeNullableFilter<'LoginEvent'> | Date | string | null;
  first?: Prisma.DateTimeNullableFilter<'LoginEvent'> | Date | string | null;
  ua?: Prisma.StringNullableFilter<'LoginEvent'> | string | null;
  count?: Prisma.IntNullableFilter<'LoginEvent'> | number | null;
};

export type LoginEventUpdateManyInput = {
  where: Prisma.LoginEventWhereInput;
  data: Prisma.LoginEventUpdateInput;
};

export type LoginEventDeleteManyInput = {
  where: Prisma.LoginEventWhereInput;
};

export type LoginEventUpdateInput = {
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  first?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  ua?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
};

export type LoginEventSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    ip?: boolean;
    date?: boolean;
    first?: boolean;
    ua?: boolean;
    count?: boolean;
  },
  ExtArgs['result']['loginEvent']
>;

export type LoginEventSelectScalar = {
  ip?: boolean;
  date?: boolean;
  first?: boolean;
  ua?: boolean;
  count?: boolean;
};

export type LoginEventOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'ip' | 'date' | 'first' | 'ua' | 'count',
  ExtArgs['result']['loginEvent']
>;

export type $LoginEventPayload = {
  name: 'LoginEvent';
  objects: {};
  scalars: {
    ip: string | null;
    date: Date | null;
    first: Date | null;
    ua: string | null;
    count: number | null;
  };
  composites: {};
};

export type LoginEventGetPayload<S extends boolean | null | undefined | LoginEventDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$LoginEventPayload, S>;

/**
 * Fields of the LoginEvent model
 */
export interface LoginEventFieldRefs {
  readonly ip: Prisma.FieldRef<'LoginEvent', 'String'>;
  readonly date: Prisma.FieldRef<'LoginEvent', 'DateTime'>;
  readonly first: Prisma.FieldRef<'LoginEvent', 'DateTime'>;
  readonly ua: Prisma.FieldRef<'LoginEvent', 'String'>;
  readonly count: Prisma.FieldRef<'LoginEvent', 'Int'>;
}

// Custom InputTypes
/**
 * LoginEvent without action
 */
export type LoginEventDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the LoginEvent
   */
  select?: Prisma.LoginEventSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the LoginEvent
   */
  omit?: Prisma.LoginEventOmit<ExtArgs> | null;
};
