/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TotpActivity` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TotpActivity
 *
 */
export type TotpActivityModel = runtime.Types.Result.DefaultSelection<Prisma.$TotpActivityPayload>;

export type TotpActivityNullableCompositeFilter = {
  equals?: Prisma.TotpActivityObjectEqualityInput | null;
  is?: Prisma.TotpActivityWhereInput | null;
  isNot?: Prisma.TotpActivityWhereInput | null;
  isSet?: boolean;
};

export type TotpActivityOrderByInput = {
  dateAccess?: Prisma.SortOrder;
  ip?: Prisma.SortOrder;
  ua?: Prisma.SortOrder;
  action?: Prisma.SortOrder;
};

export type TotpActivityNullableCreateEnvelopeInput = {
  set?: Prisma.TotpActivityCreateInput | null;
};

export type TotpActivityNullableUpdateEnvelopeInput = {
  set?: Prisma.TotpActivityCreateInput | null;
  upsert?: Prisma.TotpActivityUpsertInput;
  unset?: boolean;
};

export type TotpActivityWhereInput = {
  AND?: Prisma.TotpActivityWhereInput | Prisma.TotpActivityWhereInput[];
  OR?: Prisma.TotpActivityWhereInput[];
  NOT?: Prisma.TotpActivityWhereInput | Prisma.TotpActivityWhereInput[];
  dateAccess?: Prisma.DateTimeNullableFilter<'TotpActivity'> | Date | string | null;
  ip?: Prisma.StringNullableFilter<'TotpActivity'> | string | null;
  ua?: Prisma.StringNullableFilter<'TotpActivity'> | string | null;
  action?: Prisma.StringNullableFilter<'TotpActivity'> | string | null;
};

export type TotpActivityUpsertInput = {
  set: Prisma.TotpActivityCreateInput | null;
  update: Prisma.TotpActivityUpdateInput;
};

export type TotpActivityUpdateInput = {
  dateAccess?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  ua?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  action?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type TotpActivitySelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    dateAccess?: boolean;
    ip?: boolean;
    ua?: boolean;
    action?: boolean;
  },
  ExtArgs['result']['totpActivity']
>;

export type TotpActivitySelectScalar = {
  dateAccess?: boolean;
  ip?: boolean;
  ua?: boolean;
  action?: boolean;
};

export type TotpActivityOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'dateAccess' | 'ip' | 'ua' | 'action',
  ExtArgs['result']['totpActivity']
>;

export type $TotpActivityPayload = {
  name: 'TotpActivity';
  objects: {};
  scalars: {
    dateAccess: Date | null;
    ip: string | null;
    ua: string | null;
    action: string | null;
  };
  composites: {};
};

export type TotpActivityGetPayload<S extends boolean | null | undefined | TotpActivityDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$TotpActivityPayload, S>;

/**
 * Fields of the TotpActivity model
 */
export interface TotpActivityFieldRefs {
  readonly dateAccess: Prisma.FieldRef<'TotpActivity', 'DateTime'>;
  readonly ip: Prisma.FieldRef<'TotpActivity', 'String'>;
  readonly ua: Prisma.FieldRef<'TotpActivity', 'String'>;
  readonly action: Prisma.FieldRef<'TotpActivity', 'String'>;
}

// Custom InputTypes
/**
 * TotpActivity without action
 */
export type TotpActivityDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TotpActivity
   */
  select?: Prisma.TotpActivitySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TotpActivity
   */
  omit?: Prisma.TotpActivityOmit<ExtArgs> | null;
};
