/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TotpDevice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TotpDevice
 *
 */
export type TotpDeviceModel = runtime.Types.Result.DefaultSelection<Prisma.$TotpDevicePayload>;

export type TotpDeviceNullableCompositeFilter = {
  equals?: Prisma.TotpDeviceObjectEqualityInput | null;
  is?: Prisma.TotpDeviceWhereInput | null;
  isNot?: Prisma.TotpDeviceWhereInput | null;
  isSet?: boolean;
};

export type TotpDeviceOrderByInput = {
  ip?: Prisma.SortOrder;
  dateRegistered?: Prisma.SortOrder;
  secret?: Prisma.SortOrder;
  activated?: Prisma.SortOrder;
};

export type TotpDeviceNullableCreateEnvelopeInput = {
  set?: Prisma.TotpDeviceCreateInput | null;
};

export type TotpDeviceNullableUpdateEnvelopeInput = {
  set?: Prisma.TotpDeviceCreateInput | null;
  upsert?: Prisma.TotpDeviceUpsertInput;
  unset?: boolean;
};

export type TotpDeviceWhereInput = {
  AND?: Prisma.TotpDeviceWhereInput | Prisma.TotpDeviceWhereInput[];
  OR?: Prisma.TotpDeviceWhereInput[];
  NOT?: Prisma.TotpDeviceWhereInput | Prisma.TotpDeviceWhereInput[];
  ip?: Prisma.StringNullableFilter<'TotpDevice'> | string | null;
  dateRegistered?: Prisma.DateTimeNullableFilter<'TotpDevice'> | Date | string | null;
  secret?: Prisma.StringNullableFilter<'TotpDevice'> | string | null;
  activated?: Prisma.DateTimeNullableFilter<'TotpDevice'> | Date | string | null;
};

export type TotpDeviceUpsertInput = {
  set: Prisma.TotpDeviceCreateInput | null;
  update: Prisma.TotpDeviceUpdateInput;
};

export type TotpDeviceUpdateInput = {
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateRegistered?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  secret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  activated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type TotpDeviceSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    ip?: boolean;
    dateRegistered?: boolean;
    secret?: boolean;
    activated?: boolean;
  },
  ExtArgs['result']['totpDevice']
>;

export type TotpDeviceSelectScalar = {
  ip?: boolean;
  dateRegistered?: boolean;
  secret?: boolean;
  activated?: boolean;
};

export type TotpDeviceOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'ip' | 'dateRegistered' | 'secret' | 'activated',
  ExtArgs['result']['totpDevice']
>;

export type $TotpDevicePayload = {
  name: 'TotpDevice';
  objects: {};
  scalars: {
    ip: string | null;
    dateRegistered: Date | null;
    secret: string | null;
    activated: Date | null;
  };
  composites: {};
};

export type TotpDeviceGetPayload<S extends boolean | null | undefined | TotpDeviceDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$TotpDevicePayload, S>;

/**
 * Fields of the TotpDevice model
 */
export interface TotpDeviceFieldRefs {
  readonly ip: Prisma.FieldRef<'TotpDevice', 'String'>;
  readonly dateRegistered: Prisma.FieldRef<'TotpDevice', 'DateTime'>;
  readonly secret: Prisma.FieldRef<'TotpDevice', 'String'>;
  readonly activated: Prisma.FieldRef<'TotpDevice', 'DateTime'>;
}

// Custom InputTypes
/**
 * TotpDevice without action
 */
export type TotpDeviceDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TotpDevice
   */
  select?: Prisma.TotpDeviceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TotpDevice
   */
  omit?: Prisma.TotpDeviceOmit<ExtArgs> | null;
};
