/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TreatmentAttachment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TreatmentAttachment
 *
 */
export type TreatmentAttachmentModel =
  runtime.Types.Result.DefaultSelection<Prisma.$TreatmentAttachmentPayload>;

export type TreatmentAttachmentCompositeListFilter = {
  equals?: Prisma.TreatmentAttachmentObjectEqualityInput[];
  every?: Prisma.TreatmentAttachmentWhereInput;
  some?: Prisma.TreatmentAttachmentWhereInput;
  none?: Prisma.TreatmentAttachmentWhereInput;
  isEmpty?: boolean;
  isSet?: boolean;
};

export type TreatmentAttachmentOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type TreatmentAttachmentListCreateEnvelopeInput = {
  set?: Prisma.TreatmentAttachmentCreateInput | Prisma.TreatmentAttachmentCreateInput[];
};

export type TreatmentAttachmentListUpdateEnvelopeInput = {
  set?: Prisma.TreatmentAttachmentCreateInput | Prisma.TreatmentAttachmentCreateInput[];
  push?: Prisma.TreatmentAttachmentCreateInput | Prisma.TreatmentAttachmentCreateInput[];
  updateMany?: Prisma.TreatmentAttachmentUpdateManyInput;
  deleteMany?: Prisma.TreatmentAttachmentDeleteManyInput;
};

export type TreatmentAttachmentWhereInput = {
  AND?: Prisma.TreatmentAttachmentWhereInput | Prisma.TreatmentAttachmentWhereInput[];
  OR?: Prisma.TreatmentAttachmentWhereInput[];
  NOT?: Prisma.TreatmentAttachmentWhereInput | Prisma.TreatmentAttachmentWhereInput[];
  file?: Prisma.XOR<
    Prisma.TreatmentFileNullableCompositeFilter,
    Prisma.TreatmentFileObjectEqualityInput
  > | null;
  attach?: Prisma.BoolNullableFilter<'TreatmentAttachment'> | boolean | null;
};

export type TreatmentFileObjectEqualityInput = {
  id?: string | null;
  name?: string | null;
  mime?: string | null;
  type?: string | null;
  checksum?: string | null;
  version?: bigint | number | null;
  deep?: string | null;
  dateCreated?: Date | string | null;
  createdBy?: bigint | number | null;
};

export type TreatmentFileCreateInput = {
  id?: string | null;
  name?: string | null;
  mime?: string | null;
  type?: string | null;
  checksum?: string | null;
  version?: bigint | number | null;
  deep?: string | null;
  dateCreated?: Date | string | null;
  createdBy?: bigint | number | null;
};

export type TreatmentAttachmentUpdateManyInput = {
  where: Prisma.TreatmentAttachmentWhereInput;
  data: Prisma.TreatmentAttachmentUpdateInput;
};

export type TreatmentAttachmentDeleteManyInput = {
  where: Prisma.TreatmentAttachmentWhereInput;
};

export type TreatmentAttachmentUpdateInput = {
  file?: Prisma.XOR<
    Prisma.TreatmentFileNullableUpdateEnvelopeInput,
    Prisma.TreatmentFileCreateInput
  > | null;
  attach?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
};

export type TreatmentAttachmentSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    file?: boolean | Prisma.TreatmentFileDefaultArgs<ExtArgs>;
    attach?: boolean;
  },
  ExtArgs['result']['treatmentAttachment']
>;

export type TreatmentAttachmentSelectScalar = {
  attach?: boolean;
};

export type TreatmentAttachmentOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<'file' | 'attach', ExtArgs['result']['treatmentAttachment']>;
export type TreatmentAttachmentInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $TreatmentAttachmentPayload = {
  name: 'TreatmentAttachment';
  objects: {};
  scalars: {
    attach: boolean | null;
  };
  composites: {
    file: Prisma.$TreatmentFilePayload | null;
  };
};

export type TreatmentAttachmentGetPayload<
  S extends boolean | null | undefined | TreatmentAttachmentDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$TreatmentAttachmentPayload, S>;

/**
 * Fields of the TreatmentAttachment model
 */
export interface TreatmentAttachmentFieldRefs {
  readonly attach: Prisma.FieldRef<'TreatmentAttachment', 'Boolean'>;
}

// Custom InputTypes
/**
 * TreatmentAttachment without action
 */
export type TreatmentAttachmentDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TreatmentAttachment
   */
  select?: Prisma.TreatmentAttachmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TreatmentAttachment
   */
  omit?: Prisma.TreatmentAttachmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TreatmentAttachmentInclude<ExtArgs> | null;
};
