/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TreatmentFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TreatmentFile
 *
 */
export type TreatmentFileModel =
  runtime.Types.Result.DefaultSelection<Prisma.$TreatmentFilePayload>;

export type TreatmentFileNullableCompositeFilter = {
  equals?: Prisma.TreatmentFileObjectEqualityInput | null;
  is?: Prisma.TreatmentFileWhereInput | null;
  isNot?: Prisma.TreatmentFileWhereInput | null;
  isSet?: boolean;
};

export type TreatmentFileWhereInput = {
  AND?: Prisma.TreatmentFileWhereInput | Prisma.TreatmentFileWhereInput[];
  OR?: Prisma.TreatmentFileWhereInput[];
  NOT?: Prisma.TreatmentFileWhereInput | Prisma.TreatmentFileWhereInput[];
  id?: Prisma.StringNullableFilter<'TreatmentFile'> | string | null;
  name?: Prisma.StringNullableFilter<'TreatmentFile'> | string | null;
  mime?: Prisma.StringNullableFilter<'TreatmentFile'> | string | null;
  type?: Prisma.StringNullableFilter<'TreatmentFile'> | string | null;
  checksum?: Prisma.StringNullableFilter<'TreatmentFile'> | string | null;
  version?: Prisma.BigIntNullableFilter<'TreatmentFile'> | bigint | number | null;
  deep?: Prisma.StringNullableFilter<'TreatmentFile'> | string | null;
  dateCreated?: Prisma.DateTimeNullableFilter<'TreatmentFile'> | Date | string | null;
  createdBy?: Prisma.BigIntNullableFilter<'TreatmentFile'> | bigint | number | null;
};

export type TreatmentFileNullableUpdateEnvelopeInput = {
  set?: Prisma.TreatmentFileCreateInput | null;
  upsert?: Prisma.TreatmentFileUpsertInput;
  unset?: boolean;
};

export type TreatmentFileUpsertInput = {
  set: Prisma.TreatmentFileCreateInput | null;
  update: Prisma.TreatmentFileUpdateInput;
};

export type TreatmentFileUpdateInput = {
  id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  mime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  deep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  createdBy?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
};

export type TreatmentFileSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    mime?: boolean;
    type?: boolean;
    checksum?: boolean;
    version?: boolean;
    deep?: boolean;
    dateCreated?: boolean;
    createdBy?: boolean;
  },
  ExtArgs['result']['treatmentFile']
>;

export type TreatmentFileSelectScalar = {
  id?: boolean;
  name?: boolean;
  mime?: boolean;
  type?: boolean;
  checksum?: boolean;
  version?: boolean;
  deep?: boolean;
  dateCreated?: boolean;
  createdBy?: boolean;
};

export type TreatmentFileOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'name' | 'mime' | 'type' | 'checksum' | 'version' | 'deep' | 'dateCreated' | 'createdBy',
  ExtArgs['result']['treatmentFile']
>;

export type $TreatmentFilePayload = {
  name: 'TreatmentFile';
  objects: {};
  scalars: {
    id: string | null;
    name: string | null;
    mime: string | null;
    type: string | null;
    checksum: string | null;
    version: bigint | null;
    deep: string | null;
    dateCreated: Date | null;
    createdBy: bigint | null;
  };
  composites: {};
};

export type TreatmentFileGetPayload<
  S extends boolean | null | undefined | TreatmentFileDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$TreatmentFilePayload, S>;

/**
 * Fields of the TreatmentFile model
 */
export interface TreatmentFileFieldRefs {
  readonly id: Prisma.FieldRef<'TreatmentFile', 'String'>;
  readonly name: Prisma.FieldRef<'TreatmentFile', 'String'>;
  readonly mime: Prisma.FieldRef<'TreatmentFile', 'String'>;
  readonly type: Prisma.FieldRef<'TreatmentFile', 'String'>;
  readonly checksum: Prisma.FieldRef<'TreatmentFile', 'String'>;
  readonly version: Prisma.FieldRef<'TreatmentFile', 'BigInt'>;
  readonly deep: Prisma.FieldRef<'TreatmentFile', 'String'>;
  readonly dateCreated: Prisma.FieldRef<'TreatmentFile', 'DateTime'>;
  readonly createdBy: Prisma.FieldRef<'TreatmentFile', 'BigInt'>;
}

// Custom InputTypes
/**
 * TreatmentFile without action
 */
export type TreatmentFileDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TreatmentFile
   */
  select?: Prisma.TreatmentFileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TreatmentFile
   */
  omit?: Prisma.TreatmentFileOmit<ExtArgs> | null;
};
