/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TreatmentUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TreatmentUser
 *
 */
export type TreatmentUserModel =
  runtime.Types.Result.DefaultSelection<Prisma.$TreatmentUserPayload>;

export type TreatmentUserNullableCompositeFilter = {
  equals?: Prisma.TreatmentUserObjectEqualityInput | null;
  is?: Prisma.TreatmentUserWhereInput | null;
  isNot?: Prisma.TreatmentUserWhereInput | null;
  isSet?: boolean;
};

export type TreatmentUserOrderByInput = {
  id?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  formalDisplayName?: Prisma.SortOrder;
};

export type TreatmentUserNullableCreateEnvelopeInput = {
  set?: Prisma.TreatmentUserCreateInput | null;
};

export type TreatmentUserNullableUpdateEnvelopeInput = {
  set?: Prisma.TreatmentUserCreateInput | null;
  upsert?: Prisma.TreatmentUserUpsertInput;
  unset?: boolean;
};

export type TreatmentUserWhereInput = {
  AND?: Prisma.TreatmentUserWhereInput | Prisma.TreatmentUserWhereInput[];
  OR?: Prisma.TreatmentUserWhereInput[];
  NOT?: Prisma.TreatmentUserWhereInput | Prisma.TreatmentUserWhereInput[];
  id?: Prisma.BigIntNullableFilter<'TreatmentUser'> | bigint | number | null;
  email?: Prisma.StringNullableFilter<'TreatmentUser'> | string | null;
  name?: Prisma.StringNullableFilter<'TreatmentUser'> | string | null;
  formalDisplayName?: Prisma.StringNullableFilter<'TreatmentUser'> | string | null;
};

export type TreatmentUserUpsertInput = {
  set: Prisma.TreatmentUserCreateInput | null;
  update: Prisma.TreatmentUserUpdateInput;
};

export type TreatmentUserUpdateInput = {
  id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  formalDisplayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type TreatmentUserSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    email?: boolean;
    name?: boolean;
    formalDisplayName?: boolean;
  },
  ExtArgs['result']['treatmentUser']
>;

export type TreatmentUserSelectScalar = {
  id?: boolean;
  email?: boolean;
  name?: boolean;
  formalDisplayName?: boolean;
};

export type TreatmentUserOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'email' | 'name' | 'formalDisplayName',
  ExtArgs['result']['treatmentUser']
>;

export type $TreatmentUserPayload = {
  name: 'TreatmentUser';
  objects: {};
  scalars: {
    id: bigint | null;
    email: string | null;
    name: string | null;
    formalDisplayName: string | null;
  };
  composites: {};
};

export type TreatmentUserGetPayload<
  S extends boolean | null | undefined | TreatmentUserDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$TreatmentUserPayload, S>;

/**
 * Fields of the TreatmentUser model
 */
export interface TreatmentUserFieldRefs {
  readonly id: Prisma.FieldRef<'TreatmentUser', 'BigInt'>;
  readonly email: Prisma.FieldRef<'TreatmentUser', 'String'>;
  readonly name: Prisma.FieldRef<'TreatmentUser', 'String'>;
  readonly formalDisplayName: Prisma.FieldRef<'TreatmentUser', 'String'>;
}

// Custom InputTypes
/**
 * TreatmentUser without action
 */
export type TreatmentUserDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TreatmentUser
   */
  select?: Prisma.TreatmentUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TreatmentUser
   */
  omit?: Prisma.TreatmentUserOmit<ExtArgs> | null;
};
