/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TreatmentPosition` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TreatmentPosition
 *
 */
export type TreatmentPositionModel =
  runtime.Types.Result.DefaultSelection<Prisma.$TreatmentPositionPayload>;

export type TreatmentPositionCompositeListFilter = {
  equals?: Prisma.TreatmentPositionObjectEqualityInput[];
  every?: Prisma.TreatmentPositionWhereInput;
  some?: Prisma.TreatmentPositionWhereInput;
  none?: Prisma.TreatmentPositionWhereInput;
  isEmpty?: boolean;
  isSet?: boolean;
};

export type TreatmentPositionOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type TreatmentPositionListCreateEnvelopeInput = {
  set?: Prisma.TreatmentPositionCreateInput | Prisma.TreatmentPositionCreateInput[];
};

export type TreatmentPositionListUpdateEnvelopeInput = {
  set?: Prisma.TreatmentPositionCreateInput | Prisma.TreatmentPositionCreateInput[];
  push?: Prisma.TreatmentPositionCreateInput | Prisma.TreatmentPositionCreateInput[];
  updateMany?: Prisma.TreatmentPositionUpdateManyInput;
  deleteMany?: Prisma.TreatmentPositionDeleteManyInput;
};

export type TreatmentPositionWhereInput = {
  AND?: Prisma.TreatmentPositionWhereInput | Prisma.TreatmentPositionWhereInput[];
  OR?: Prisma.TreatmentPositionWhereInput[];
  NOT?: Prisma.TreatmentPositionWhereInput | Prisma.TreatmentPositionWhereInput[];
  appointmentId?: Prisma.BigIntNullableFilter<'TreatmentPosition'> | bigint | number | null;
  start?: Prisma.DateTimeNullableFilter<'TreatmentPosition'> | Date | string | null;
  until?: Prisma.DateTimeNullableFilter<'TreatmentPosition'> | Date | string | null;
  state?: Prisma.StringNullableFilter<'TreatmentPosition'> | string | null;
  requireReport?: Prisma.BoolNullableFilter<'TreatmentPosition'> | boolean | null;
  forceReport?: Prisma.BoolNullableFilter<'TreatmentPosition'> | boolean | null;
  report?: Prisma.XOR<
    Prisma.TreatmentReportNullableCompositeFilter,
    Prisma.TreatmentReportObjectEqualityInput
  > | null;
};

export type TreatmentReportObjectEqualityInput = {
  date?: Date | string | null;
  type?: string | null;
  consultationId?: bigint | number | null;
  dateEnd?: Date | string | null;
  job?: Prisma.TreatmentJobObjectEqualityInput | null;
  dateStart?: Date | string | null;
};

export type TreatmentReportCreateInput = {
  date?: Date | string | null;
  type?: string | null;
  consultationId?: bigint | number | null;
  dateEnd?: Date | string | null;
  job?: Prisma.TreatmentJobCreateInput | null;
  dateStart?: Date | string | null;
};

export type TreatmentPositionUpdateManyInput = {
  where: Prisma.TreatmentPositionWhereInput;
  data: Prisma.TreatmentPositionUpdateInput;
};

export type TreatmentPositionDeleteManyInput = {
  where: Prisma.TreatmentPositionWhereInput;
};

export type TreatmentPositionUpdateInput = {
  appointmentId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  start?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  until?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  requireReport?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  forceReport?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  report?: Prisma.XOR<
    Prisma.TreatmentReportNullableUpdateEnvelopeInput,
    Prisma.TreatmentReportCreateInput
  > | null;
};

export type TreatmentPositionSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    appointmentId?: boolean;
    start?: boolean;
    until?: boolean;
    state?: boolean;
    requireReport?: boolean;
    forceReport?: boolean;
    report?: boolean | Prisma.TreatmentReportDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['treatmentPosition']
>;

export type TreatmentPositionSelectScalar = {
  appointmentId?: boolean;
  start?: boolean;
  until?: boolean;
  state?: boolean;
  requireReport?: boolean;
  forceReport?: boolean;
};

export type TreatmentPositionOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'appointmentId' | 'start' | 'until' | 'state' | 'requireReport' | 'forceReport' | 'report',
  ExtArgs['result']['treatmentPosition']
>;
export type TreatmentPositionInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $TreatmentPositionPayload = {
  name: 'TreatmentPosition';
  objects: {};
  scalars: {
    appointmentId: bigint | null;
    start: Date | null;
    until: Date | null;
    state: string | null;
    requireReport: boolean | null;
    forceReport: boolean | null;
  };
  composites: {
    report: Prisma.$TreatmentReportPayload | null;
  };
};

export type TreatmentPositionGetPayload<
  S extends boolean | null | undefined | TreatmentPositionDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$TreatmentPositionPayload, S>;

/**
 * Fields of the TreatmentPosition model
 */
export interface TreatmentPositionFieldRefs {
  readonly appointmentId: Prisma.FieldRef<'TreatmentPosition', 'BigInt'>;
  readonly start: Prisma.FieldRef<'TreatmentPosition', 'DateTime'>;
  readonly until: Prisma.FieldRef<'TreatmentPosition', 'DateTime'>;
  readonly state: Prisma.FieldRef<'TreatmentPosition', 'String'>;
  readonly requireReport: Prisma.FieldRef<'TreatmentPosition', 'Boolean'>;
  readonly forceReport: Prisma.FieldRef<'TreatmentPosition', 'Boolean'>;
}

// Custom InputTypes
/**
 * TreatmentPosition without action
 */
export type TreatmentPositionDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TreatmentPosition
   */
  select?: Prisma.TreatmentPositionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TreatmentPosition
   */
  omit?: Prisma.TreatmentPositionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TreatmentPositionInclude<ExtArgs> | null;
};
