/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TreatmentJob` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TreatmentJob
 *
 */
export type TreatmentJobModel = runtime.Types.Result.DefaultSelection<Prisma.$TreatmentJobPayload>;

export type TreatmentJobNullableCompositeFilter = {
  equals?: Prisma.TreatmentJobObjectEqualityInput | null;
  is?: Prisma.TreatmentJobWhereInput | null;
  isNot?: Prisma.TreatmentJobWhereInput | null;
  isSet?: boolean;
};

export type TreatmentJobOrderByInput = {
  id?: Prisma.SortOrder;
  code?: Prisma.SortOrder;
  remoteCode?: Prisma.SortOrder;
  title?: Prisma.SortOrder;
  expertTitle?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
  color?: Prisma.SortOrder;
  consultationStandard?: Prisma.SortOrder;
  consultationOnboarding?: Prisma.SortOrder;
  consultationOnboardingShort?: Prisma.SortOrder;
  consultationDocument?: Prisma.SortOrder;
  consultationIncarceration?: Prisma.SortOrder;
  defaultConsultation?: Prisma.SortOrder;
  defaultFurtherTreatment?: Prisma.SortOrder;
};

export type TreatmentJobNullableCreateEnvelopeInput = {
  set?: Prisma.TreatmentJobCreateInput | null;
};

export type TreatmentJobNullableUpdateEnvelopeInput = {
  set?: Prisma.TreatmentJobCreateInput | null;
  upsert?: Prisma.TreatmentJobUpsertInput;
  unset?: boolean;
};

export type TreatmentJobWhereInput = {
  AND?: Prisma.TreatmentJobWhereInput | Prisma.TreatmentJobWhereInput[];
  OR?: Prisma.TreatmentJobWhereInput[];
  NOT?: Prisma.TreatmentJobWhereInput | Prisma.TreatmentJobWhereInput[];
  id?: Prisma.BigIntNullableFilter<'TreatmentJob'> | bigint | number | null;
  code?: Prisma.StringNullableFilter<'TreatmentJob'> | string | null;
  remoteCode?: Prisma.StringNullableFilter<'TreatmentJob'> | string | null;
  title?: Prisma.StringNullableFilter<'TreatmentJob'> | string | null;
  expertTitle?: Prisma.StringNullableFilter<'TreatmentJob'> | string | null;
  type?: Prisma.StringNullableFilter<'TreatmentJob'> | string | null;
  color?: Prisma.StringNullableFilter<'TreatmentJob'> | string | null;
  consultationStandard?: Prisma.BoolNullableFilter<'TreatmentJob'> | boolean | null;
  consultationOnboarding?: Prisma.BoolNullableFilter<'TreatmentJob'> | boolean | null;
  consultationOnboardingShort?: Prisma.BoolNullableFilter<'TreatmentJob'> | boolean | null;
  consultationDocument?: Prisma.BoolNullableFilter<'TreatmentJob'> | boolean | null;
  consultationIncarceration?: Prisma.BoolNullableFilter<'TreatmentJob'> | boolean | null;
  defaultConsultation?: Prisma.StringNullableFilter<'TreatmentJob'> | string | null;
  defaultFurtherTreatment?: Prisma.StringNullableFilter<'TreatmentJob'> | string | null;
};

export type TreatmentJobUpsertInput = {
  set: Prisma.TreatmentJobCreateInput | null;
  update: Prisma.TreatmentJobUpdateInput;
};

export type TreatmentJobUpdateInput = {
  id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  remoteCode?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  expertTitle?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  consultationStandard?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  consultationOnboarding?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  consultationOnboardingShort?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  consultationDocument?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  consultationIncarceration?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  defaultConsultation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  defaultFurtherTreatment?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type TreatmentJobSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    code?: boolean;
    remoteCode?: boolean;
    title?: boolean;
    expertTitle?: boolean;
    type?: boolean;
    color?: boolean;
    consultationStandard?: boolean;
    consultationOnboarding?: boolean;
    consultationOnboardingShort?: boolean;
    consultationDocument?: boolean;
    consultationIncarceration?: boolean;
    defaultConsultation?: boolean;
    defaultFurtherTreatment?: boolean;
  },
  ExtArgs['result']['treatmentJob']
>;

export type TreatmentJobSelectScalar = {
  id?: boolean;
  code?: boolean;
  remoteCode?: boolean;
  title?: boolean;
  expertTitle?: boolean;
  type?: boolean;
  color?: boolean;
  consultationStandard?: boolean;
  consultationOnboarding?: boolean;
  consultationOnboardingShort?: boolean;
  consultationDocument?: boolean;
  consultationIncarceration?: boolean;
  defaultConsultation?: boolean;
  defaultFurtherTreatment?: boolean;
};

export type TreatmentJobOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'code'
  | 'remoteCode'
  | 'title'
  | 'expertTitle'
  | 'type'
  | 'color'
  | 'consultationStandard'
  | 'consultationOnboarding'
  | 'consultationOnboardingShort'
  | 'consultationDocument'
  | 'consultationIncarceration'
  | 'defaultConsultation'
  | 'defaultFurtherTreatment',
  ExtArgs['result']['treatmentJob']
>;

export type $TreatmentJobPayload = {
  name: 'TreatmentJob';
  objects: {};
  scalars: {
    id: bigint | null;
    code: string | null;
    remoteCode: string | null;
    title: string | null;
    expertTitle: string | null;
    type: string | null;
    color: string | null;
    consultationStandard: boolean | null;
    consultationOnboarding: boolean | null;
    consultationOnboardingShort: boolean | null;
    consultationDocument: boolean | null;
    consultationIncarceration: boolean | null;
    defaultConsultation: string | null;
    defaultFurtherTreatment: string | null;
  };
  composites: {};
};

export type TreatmentJobGetPayload<S extends boolean | null | undefined | TreatmentJobDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$TreatmentJobPayload, S>;

/**
 * Fields of the TreatmentJob model
 */
export interface TreatmentJobFieldRefs {
  readonly id: Prisma.FieldRef<'TreatmentJob', 'BigInt'>;
  readonly code: Prisma.FieldRef<'TreatmentJob', 'String'>;
  readonly remoteCode: Prisma.FieldRef<'TreatmentJob', 'String'>;
  readonly title: Prisma.FieldRef<'TreatmentJob', 'String'>;
  readonly expertTitle: Prisma.FieldRef<'TreatmentJob', 'String'>;
  readonly type: Prisma.FieldRef<'TreatmentJob', 'String'>;
  readonly color: Prisma.FieldRef<'TreatmentJob', 'String'>;
  readonly consultationStandard: Prisma.FieldRef<'TreatmentJob', 'Boolean'>;
  readonly consultationOnboarding: Prisma.FieldRef<'TreatmentJob', 'Boolean'>;
  readonly consultationOnboardingShort: Prisma.FieldRef<'TreatmentJob', 'Boolean'>;
  readonly consultationDocument: Prisma.FieldRef<'TreatmentJob', 'Boolean'>;
  readonly consultationIncarceration: Prisma.FieldRef<'TreatmentJob', 'Boolean'>;
  readonly defaultConsultation: Prisma.FieldRef<'TreatmentJob', 'String'>;
  readonly defaultFurtherTreatment: Prisma.FieldRef<'TreatmentJob', 'String'>;
}

// Custom InputTypes
/**
 * TreatmentJob without action
 */
export type TreatmentJobDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TreatmentJob
   */
  select?: Prisma.TreatmentJobSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TreatmentJob
   */
  omit?: Prisma.TreatmentJobOmit<ExtArgs> | null;
};
