/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TreatmentLocation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TreatmentLocation
 *
 */
export type TreatmentLocationModel =
  runtime.Types.Result.DefaultSelection<Prisma.$TreatmentLocationPayload>;

export type TreatmentLocationNullableCompositeFilter = {
  equals?: Prisma.TreatmentLocationObjectEqualityInput | null;
  is?: Prisma.TreatmentLocationWhereInput | null;
  isNot?: Prisma.TreatmentLocationWhereInput | null;
  isSet?: boolean;
};

export type TreatmentLocationOrderByInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  patientDataType?: Prisma.SortOrder;
  booknumberMask?: Prisma.SortOrder;
  customer?: Prisma.TreatmentCustomerOrderByInput;
};

export type TreatmentLocationNullableCreateEnvelopeInput = {
  set?: Prisma.TreatmentLocationCreateInput | null;
};

export type TreatmentLocationNullableUpdateEnvelopeInput = {
  set?: Prisma.TreatmentLocationCreateInput | null;
  upsert?: Prisma.TreatmentLocationUpsertInput;
  unset?: boolean;
};

export type TreatmentLocationWhereInput = {
  AND?: Prisma.TreatmentLocationWhereInput | Prisma.TreatmentLocationWhereInput[];
  OR?: Prisma.TreatmentLocationWhereInput[];
  NOT?: Prisma.TreatmentLocationWhereInput | Prisma.TreatmentLocationWhereInput[];
  id?: Prisma.BigIntNullableFilter<'TreatmentLocation'> | bigint | number | null;
  name?: Prisma.StringNullableFilter<'TreatmentLocation'> | string | null;
  patientDataType?: Prisma.StringNullableFilter<'TreatmentLocation'> | string | null;
  booknumberMask?: Prisma.StringNullableFilter<'TreatmentLocation'> | string | null;
  customer?: Prisma.XOR<
    Prisma.TreatmentCustomerNullableCompositeFilter,
    Prisma.TreatmentCustomerObjectEqualityInput
  > | null;
};

export type TreatmentLocationUpsertInput = {
  set: Prisma.TreatmentLocationCreateInput | null;
  update: Prisma.TreatmentLocationUpdateInput;
};

export type TreatmentLocationUpdateInput = {
  id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  patientDataType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  booknumberMask?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  customer?: Prisma.XOR<
    Prisma.TreatmentCustomerNullableUpdateEnvelopeInput,
    Prisma.TreatmentCustomerCreateInput
  > | null;
};

export type TreatmentLocationSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    patientDataType?: boolean;
    booknumberMask?: boolean;
    customer?: boolean | Prisma.TreatmentCustomerDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['treatmentLocation']
>;

export type TreatmentLocationSelectScalar = {
  id?: boolean;
  name?: boolean;
  patientDataType?: boolean;
  booknumberMask?: boolean;
};

export type TreatmentLocationOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'name' | 'patientDataType' | 'booknumberMask' | 'customer',
  ExtArgs['result']['treatmentLocation']
>;
export type TreatmentLocationInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $TreatmentLocationPayload = {
  name: 'TreatmentLocation';
  objects: {};
  scalars: {
    id: bigint | null;
    name: string | null;
    patientDataType: string | null;
    booknumberMask: string | null;
  };
  composites: {
    customer: Prisma.$TreatmentCustomerPayload | null;
  };
};

export type TreatmentLocationGetPayload<
  S extends boolean | null | undefined | TreatmentLocationDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$TreatmentLocationPayload, S>;

/**
 * Fields of the TreatmentLocation model
 */
export interface TreatmentLocationFieldRefs {
  readonly id: Prisma.FieldRef<'TreatmentLocation', 'BigInt'>;
  readonly name: Prisma.FieldRef<'TreatmentLocation', 'String'>;
  readonly patientDataType: Prisma.FieldRef<'TreatmentLocation', 'String'>;
  readonly booknumberMask: Prisma.FieldRef<'TreatmentLocation', 'String'>;
}

// Custom InputTypes
/**
 * TreatmentLocation without action
 */
export type TreatmentLocationDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TreatmentLocation
   */
  select?: Prisma.TreatmentLocationSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TreatmentLocation
   */
  omit?: Prisma.TreatmentLocationOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TreatmentLocationInclude<ExtArgs> | null;
};
