/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `TreatmentReport` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model TreatmentReport
 *
 */
export type TreatmentReportModel =
  runtime.Types.Result.DefaultSelection<Prisma.$TreatmentReportPayload>;

export type TreatmentReportNullableCompositeFilter = {
  equals?: Prisma.TreatmentReportObjectEqualityInput | null;
  is?: Prisma.TreatmentReportWhereInput | null;
  isNot?: Prisma.TreatmentReportWhereInput | null;
  isSet?: boolean;
};

export type TreatmentReportWhereInput = {
  AND?: Prisma.TreatmentReportWhereInput | Prisma.TreatmentReportWhereInput[];
  OR?: Prisma.TreatmentReportWhereInput[];
  NOT?: Prisma.TreatmentReportWhereInput | Prisma.TreatmentReportWhereInput[];
  date?: Prisma.DateTimeNullableFilter<'TreatmentReport'> | Date | string | null;
  type?: Prisma.StringNullableFilter<'TreatmentReport'> | string | null;
  consultationId?: Prisma.BigIntNullableFilter<'TreatmentReport'> | bigint | number | null;
  dateEnd?: Prisma.DateTimeNullableFilter<'TreatmentReport'> | Date | string | null;
  job?: Prisma.XOR<
    Prisma.TreatmentJobNullableCompositeFilter,
    Prisma.TreatmentJobObjectEqualityInput
  > | null;
  dateStart?: Prisma.DateTimeNullableFilter<'TreatmentReport'> | Date | string | null;
};

export type TreatmentReportNullableUpdateEnvelopeInput = {
  set?: Prisma.TreatmentReportCreateInput | null;
  upsert?: Prisma.TreatmentReportUpsertInput;
  unset?: boolean;
};

export type TreatmentReportUpsertInput = {
  set: Prisma.TreatmentReportCreateInput | null;
  update: Prisma.TreatmentReportUpdateInput;
};

export type TreatmentReportUpdateInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  consultationId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  dateEnd?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  job?: Prisma.XOR<
    Prisma.TreatmentJobNullableUpdateEnvelopeInput,
    Prisma.TreatmentJobCreateInput
  > | null;
  dateStart?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type TreatmentReportSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    date?: boolean;
    type?: boolean;
    consultationId?: boolean;
    dateEnd?: boolean;
    job?: boolean | Prisma.TreatmentJobDefaultArgs<ExtArgs>;
    dateStart?: boolean;
  },
  ExtArgs['result']['treatmentReport']
>;

export type TreatmentReportSelectScalar = {
  date?: boolean;
  type?: boolean;
  consultationId?: boolean;
  dateEnd?: boolean;
  dateStart?: boolean;
};

export type TreatmentReportOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'date' | 'type' | 'consultationId' | 'dateEnd' | 'job' | 'dateStart',
  ExtArgs['result']['treatmentReport']
>;
export type TreatmentReportInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $TreatmentReportPayload = {
  name: 'TreatmentReport';
  objects: {};
  scalars: {
    date: Date | null;
    type: string | null;
    consultationId: bigint | null;
    dateEnd: Date | null;
    dateStart: Date | null;
  };
  composites: {
    job: Prisma.$TreatmentJobPayload | null;
  };
};

export type TreatmentReportGetPayload<
  S extends boolean | null | undefined | TreatmentReportDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$TreatmentReportPayload, S>;

/**
 * Fields of the TreatmentReport model
 */
export interface TreatmentReportFieldRefs {
  readonly date: Prisma.FieldRef<'TreatmentReport', 'DateTime'>;
  readonly type: Prisma.FieldRef<'TreatmentReport', 'String'>;
  readonly consultationId: Prisma.FieldRef<'TreatmentReport', 'BigInt'>;
  readonly dateEnd: Prisma.FieldRef<'TreatmentReport', 'DateTime'>;
  readonly dateStart: Prisma.FieldRef<'TreatmentReport', 'DateTime'>;
}

// Custom InputTypes
/**
 * TreatmentReport without action
 */
export type TreatmentReportDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the TreatmentReport
   */
  select?: Prisma.TreatmentReportSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the TreatmentReport
   */
  omit?: Prisma.TreatmentReportOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TreatmentReportInclude<ExtArgs> | null;
};
