/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `UserMongo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model UserMongo
 *
 */
export type UserMongoModel = runtime.Types.Result.DefaultSelection<Prisma.$UserMongoPayload>;

export type AggregateUserMongo = {
  _count: UserMongoCountAggregateOutputType | null;
  _avg: UserMongoAvgAggregateOutputType | null;
  _sum: UserMongoSumAggregateOutputType | null;
  _min: UserMongoMinAggregateOutputType | null;
  _max: UserMongoMaxAggregateOutputType | null;
};

export type UserMongoAvgAggregateOutputType = {
  id: number | null;
  version: number | null;
  countInvalidLogin: number | null;
  countLogin: number | null;
  consecutiveFailedLoginAttempts: number | null;
  onBoardingPercentComplete: number | null;
  stepsTotal: number | null;
  stepsCompleted: number | null;
};

export type UserMongoSumAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  countInvalidLogin: number | null;
  countLogin: number | null;
  consecutiveFailedLoginAttempts: number | null;
  onBoardingPercentComplete: number | null;
  stepsTotal: number | null;
  stepsCompleted: number | null;
};

export type UserMongoMinAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  username: string | null;
  email: string | null;
  password: string | null;
  enabled: boolean | null;
  accountLocked: boolean | null;
  accountExpired: boolean | null;
  credentialsExpired: boolean | null;
  deleted: boolean | null;
  external: boolean | null;
  role: string | null;
  employeeState: string | null;
  nextBirthday: Date | null;
  requireTotp: boolean | null;
  countInvalidLogin: number | null;
  dateLocked: Date | null;
  lastIP: string | null;
  countLogin: number | null;
  lastLogin: Date | null;
  ip: string | null;
  consecutiveFailedLoginAttempts: number | null;
  dateAcceptedLoginNotification: Date | null;
  resetDate: Date | null;
  resetIp: string | null;
  resetKey: string | null;
  dateChanged: Date | null;
  lastReminder: Date | null;
  emailVerified: string | null;
  dateCreated: Date | null;
  onBoardingPercentComplete: number | null;
  stepsTotal: number | null;
  stepsCompleted: number | null;
  lang: string | null;
  verifikationKey: string | null;
  class: string | null;
};

export type UserMongoMaxAggregateOutputType = {
  id: bigint | null;
  version: bigint | null;
  username: string | null;
  email: string | null;
  password: string | null;
  enabled: boolean | null;
  accountLocked: boolean | null;
  accountExpired: boolean | null;
  credentialsExpired: boolean | null;
  deleted: boolean | null;
  external: boolean | null;
  role: string | null;
  employeeState: string | null;
  nextBirthday: Date | null;
  requireTotp: boolean | null;
  countInvalidLogin: number | null;
  dateLocked: Date | null;
  lastIP: string | null;
  countLogin: number | null;
  lastLogin: Date | null;
  ip: string | null;
  consecutiveFailedLoginAttempts: number | null;
  dateAcceptedLoginNotification: Date | null;
  resetDate: Date | null;
  resetIp: string | null;
  resetKey: string | null;
  dateChanged: Date | null;
  lastReminder: Date | null;
  emailVerified: string | null;
  dateCreated: Date | null;
  onBoardingPercentComplete: number | null;
  stepsTotal: number | null;
  stepsCompleted: number | null;
  lang: string | null;
  verifikationKey: string | null;
  class: string | null;
};

export type UserMongoCountAggregateOutputType = {
  id: number;
  version: number;
  username: number;
  email: number;
  password: number;
  enabled: number;
  accountLocked: number;
  accountExpired: number;
  credentialsExpired: number;
  deleted: number;
  external: number;
  role: number;
  employeeState: number;
  nextBirthday: number;
  requireTotp: number;
  countInvalidLogin: number;
  dateLocked: number;
  lastIP: number;
  countLogin: number;
  lastLogin: number;
  settings: number;
  ip: number;
  consecutiveFailedLoginAttempts: number;
  dateAcceptedLoginNotification: number;
  resetDate: number;
  resetIp: number;
  resetKey: number;
  dateChanged: number;
  lastReminder: number;
  emailVerified: number;
  dateCreated: number;
  onBoardingPercentComplete: number;
  stepsTotal: number;
  stepsCompleted: number;
  lang: number;
  verifikationKey: number;
  class: number;
  _all: number;
};

export type UserMongoAvgAggregateInputType = {
  id?: true;
  version?: true;
  countInvalidLogin?: true;
  countLogin?: true;
  consecutiveFailedLoginAttempts?: true;
  onBoardingPercentComplete?: true;
  stepsTotal?: true;
  stepsCompleted?: true;
};

export type UserMongoSumAggregateInputType = {
  id?: true;
  version?: true;
  countInvalidLogin?: true;
  countLogin?: true;
  consecutiveFailedLoginAttempts?: true;
  onBoardingPercentComplete?: true;
  stepsTotal?: true;
  stepsCompleted?: true;
};

export type UserMongoMinAggregateInputType = {
  id?: true;
  version?: true;
  username?: true;
  email?: true;
  password?: true;
  enabled?: true;
  accountLocked?: true;
  accountExpired?: true;
  credentialsExpired?: true;
  deleted?: true;
  external?: true;
  role?: true;
  employeeState?: true;
  nextBirthday?: true;
  requireTotp?: true;
  countInvalidLogin?: true;
  dateLocked?: true;
  lastIP?: true;
  countLogin?: true;
  lastLogin?: true;
  ip?: true;
  consecutiveFailedLoginAttempts?: true;
  dateAcceptedLoginNotification?: true;
  resetDate?: true;
  resetIp?: true;
  resetKey?: true;
  dateChanged?: true;
  lastReminder?: true;
  emailVerified?: true;
  dateCreated?: true;
  onBoardingPercentComplete?: true;
  stepsTotal?: true;
  stepsCompleted?: true;
  lang?: true;
  verifikationKey?: true;
  class?: true;
};

export type UserMongoMaxAggregateInputType = {
  id?: true;
  version?: true;
  username?: true;
  email?: true;
  password?: true;
  enabled?: true;
  accountLocked?: true;
  accountExpired?: true;
  credentialsExpired?: true;
  deleted?: true;
  external?: true;
  role?: true;
  employeeState?: true;
  nextBirthday?: true;
  requireTotp?: true;
  countInvalidLogin?: true;
  dateLocked?: true;
  lastIP?: true;
  countLogin?: true;
  lastLogin?: true;
  ip?: true;
  consecutiveFailedLoginAttempts?: true;
  dateAcceptedLoginNotification?: true;
  resetDate?: true;
  resetIp?: true;
  resetKey?: true;
  dateChanged?: true;
  lastReminder?: true;
  emailVerified?: true;
  dateCreated?: true;
  onBoardingPercentComplete?: true;
  stepsTotal?: true;
  stepsCompleted?: true;
  lang?: true;
  verifikationKey?: true;
  class?: true;
};

export type UserMongoCountAggregateInputType = {
  id?: true;
  version?: true;
  username?: true;
  email?: true;
  password?: true;
  enabled?: true;
  accountLocked?: true;
  accountExpired?: true;
  credentialsExpired?: true;
  deleted?: true;
  external?: true;
  role?: true;
  employeeState?: true;
  nextBirthday?: true;
  requireTotp?: true;
  countInvalidLogin?: true;
  dateLocked?: true;
  lastIP?: true;
  countLogin?: true;
  lastLogin?: true;
  settings?: true;
  ip?: true;
  consecutiveFailedLoginAttempts?: true;
  dateAcceptedLoginNotification?: true;
  resetDate?: true;
  resetIp?: true;
  resetKey?: true;
  dateChanged?: true;
  lastReminder?: true;
  emailVerified?: true;
  dateCreated?: true;
  onBoardingPercentComplete?: true;
  stepsTotal?: true;
  stepsCompleted?: true;
  lang?: true;
  verifikationKey?: true;
  class?: true;
  _all?: true;
};

export type UserMongoAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UserMongo to aggregate.
   */
  where?: Prisma.UserMongoWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserMongos to fetch.
   */
  orderBy?: Prisma.UserMongoOrderByWithRelationInput | Prisma.UserMongoOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.UserMongoWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserMongos from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserMongos.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned UserMongos
   **/
  _count?: true | UserMongoCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: UserMongoAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: UserMongoSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: UserMongoMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: UserMongoMaxAggregateInputType;
};

export type GetUserMongoAggregateType<T extends UserMongoAggregateArgs> = {
  [P in keyof T & keyof AggregateUserMongo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserMongo[P]>
    : Prisma.GetScalarType<T[P], AggregateUserMongo[P]>;
};

export type UserMongoGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.UserMongoWhereInput;
  orderBy?:
    | Prisma.UserMongoOrderByWithAggregationInput
    | Prisma.UserMongoOrderByWithAggregationInput[];
  by: Prisma.UserMongoScalarFieldEnum[] | Prisma.UserMongoScalarFieldEnum;
  having?: Prisma.UserMongoScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: UserMongoCountAggregateInputType | true;
  _avg?: UserMongoAvgAggregateInputType;
  _sum?: UserMongoSumAggregateInputType;
  _min?: UserMongoMinAggregateInputType;
  _max?: UserMongoMaxAggregateInputType;
};

export type UserMongoGroupByOutputType = {
  id: bigint;
  version: bigint | null;
  username: string | null;
  email: string | null;
  password: string | null;
  enabled: boolean | null;
  accountLocked: boolean | null;
  accountExpired: boolean | null;
  credentialsExpired: boolean | null;
  deleted: boolean | null;
  external: boolean | null;
  role: string | null;
  employeeState: string | null;
  nextBirthday: Date | null;
  requireTotp: boolean | null;
  countInvalidLogin: number | null;
  dateLocked: Date | null;
  lastIP: string | null;
  countLogin: number | null;
  lastLogin: Date | null;
  settings: runtime.JsonValue | null;
  ip: string | null;
  consecutiveFailedLoginAttempts: number | null;
  dateAcceptedLoginNotification: Date | null;
  resetDate: Date | null;
  resetIp: string | null;
  resetKey: string | null;
  dateChanged: Date | null;
  lastReminder: Date | null;
  emailVerified: string | null;
  dateCreated: Date | null;
  onBoardingPercentComplete: number | null;
  stepsTotal: number | null;
  stepsCompleted: number | null;
  lang: string | null;
  verifikationKey: string | null;
  class: string | null;
  _count: UserMongoCountAggregateOutputType | null;
  _avg: UserMongoAvgAggregateOutputType | null;
  _sum: UserMongoSumAggregateOutputType | null;
  _min: UserMongoMinAggregateOutputType | null;
  _max: UserMongoMaxAggregateOutputType | null;
};

type GetUserMongoGroupByPayload<T extends UserMongoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserMongoGroupByOutputType, T['by']> & {
      [P in keyof T & keyof UserMongoGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], UserMongoGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], UserMongoGroupByOutputType[P]>;
    }
  >
>;

export type UserMongoWhereInput = {
  AND?: Prisma.UserMongoWhereInput | Prisma.UserMongoWhereInput[];
  OR?: Prisma.UserMongoWhereInput[];
  NOT?: Prisma.UserMongoWhereInput | Prisma.UserMongoWhereInput[];
  id?: Prisma.BigIntFilter<'UserMongo'> | bigint | number;
  version?: Prisma.BigIntNullableFilter<'UserMongo'> | bigint | number | null;
  username?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  email?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  password?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  enabled?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
  accountLocked?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
  accountExpired?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
  credentialsExpired?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
  deleted?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
  external?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
  role?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  employeeState?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  userProfile?: Prisma.XOR<
    Prisma.UserProfileNullableCompositeFilter,
    Prisma.UserProfileObjectEqualityInput
  > | null;
  employeeProfile?: Prisma.XOR<
    Prisma.EmployeeProfileNullableCompositeFilter,
    Prisma.EmployeeProfileObjectEqualityInput
  > | null;
  employerProfile?: Prisma.XOR<
    Prisma.EmployerProfileNullableCompositeFilter,
    Prisma.EmployerProfileObjectEqualityInput
  > | null;
  nextBirthday?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
  totpDevice?: Prisma.XOR<
    Prisma.TotpDeviceNullableCompositeFilter,
    Prisma.TotpDeviceObjectEqualityInput
  > | null;
  requireTotp?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
  totpActivity?: Prisma.XOR<
    Prisma.TotpActivityNullableCompositeFilter,
    Prisma.TotpActivityObjectEqualityInput
  > | null;
  countInvalidLogin?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
  dateLocked?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
  lastIP?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  countLogin?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
  lastLogin?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
  settings?: Prisma.JsonNullableFilter<'UserMongo'>;
  ip?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  invalidLogins?: Prisma.LoginEventCompositeListFilter | Prisma.LoginEventObjectEqualityInput[];
  consecutiveFailedLoginAttempts?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
  successfulLogins?: Prisma.LoginEventCompositeListFilter | Prisma.LoginEventObjectEqualityInput[];
  dateAcceptedLoginNotification?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
  resetDate?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
  resetIp?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  resetKey?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  dateChanged?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
  changedBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableCompositeFilter,
    Prisma.UserPlanUserObjectEqualityInput
  > | null;
  lastReminder?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
  emailVerified?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  dateCreated?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
  createdBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableCompositeFilter,
    Prisma.UserPlanUserObjectEqualityInput
  > | null;
  onBoardingPercentComplete?: Prisma.FloatNullableFilter<'UserMongo'> | number | null;
  stepsTotal?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
  stepsCompleted?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
  lang?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  verifikationKey?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  class?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
};

export type UserMongoOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  username?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  password?: Prisma.SortOrder;
  enabled?: Prisma.SortOrder;
  accountLocked?: Prisma.SortOrder;
  accountExpired?: Prisma.SortOrder;
  credentialsExpired?: Prisma.SortOrder;
  deleted?: Prisma.SortOrder;
  external?: Prisma.SortOrder;
  role?: Prisma.SortOrder;
  employeeState?: Prisma.SortOrder;
  userProfile?: Prisma.UserProfileOrderByInput;
  employeeProfile?: Prisma.EmployeeProfileOrderByInput;
  employerProfile?: Prisma.EmployerProfileOrderByInput;
  nextBirthday?: Prisma.SortOrder;
  totpDevice?: Prisma.TotpDeviceOrderByInput;
  requireTotp?: Prisma.SortOrder;
  totpActivity?: Prisma.TotpActivityOrderByInput;
  countInvalidLogin?: Prisma.SortOrder;
  dateLocked?: Prisma.SortOrder;
  lastIP?: Prisma.SortOrder;
  countLogin?: Prisma.SortOrder;
  lastLogin?: Prisma.SortOrder;
  settings?: Prisma.SortOrder;
  ip?: Prisma.SortOrder;
  invalidLogins?: Prisma.LoginEventOrderByCompositeAggregateInput;
  consecutiveFailedLoginAttempts?: Prisma.SortOrder;
  successfulLogins?: Prisma.LoginEventOrderByCompositeAggregateInput;
  dateAcceptedLoginNotification?: Prisma.SortOrder;
  resetDate?: Prisma.SortOrder;
  resetIp?: Prisma.SortOrder;
  resetKey?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  changedBy?: Prisma.UserPlanUserOrderByInput;
  lastReminder?: Prisma.SortOrder;
  emailVerified?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  createdBy?: Prisma.UserPlanUserOrderByInput;
  onBoardingPercentComplete?: Prisma.SortOrder;
  stepsTotal?: Prisma.SortOrder;
  stepsCompleted?: Prisma.SortOrder;
  lang?: Prisma.SortOrder;
  verifikationKey?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type UserMongoWhereUniqueInput = Prisma.AtLeast<
  {
    id?: bigint | number;
    AND?: Prisma.UserMongoWhereInput | Prisma.UserMongoWhereInput[];
    OR?: Prisma.UserMongoWhereInput[];
    NOT?: Prisma.UserMongoWhereInput | Prisma.UserMongoWhereInput[];
    version?: Prisma.BigIntNullableFilter<'UserMongo'> | bigint | number | null;
    username?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    email?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    password?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    enabled?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
    accountLocked?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
    accountExpired?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
    credentialsExpired?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
    deleted?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
    external?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
    role?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    employeeState?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    userProfile?: Prisma.XOR<
      Prisma.UserProfileNullableCompositeFilter,
      Prisma.UserProfileObjectEqualityInput
    > | null;
    employeeProfile?: Prisma.XOR<
      Prisma.EmployeeProfileNullableCompositeFilter,
      Prisma.EmployeeProfileObjectEqualityInput
    > | null;
    employerProfile?: Prisma.XOR<
      Prisma.EmployerProfileNullableCompositeFilter,
      Prisma.EmployerProfileObjectEqualityInput
    > | null;
    nextBirthday?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
    totpDevice?: Prisma.XOR<
      Prisma.TotpDeviceNullableCompositeFilter,
      Prisma.TotpDeviceObjectEqualityInput
    > | null;
    requireTotp?: Prisma.BoolNullableFilter<'UserMongo'> | boolean | null;
    totpActivity?: Prisma.XOR<
      Prisma.TotpActivityNullableCompositeFilter,
      Prisma.TotpActivityObjectEqualityInput
    > | null;
    countInvalidLogin?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
    dateLocked?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
    lastIP?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    countLogin?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
    lastLogin?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
    settings?: Prisma.JsonNullableFilter<'UserMongo'>;
    ip?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    invalidLogins?: Prisma.LoginEventCompositeListFilter | Prisma.LoginEventObjectEqualityInput[];
    consecutiveFailedLoginAttempts?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
    successfulLogins?:
      | Prisma.LoginEventCompositeListFilter
      | Prisma.LoginEventObjectEqualityInput[];
    dateAcceptedLoginNotification?:
      | Prisma.DateTimeNullableFilter<'UserMongo'>
      | Date
      | string
      | null;
    resetDate?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
    resetIp?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    resetKey?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    dateChanged?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
    changedBy?: Prisma.XOR<
      Prisma.UserPlanUserNullableCompositeFilter,
      Prisma.UserPlanUserObjectEqualityInput
    > | null;
    lastReminder?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
    emailVerified?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    dateCreated?: Prisma.DateTimeNullableFilter<'UserMongo'> | Date | string | null;
    createdBy?: Prisma.XOR<
      Prisma.UserPlanUserNullableCompositeFilter,
      Prisma.UserPlanUserObjectEqualityInput
    > | null;
    onBoardingPercentComplete?: Prisma.FloatNullableFilter<'UserMongo'> | number | null;
    stepsTotal?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
    stepsCompleted?: Prisma.IntNullableFilter<'UserMongo'> | number | null;
    lang?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    verifikationKey?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
    class?: Prisma.StringNullableFilter<'UserMongo'> | string | null;
  },
  'id'
>;

export type UserMongoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  username?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  password?: Prisma.SortOrder;
  enabled?: Prisma.SortOrder;
  accountLocked?: Prisma.SortOrder;
  accountExpired?: Prisma.SortOrder;
  credentialsExpired?: Prisma.SortOrder;
  deleted?: Prisma.SortOrder;
  external?: Prisma.SortOrder;
  role?: Prisma.SortOrder;
  employeeState?: Prisma.SortOrder;
  nextBirthday?: Prisma.SortOrder;
  requireTotp?: Prisma.SortOrder;
  countInvalidLogin?: Prisma.SortOrder;
  dateLocked?: Prisma.SortOrder;
  lastIP?: Prisma.SortOrder;
  countLogin?: Prisma.SortOrder;
  lastLogin?: Prisma.SortOrder;
  settings?: Prisma.SortOrder;
  ip?: Prisma.SortOrder;
  consecutiveFailedLoginAttempts?: Prisma.SortOrder;
  dateAcceptedLoginNotification?: Prisma.SortOrder;
  resetDate?: Prisma.SortOrder;
  resetIp?: Prisma.SortOrder;
  resetKey?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  lastReminder?: Prisma.SortOrder;
  emailVerified?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  onBoardingPercentComplete?: Prisma.SortOrder;
  stepsTotal?: Prisma.SortOrder;
  stepsCompleted?: Prisma.SortOrder;
  lang?: Prisma.SortOrder;
  verifikationKey?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
  _count?: Prisma.UserMongoCountOrderByAggregateInput;
  _avg?: Prisma.UserMongoAvgOrderByAggregateInput;
  _max?: Prisma.UserMongoMaxOrderByAggregateInput;
  _min?: Prisma.UserMongoMinOrderByAggregateInput;
  _sum?: Prisma.UserMongoSumOrderByAggregateInput;
};

export type UserMongoScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.UserMongoScalarWhereWithAggregatesInput
    | Prisma.UserMongoScalarWhereWithAggregatesInput[];
  OR?: Prisma.UserMongoScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.UserMongoScalarWhereWithAggregatesInput
    | Prisma.UserMongoScalarWhereWithAggregatesInput[];
  id?: Prisma.BigIntWithAggregatesFilter<'UserMongo'> | bigint | number;
  version?: Prisma.BigIntNullableWithAggregatesFilter<'UserMongo'> | bigint | number | null;
  username?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  email?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  password?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  enabled?: Prisma.BoolNullableWithAggregatesFilter<'UserMongo'> | boolean | null;
  accountLocked?: Prisma.BoolNullableWithAggregatesFilter<'UserMongo'> | boolean | null;
  accountExpired?: Prisma.BoolNullableWithAggregatesFilter<'UserMongo'> | boolean | null;
  credentialsExpired?: Prisma.BoolNullableWithAggregatesFilter<'UserMongo'> | boolean | null;
  deleted?: Prisma.BoolNullableWithAggregatesFilter<'UserMongo'> | boolean | null;
  external?: Prisma.BoolNullableWithAggregatesFilter<'UserMongo'> | boolean | null;
  role?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  employeeState?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  nextBirthday?: Prisma.DateTimeNullableWithAggregatesFilter<'UserMongo'> | Date | string | null;
  requireTotp?: Prisma.BoolNullableWithAggregatesFilter<'UserMongo'> | boolean | null;
  countInvalidLogin?: Prisma.IntNullableWithAggregatesFilter<'UserMongo'> | number | null;
  dateLocked?: Prisma.DateTimeNullableWithAggregatesFilter<'UserMongo'> | Date | string | null;
  lastIP?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  countLogin?: Prisma.IntNullableWithAggregatesFilter<'UserMongo'> | number | null;
  lastLogin?: Prisma.DateTimeNullableWithAggregatesFilter<'UserMongo'> | Date | string | null;
  settings?: Prisma.JsonNullableWithAggregatesFilter<'UserMongo'>;
  ip?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  consecutiveFailedLoginAttempts?:
    | Prisma.IntNullableWithAggregatesFilter<'UserMongo'>
    | number
    | null;
  dateAcceptedLoginNotification?:
    | Prisma.DateTimeNullableWithAggregatesFilter<'UserMongo'>
    | Date
    | string
    | null;
  resetDate?: Prisma.DateTimeNullableWithAggregatesFilter<'UserMongo'> | Date | string | null;
  resetIp?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  resetKey?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  dateChanged?: Prisma.DateTimeNullableWithAggregatesFilter<'UserMongo'> | Date | string | null;
  lastReminder?: Prisma.DateTimeNullableWithAggregatesFilter<'UserMongo'> | Date | string | null;
  emailVerified?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  dateCreated?: Prisma.DateTimeNullableWithAggregatesFilter<'UserMongo'> | Date | string | null;
  onBoardingPercentComplete?: Prisma.FloatNullableWithAggregatesFilter<'UserMongo'> | number | null;
  stepsTotal?: Prisma.IntNullableWithAggregatesFilter<'UserMongo'> | number | null;
  stepsCompleted?: Prisma.IntNullableWithAggregatesFilter<'UserMongo'> | number | null;
  lang?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  verifikationKey?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
  class?: Prisma.StringNullableWithAggregatesFilter<'UserMongo'> | string | null;
};

export type UserMongoCreateInput = {
  id: bigint | number;
  version?: bigint | number | null;
  username?: string | null;
  email?: string | null;
  password?: string | null;
  enabled?: boolean | null;
  accountLocked?: boolean | null;
  accountExpired?: boolean | null;
  credentialsExpired?: boolean | null;
  deleted?: boolean | null;
  external?: boolean | null;
  role?: string | null;
  employeeState?: string | null;
  userProfile?: Prisma.XOR<
    Prisma.UserProfileNullableCreateEnvelopeInput,
    Prisma.UserProfileCreateInput
  > | null;
  employeeProfile?: Prisma.XOR<
    Prisma.EmployeeProfileNullableCreateEnvelopeInput,
    Prisma.EmployeeProfileCreateInput
  > | null;
  employerProfile?: Prisma.XOR<
    Prisma.EmployerProfileNullableCreateEnvelopeInput,
    Prisma.EmployerProfileCreateInput
  > | null;
  nextBirthday?: Date | string | null;
  totpDevice?: Prisma.XOR<
    Prisma.TotpDeviceNullableCreateEnvelopeInput,
    Prisma.TotpDeviceCreateInput
  > | null;
  requireTotp?: boolean | null;
  totpActivity?: Prisma.XOR<
    Prisma.TotpActivityNullableCreateEnvelopeInput,
    Prisma.TotpActivityCreateInput
  > | null;
  countInvalidLogin?: number | null;
  dateLocked?: Date | string | null;
  lastIP?: string | null;
  countLogin?: number | null;
  lastLogin?: Date | string | null;
  settings?: runtime.InputJsonValue | null;
  ip?: string | null;
  invalidLogins?:
    | Prisma.XOR<Prisma.LoginEventListCreateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  consecutiveFailedLoginAttempts?: number | null;
  successfulLogins?:
    | Prisma.XOR<Prisma.LoginEventListCreateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  dateAcceptedLoginNotification?: Date | string | null;
  resetDate?: Date | string | null;
  resetIp?: string | null;
  resetKey?: string | null;
  dateChanged?: Date | string | null;
  changedBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableCreateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  lastReminder?: Date | string | null;
  emailVerified?: string | null;
  dateCreated?: Date | string | null;
  createdBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableCreateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  onBoardingPercentComplete?: number | null;
  stepsTotal?: number | null;
  stepsCompleted?: number | null;
  lang?: string | null;
  verifikationKey?: string | null;
  class?: string | null;
};

export type UserMongoUncheckedCreateInput = {
  id: bigint | number;
  version?: bigint | number | null;
  username?: string | null;
  email?: string | null;
  password?: string | null;
  enabled?: boolean | null;
  accountLocked?: boolean | null;
  accountExpired?: boolean | null;
  credentialsExpired?: boolean | null;
  deleted?: boolean | null;
  external?: boolean | null;
  role?: string | null;
  employeeState?: string | null;
  userProfile?: Prisma.XOR<
    Prisma.UserProfileNullableCreateEnvelopeInput,
    Prisma.UserProfileCreateInput
  > | null;
  employeeProfile?: Prisma.XOR<
    Prisma.EmployeeProfileNullableCreateEnvelopeInput,
    Prisma.EmployeeProfileCreateInput
  > | null;
  employerProfile?: Prisma.XOR<
    Prisma.EmployerProfileNullableCreateEnvelopeInput,
    Prisma.EmployerProfileCreateInput
  > | null;
  nextBirthday?: Date | string | null;
  totpDevice?: Prisma.XOR<
    Prisma.TotpDeviceNullableCreateEnvelopeInput,
    Prisma.TotpDeviceCreateInput
  > | null;
  requireTotp?: boolean | null;
  totpActivity?: Prisma.XOR<
    Prisma.TotpActivityNullableCreateEnvelopeInput,
    Prisma.TotpActivityCreateInput
  > | null;
  countInvalidLogin?: number | null;
  dateLocked?: Date | string | null;
  lastIP?: string | null;
  countLogin?: number | null;
  lastLogin?: Date | string | null;
  settings?: runtime.InputJsonValue | null;
  ip?: string | null;
  invalidLogins?:
    | Prisma.XOR<Prisma.LoginEventListCreateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  consecutiveFailedLoginAttempts?: number | null;
  successfulLogins?:
    | Prisma.XOR<Prisma.LoginEventListCreateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  dateAcceptedLoginNotification?: Date | string | null;
  resetDate?: Date | string | null;
  resetIp?: string | null;
  resetKey?: string | null;
  dateChanged?: Date | string | null;
  changedBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableCreateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  lastReminder?: Date | string | null;
  emailVerified?: string | null;
  dateCreated?: Date | string | null;
  createdBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableCreateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  onBoardingPercentComplete?: number | null;
  stepsTotal?: number | null;
  stepsCompleted?: number | null;
  lang?: string | null;
  verifikationKey?: string | null;
  class?: string | null;
};

export type UserMongoUpdateInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  enabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  accountLocked?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  accountExpired?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  credentialsExpired?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  deleted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  external?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  employeeState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  userProfile?: Prisma.XOR<
    Prisma.UserProfileNullableUpdateEnvelopeInput,
    Prisma.UserProfileCreateInput
  > | null;
  employeeProfile?: Prisma.XOR<
    Prisma.EmployeeProfileNullableUpdateEnvelopeInput,
    Prisma.EmployeeProfileCreateInput
  > | null;
  employerProfile?: Prisma.XOR<
    Prisma.EmployerProfileNullableUpdateEnvelopeInput,
    Prisma.EmployerProfileCreateInput
  > | null;
  nextBirthday?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  totpDevice?: Prisma.XOR<
    Prisma.TotpDeviceNullableUpdateEnvelopeInput,
    Prisma.TotpDeviceCreateInput
  > | null;
  requireTotp?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  totpActivity?: Prisma.XOR<
    Prisma.TotpActivityNullableUpdateEnvelopeInput,
    Prisma.TotpActivityCreateInput
  > | null;
  countInvalidLogin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  dateLocked?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  lastIP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  countLogin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  lastLogin?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  settings?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  invalidLogins?:
    | Prisma.XOR<Prisma.LoginEventListUpdateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  consecutiveFailedLoginAttempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  successfulLogins?:
    | Prisma.XOR<Prisma.LoginEventListUpdateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  dateAcceptedLoginNotification?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  resetDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  resetIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  resetKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateChanged?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  changedBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableUpdateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  lastReminder?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  emailVerified?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  createdBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableUpdateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  onBoardingPercentComplete?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  stepsTotal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  stepsCompleted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  verifikationKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type UserMongoUncheckedUpdateInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  enabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  accountLocked?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  accountExpired?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  credentialsExpired?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  deleted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  external?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  employeeState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  userProfile?: Prisma.XOR<
    Prisma.UserProfileNullableUpdateEnvelopeInput,
    Prisma.UserProfileCreateInput
  > | null;
  employeeProfile?: Prisma.XOR<
    Prisma.EmployeeProfileNullableUpdateEnvelopeInput,
    Prisma.EmployeeProfileCreateInput
  > | null;
  employerProfile?: Prisma.XOR<
    Prisma.EmployerProfileNullableUpdateEnvelopeInput,
    Prisma.EmployerProfileCreateInput
  > | null;
  nextBirthday?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  totpDevice?: Prisma.XOR<
    Prisma.TotpDeviceNullableUpdateEnvelopeInput,
    Prisma.TotpDeviceCreateInput
  > | null;
  requireTotp?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  totpActivity?: Prisma.XOR<
    Prisma.TotpActivityNullableUpdateEnvelopeInput,
    Prisma.TotpActivityCreateInput
  > | null;
  countInvalidLogin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  dateLocked?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  lastIP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  countLogin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  lastLogin?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  settings?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  invalidLogins?:
    | Prisma.XOR<Prisma.LoginEventListUpdateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  consecutiveFailedLoginAttempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  successfulLogins?:
    | Prisma.XOR<Prisma.LoginEventListUpdateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  dateAcceptedLoginNotification?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  resetDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  resetIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  resetKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateChanged?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  changedBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableUpdateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  lastReminder?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  emailVerified?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  createdBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableUpdateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  onBoardingPercentComplete?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  stepsTotal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  stepsCompleted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  verifikationKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type UserMongoCreateManyInput = {
  id: bigint | number;
  version?: bigint | number | null;
  username?: string | null;
  email?: string | null;
  password?: string | null;
  enabled?: boolean | null;
  accountLocked?: boolean | null;
  accountExpired?: boolean | null;
  credentialsExpired?: boolean | null;
  deleted?: boolean | null;
  external?: boolean | null;
  role?: string | null;
  employeeState?: string | null;
  userProfile?: Prisma.XOR<
    Prisma.UserProfileNullableCreateEnvelopeInput,
    Prisma.UserProfileCreateInput
  > | null;
  employeeProfile?: Prisma.XOR<
    Prisma.EmployeeProfileNullableCreateEnvelopeInput,
    Prisma.EmployeeProfileCreateInput
  > | null;
  employerProfile?: Prisma.XOR<
    Prisma.EmployerProfileNullableCreateEnvelopeInput,
    Prisma.EmployerProfileCreateInput
  > | null;
  nextBirthday?: Date | string | null;
  totpDevice?: Prisma.XOR<
    Prisma.TotpDeviceNullableCreateEnvelopeInput,
    Prisma.TotpDeviceCreateInput
  > | null;
  requireTotp?: boolean | null;
  totpActivity?: Prisma.XOR<
    Prisma.TotpActivityNullableCreateEnvelopeInput,
    Prisma.TotpActivityCreateInput
  > | null;
  countInvalidLogin?: number | null;
  dateLocked?: Date | string | null;
  lastIP?: string | null;
  countLogin?: number | null;
  lastLogin?: Date | string | null;
  settings?: runtime.InputJsonValue | null;
  ip?: string | null;
  invalidLogins?:
    | Prisma.XOR<Prisma.LoginEventListCreateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  consecutiveFailedLoginAttempts?: number | null;
  successfulLogins?:
    | Prisma.XOR<Prisma.LoginEventListCreateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  dateAcceptedLoginNotification?: Date | string | null;
  resetDate?: Date | string | null;
  resetIp?: string | null;
  resetKey?: string | null;
  dateChanged?: Date | string | null;
  changedBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableCreateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  lastReminder?: Date | string | null;
  emailVerified?: string | null;
  dateCreated?: Date | string | null;
  createdBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableCreateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  onBoardingPercentComplete?: number | null;
  stepsTotal?: number | null;
  stepsCompleted?: number | null;
  lang?: string | null;
  verifikationKey?: string | null;
  class?: string | null;
};

export type UserMongoUpdateManyMutationInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  enabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  accountLocked?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  accountExpired?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  credentialsExpired?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  deleted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  external?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  employeeState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  userProfile?: Prisma.XOR<
    Prisma.UserProfileNullableUpdateEnvelopeInput,
    Prisma.UserProfileCreateInput
  > | null;
  employeeProfile?: Prisma.XOR<
    Prisma.EmployeeProfileNullableUpdateEnvelopeInput,
    Prisma.EmployeeProfileCreateInput
  > | null;
  employerProfile?: Prisma.XOR<
    Prisma.EmployerProfileNullableUpdateEnvelopeInput,
    Prisma.EmployerProfileCreateInput
  > | null;
  nextBirthday?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  totpDevice?: Prisma.XOR<
    Prisma.TotpDeviceNullableUpdateEnvelopeInput,
    Prisma.TotpDeviceCreateInput
  > | null;
  requireTotp?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  totpActivity?: Prisma.XOR<
    Prisma.TotpActivityNullableUpdateEnvelopeInput,
    Prisma.TotpActivityCreateInput
  > | null;
  countInvalidLogin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  dateLocked?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  lastIP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  countLogin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  lastLogin?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  settings?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  invalidLogins?:
    | Prisma.XOR<Prisma.LoginEventListUpdateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  consecutiveFailedLoginAttempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  successfulLogins?:
    | Prisma.XOR<Prisma.LoginEventListUpdateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  dateAcceptedLoginNotification?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  resetDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  resetIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  resetKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateChanged?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  changedBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableUpdateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  lastReminder?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  emailVerified?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  createdBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableUpdateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  onBoardingPercentComplete?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  stepsTotal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  stepsCompleted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  verifikationKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type UserMongoUncheckedUpdateManyInput = {
  version?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  enabled?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  accountLocked?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  accountExpired?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  credentialsExpired?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  deleted?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  external?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  role?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  employeeState?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  userProfile?: Prisma.XOR<
    Prisma.UserProfileNullableUpdateEnvelopeInput,
    Prisma.UserProfileCreateInput
  > | null;
  employeeProfile?: Prisma.XOR<
    Prisma.EmployeeProfileNullableUpdateEnvelopeInput,
    Prisma.EmployeeProfileCreateInput
  > | null;
  employerProfile?: Prisma.XOR<
    Prisma.EmployerProfileNullableUpdateEnvelopeInput,
    Prisma.EmployerProfileCreateInput
  > | null;
  nextBirthday?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  totpDevice?: Prisma.XOR<
    Prisma.TotpDeviceNullableUpdateEnvelopeInput,
    Prisma.TotpDeviceCreateInput
  > | null;
  requireTotp?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null;
  totpActivity?: Prisma.XOR<
    Prisma.TotpActivityNullableUpdateEnvelopeInput,
    Prisma.TotpActivityCreateInput
  > | null;
  countInvalidLogin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  dateLocked?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  lastIP?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  countLogin?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  lastLogin?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  settings?: runtime.InputJsonValue | runtime.InputJsonValue | null;
  ip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  invalidLogins?:
    | Prisma.XOR<Prisma.LoginEventListUpdateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  consecutiveFailedLoginAttempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  successfulLogins?:
    | Prisma.XOR<Prisma.LoginEventListUpdateEnvelopeInput, Prisma.LoginEventCreateInput>
    | Prisma.LoginEventCreateInput[];
  dateAcceptedLoginNotification?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null;
  resetDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  resetIp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  resetKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateChanged?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  changedBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableUpdateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  lastReminder?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  emailVerified?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  dateCreated?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  createdBy?: Prisma.XOR<
    Prisma.UserPlanUserNullableUpdateEnvelopeInput,
    Prisma.UserPlanUserCreateInput
  > | null;
  onBoardingPercentComplete?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null;
  stepsTotal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  stepsCompleted?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  lang?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  verifikationKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  class?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type UserProfileObjectEqualityInput = {
  id?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  displayName?: string | null;
  title?: string | null;
  salutation?: string | null;
  gender?: string | null;
  birthday?: Date | string | null;
  mainAddress?: Prisma.UserAddressObjectEqualityInput | null;
  cellularNumber?: string | null;
  shiftPhoneNumber?: string | null;
  notificationPerMail?: boolean | null;
  exludedNotifications?: string[];
  photo?: Prisma.FileMetadataObjectEqualityInput | null;
  homePhone?: string | null;
  faxNumber?: string | null;
  workPhone?: string | null;
  userId?: bigint | number | null;
};

export type EmployeeProfileObjectEqualityInput = {
  id?: string | null;
  email2?: string | null;
  activeSince?: Date | string | null;
  bank?: string | null;
  iban?: string | null;
  bic?: string | null;
  taxid?: string | null;
  uid?: string | null;
  mailInvoice?: boolean | null;
  postInvoice?: boolean | null;
  shift?: string | null;
  appointment?: string | null;
  therapy?: string | null;
  skills?: Prisma.EmployeeSkillAssignmentObjectEqualityInput[];
  exclusionCriteria?: string[];
  imageSignature?: Prisma.FileMetadataObjectEqualityInput | null;
  bayernBoxAccess?: Prisma.BayernBoxAccessObjectEqualityInput | null;
  categoriesWatched?: Prisma.WatchedCategoryObjectEqualityInput[];
};

export type EmployerProfileObjectEqualityInput = {
  id?: string | null;
  konto?: string | null;
  gkto?: string | null;
  efn?: string | null;
  level?: string | null;
  activeSince?: Date | string | null;
  activeUntil?: Date | string | null;
  activeSinceVC?: Date | string | null;
  activeUntilVC?: Date | string | null;
  currentIncome?: number | null;
  inctiveReason?: string | null;
  experienceAddictionMedicine?: string | null;
};

export type TotpDeviceObjectEqualityInput = {
  ip?: string | null;
  dateRegistered?: Date | string | null;
  secret?: string | null;
  activated?: Date | string | null;
};

export type TotpActivityObjectEqualityInput = {
  dateAccess?: Date | string | null;
  ip?: string | null;
  ua?: string | null;
  action?: string | null;
};

export type LoginEventObjectEqualityInput = {
  ip?: string | null;
  date?: Date | string | null;
  first?: Date | string | null;
  ua?: string | null;
  count?: number | null;
};

export type UserPlanUserObjectEqualityInput = {
  id?: bigint | number | null;
  name?: string | null;
  email?: string | null;
  formalDisplayName?: string | null;
};

export type UserMongoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  username?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  password?: Prisma.SortOrder;
  enabled?: Prisma.SortOrder;
  accountLocked?: Prisma.SortOrder;
  accountExpired?: Prisma.SortOrder;
  credentialsExpired?: Prisma.SortOrder;
  deleted?: Prisma.SortOrder;
  external?: Prisma.SortOrder;
  role?: Prisma.SortOrder;
  employeeState?: Prisma.SortOrder;
  nextBirthday?: Prisma.SortOrder;
  requireTotp?: Prisma.SortOrder;
  countInvalidLogin?: Prisma.SortOrder;
  dateLocked?: Prisma.SortOrder;
  lastIP?: Prisma.SortOrder;
  countLogin?: Prisma.SortOrder;
  lastLogin?: Prisma.SortOrder;
  settings?: Prisma.SortOrder;
  ip?: Prisma.SortOrder;
  consecutiveFailedLoginAttempts?: Prisma.SortOrder;
  dateAcceptedLoginNotification?: Prisma.SortOrder;
  resetDate?: Prisma.SortOrder;
  resetIp?: Prisma.SortOrder;
  resetKey?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  lastReminder?: Prisma.SortOrder;
  emailVerified?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  onBoardingPercentComplete?: Prisma.SortOrder;
  stepsTotal?: Prisma.SortOrder;
  stepsCompleted?: Prisma.SortOrder;
  lang?: Prisma.SortOrder;
  verifikationKey?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type UserMongoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  countInvalidLogin?: Prisma.SortOrder;
  countLogin?: Prisma.SortOrder;
  consecutiveFailedLoginAttempts?: Prisma.SortOrder;
  onBoardingPercentComplete?: Prisma.SortOrder;
  stepsTotal?: Prisma.SortOrder;
  stepsCompleted?: Prisma.SortOrder;
};

export type UserMongoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  username?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  password?: Prisma.SortOrder;
  enabled?: Prisma.SortOrder;
  accountLocked?: Prisma.SortOrder;
  accountExpired?: Prisma.SortOrder;
  credentialsExpired?: Prisma.SortOrder;
  deleted?: Prisma.SortOrder;
  external?: Prisma.SortOrder;
  role?: Prisma.SortOrder;
  employeeState?: Prisma.SortOrder;
  nextBirthday?: Prisma.SortOrder;
  requireTotp?: Prisma.SortOrder;
  countInvalidLogin?: Prisma.SortOrder;
  dateLocked?: Prisma.SortOrder;
  lastIP?: Prisma.SortOrder;
  countLogin?: Prisma.SortOrder;
  lastLogin?: Prisma.SortOrder;
  ip?: Prisma.SortOrder;
  consecutiveFailedLoginAttempts?: Prisma.SortOrder;
  dateAcceptedLoginNotification?: Prisma.SortOrder;
  resetDate?: Prisma.SortOrder;
  resetIp?: Prisma.SortOrder;
  resetKey?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  lastReminder?: Prisma.SortOrder;
  emailVerified?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  onBoardingPercentComplete?: Prisma.SortOrder;
  stepsTotal?: Prisma.SortOrder;
  stepsCompleted?: Prisma.SortOrder;
  lang?: Prisma.SortOrder;
  verifikationKey?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type UserMongoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  username?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  password?: Prisma.SortOrder;
  enabled?: Prisma.SortOrder;
  accountLocked?: Prisma.SortOrder;
  accountExpired?: Prisma.SortOrder;
  credentialsExpired?: Prisma.SortOrder;
  deleted?: Prisma.SortOrder;
  external?: Prisma.SortOrder;
  role?: Prisma.SortOrder;
  employeeState?: Prisma.SortOrder;
  nextBirthday?: Prisma.SortOrder;
  requireTotp?: Prisma.SortOrder;
  countInvalidLogin?: Prisma.SortOrder;
  dateLocked?: Prisma.SortOrder;
  lastIP?: Prisma.SortOrder;
  countLogin?: Prisma.SortOrder;
  lastLogin?: Prisma.SortOrder;
  ip?: Prisma.SortOrder;
  consecutiveFailedLoginAttempts?: Prisma.SortOrder;
  dateAcceptedLoginNotification?: Prisma.SortOrder;
  resetDate?: Prisma.SortOrder;
  resetIp?: Prisma.SortOrder;
  resetKey?: Prisma.SortOrder;
  dateChanged?: Prisma.SortOrder;
  lastReminder?: Prisma.SortOrder;
  emailVerified?: Prisma.SortOrder;
  dateCreated?: Prisma.SortOrder;
  onBoardingPercentComplete?: Prisma.SortOrder;
  stepsTotal?: Prisma.SortOrder;
  stepsCompleted?: Prisma.SortOrder;
  lang?: Prisma.SortOrder;
  verifikationKey?: Prisma.SortOrder;
  class?: Prisma.SortOrder;
};

export type UserMongoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  version?: Prisma.SortOrder;
  countInvalidLogin?: Prisma.SortOrder;
  countLogin?: Prisma.SortOrder;
  consecutiveFailedLoginAttempts?: Prisma.SortOrder;
  onBoardingPercentComplete?: Prisma.SortOrder;
  stepsTotal?: Prisma.SortOrder;
  stepsCompleted?: Prisma.SortOrder;
};

export type UserProfileCreateInput = {
  id?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  displayName?: string | null;
  title?: string | null;
  salutation?: string | null;
  gender?: string | null;
  birthday?: Date | string | null;
  mainAddress?: Prisma.UserAddressCreateInput | null;
  cellularNumber?: string | null;
  shiftPhoneNumber?: string | null;
  notificationPerMail?: boolean | null;
  exludedNotifications?: Prisma.UserProfileCreateexludedNotificationsInput | string[];
  photo?: Prisma.FileMetadataCreateInput | null;
  homePhone?: string | null;
  faxNumber?: string | null;
  workPhone?: string | null;
  userId?: bigint | number | null;
};

export type EmployeeProfileCreateInput = {
  id?: string | null;
  email2?: string | null;
  activeSince?: Date | string | null;
  bank?: string | null;
  iban?: string | null;
  bic?: string | null;
  taxid?: string | null;
  uid?: string | null;
  mailInvoice?: boolean | null;
  postInvoice?: boolean | null;
  shift?: string | null;
  appointment?: string | null;
  therapy?: string | null;
  skills?: Prisma.EmployeeSkillAssignmentCreateInput | Prisma.EmployeeSkillAssignmentCreateInput[];
  exclusionCriteria?: Prisma.EmployeeProfileCreateexclusionCriteriaInput | string[];
  imageSignature?: Prisma.FileMetadataCreateInput | null;
  bayernBoxAccess?: Prisma.BayernBoxAccessCreateInput | null;
  categoriesWatched?: Prisma.WatchedCategoryCreateInput | Prisma.WatchedCategoryCreateInput[];
};

export type EmployerProfileCreateInput = {
  id?: string | null;
  konto?: string | null;
  gkto?: string | null;
  efn?: string | null;
  level?: string | null;
  activeSince?: Date | string | null;
  activeUntil?: Date | string | null;
  activeSinceVC?: Date | string | null;
  activeUntilVC?: Date | string | null;
  currentIncome?: number | null;
  inctiveReason?: string | null;
  experienceAddictionMedicine?: string | null;
};

export type TotpDeviceCreateInput = {
  ip?: string | null;
  dateRegistered?: Date | string | null;
  secret?: string | null;
  activated?: Date | string | null;
};

export type TotpActivityCreateInput = {
  dateAccess?: Date | string | null;
  ip?: string | null;
  ua?: string | null;
  action?: string | null;
};

export type LoginEventCreateInput = {
  ip?: string | null;
  date?: Date | string | null;
  first?: Date | string | null;
  ua?: string | null;
  count?: number | null;
};

export type UserPlanUserCreateInput = {
  id?: bigint | number | null;
  name?: string | null;
  email?: string | null;
  formalDisplayName?: string | null;
};

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null;
  unset?: boolean;
};

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null;
  increment?: number;
  decrement?: number;
  multiply?: number;
  divide?: number;
  unset?: boolean;
};

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null;
  increment?: number;
  decrement?: number;
  multiply?: number;
  divide?: number;
  unset?: boolean;
};

export type UserMongoSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    version?: boolean;
    username?: boolean;
    email?: boolean;
    password?: boolean;
    enabled?: boolean;
    accountLocked?: boolean;
    accountExpired?: boolean;
    credentialsExpired?: boolean;
    deleted?: boolean;
    external?: boolean;
    role?: boolean;
    employeeState?: boolean;
    userProfile?: boolean | Prisma.UserProfileDefaultArgs<ExtArgs>;
    employeeProfile?: boolean | Prisma.EmployeeProfileDefaultArgs<ExtArgs>;
    employerProfile?: boolean | Prisma.EmployerProfileDefaultArgs<ExtArgs>;
    nextBirthday?: boolean;
    totpDevice?: boolean | Prisma.TotpDeviceDefaultArgs<ExtArgs>;
    requireTotp?: boolean;
    totpActivity?: boolean | Prisma.TotpActivityDefaultArgs<ExtArgs>;
    countInvalidLogin?: boolean;
    dateLocked?: boolean;
    lastIP?: boolean;
    countLogin?: boolean;
    lastLogin?: boolean;
    settings?: boolean;
    ip?: boolean;
    invalidLogins?: boolean | Prisma.LoginEventDefaultArgs<ExtArgs>;
    consecutiveFailedLoginAttempts?: boolean;
    successfulLogins?: boolean | Prisma.LoginEventDefaultArgs<ExtArgs>;
    dateAcceptedLoginNotification?: boolean;
    resetDate?: boolean;
    resetIp?: boolean;
    resetKey?: boolean;
    dateChanged?: boolean;
    changedBy?: boolean | Prisma.UserPlanUserDefaultArgs<ExtArgs>;
    lastReminder?: boolean;
    emailVerified?: boolean;
    dateCreated?: boolean;
    createdBy?: boolean | Prisma.UserPlanUserDefaultArgs<ExtArgs>;
    onBoardingPercentComplete?: boolean;
    stepsTotal?: boolean;
    stepsCompleted?: boolean;
    lang?: boolean;
    verifikationKey?: boolean;
    class?: boolean;
  },
  ExtArgs['result']['userMongo']
>;

export type UserMongoSelectScalar = {
  id?: boolean;
  version?: boolean;
  username?: boolean;
  email?: boolean;
  password?: boolean;
  enabled?: boolean;
  accountLocked?: boolean;
  accountExpired?: boolean;
  credentialsExpired?: boolean;
  deleted?: boolean;
  external?: boolean;
  role?: boolean;
  employeeState?: boolean;
  nextBirthday?: boolean;
  requireTotp?: boolean;
  countInvalidLogin?: boolean;
  dateLocked?: boolean;
  lastIP?: boolean;
  countLogin?: boolean;
  lastLogin?: boolean;
  settings?: boolean;
  ip?: boolean;
  consecutiveFailedLoginAttempts?: boolean;
  dateAcceptedLoginNotification?: boolean;
  resetDate?: boolean;
  resetIp?: boolean;
  resetKey?: boolean;
  dateChanged?: boolean;
  lastReminder?: boolean;
  emailVerified?: boolean;
  dateCreated?: boolean;
  onBoardingPercentComplete?: boolean;
  stepsTotal?: boolean;
  stepsCompleted?: boolean;
  lang?: boolean;
  verifikationKey?: boolean;
  class?: boolean;
};

export type UserMongoOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'version'
  | 'username'
  | 'email'
  | 'password'
  | 'enabled'
  | 'accountLocked'
  | 'accountExpired'
  | 'credentialsExpired'
  | 'deleted'
  | 'external'
  | 'role'
  | 'employeeState'
  | 'userProfile'
  | 'employeeProfile'
  | 'employerProfile'
  | 'nextBirthday'
  | 'totpDevice'
  | 'requireTotp'
  | 'totpActivity'
  | 'countInvalidLogin'
  | 'dateLocked'
  | 'lastIP'
  | 'countLogin'
  | 'lastLogin'
  | 'settings'
  | 'ip'
  | 'invalidLogins'
  | 'consecutiveFailedLoginAttempts'
  | 'successfulLogins'
  | 'dateAcceptedLoginNotification'
  | 'resetDate'
  | 'resetIp'
  | 'resetKey'
  | 'dateChanged'
  | 'changedBy'
  | 'lastReminder'
  | 'emailVerified'
  | 'dateCreated'
  | 'createdBy'
  | 'onBoardingPercentComplete'
  | 'stepsTotal'
  | 'stepsCompleted'
  | 'lang'
  | 'verifikationKey'
  | 'class',
  ExtArgs['result']['userMongo']
>;
export type UserMongoInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $UserMongoPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'UserMongo';
  objects: {};
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: bigint;
      version: bigint | null;
      username: string | null;
      email: string | null;
      password: string | null;
      enabled: boolean | null;
      accountLocked: boolean | null;
      accountExpired: boolean | null;
      credentialsExpired: boolean | null;
      deleted: boolean | null;
      external: boolean | null;
      role: string | null;
      employeeState: string | null;
      nextBirthday: Date | null;
      requireTotp: boolean | null;
      countInvalidLogin: number | null;
      dateLocked: Date | null;
      lastIP: string | null;
      countLogin: number | null;
      lastLogin: Date | null;
      settings: runtime.JsonValue | null;
      ip: string | null;
      consecutiveFailedLoginAttempts: number | null;
      dateAcceptedLoginNotification: Date | null;
      resetDate: Date | null;
      resetIp: string | null;
      resetKey: string | null;
      dateChanged: Date | null;
      lastReminder: Date | null;
      emailVerified: string | null;
      dateCreated: Date | null;
      onBoardingPercentComplete: number | null;
      stepsTotal: number | null;
      stepsCompleted: number | null;
      lang: string | null;
      verifikationKey: string | null;
      class: string | null;
    },
    ExtArgs['result']['userMongo']
  >;
  composites: {
    userProfile: Prisma.$UserProfilePayload | null;
    employeeProfile: Prisma.$EmployeeProfilePayload | null;
    employerProfile: Prisma.$EmployerProfilePayload | null;
    totpDevice: Prisma.$TotpDevicePayload | null;
    totpActivity: Prisma.$TotpActivityPayload | null;
    invalidLogins: Prisma.$LoginEventPayload[];
    successfulLogins: Prisma.$LoginEventPayload[];
    changedBy: Prisma.$UserPlanUserPayload | null;
    createdBy: Prisma.$UserPlanUserPayload | null;
  };
};

export type UserMongoGetPayload<S extends boolean | null | undefined | UserMongoDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$UserMongoPayload, S>;

export type UserMongoCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<UserMongoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: UserMongoCountAggregateInputType | true;
};

export interface UserMongoDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['UserMongo'];
    meta: { name: 'UserMongo' };
  };
  /**
   * Find zero or one UserMongo that matches the filter.
   * @param {UserMongoFindUniqueArgs} args - Arguments to find a UserMongo
   * @example
   * // Get one UserMongo
   * const userMongo = await prisma.userMongo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserMongoFindUniqueArgs>(
    args: Prisma.SelectSubset<T, UserMongoFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__UserMongoClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one UserMongo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserMongoFindUniqueOrThrowArgs} args - Arguments to find a UserMongo
   * @example
   * // Get one UserMongo
   * const userMongo = await prisma.userMongo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserMongoFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, UserMongoFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__UserMongoClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first UserMongo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMongoFindFirstArgs} args - Arguments to find a UserMongo
   * @example
   * // Get one UserMongo
   * const userMongo = await prisma.userMongo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserMongoFindFirstArgs>(
    args?: Prisma.SelectSubset<T, UserMongoFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__UserMongoClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first UserMongo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMongoFindFirstOrThrowArgs} args - Arguments to find a UserMongo
   * @example
   * // Get one UserMongo
   * const userMongo = await prisma.userMongo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserMongoFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, UserMongoFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__UserMongoClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more UserMongos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMongoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserMongos
   * const userMongos = await prisma.userMongo.findMany()
   *
   * // Get first 10 UserMongos
   * const userMongos = await prisma.userMongo.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const userMongoWithIdOnly = await prisma.userMongo.findMany({ select: { id: true } })
   *
   */
  findMany<T extends UserMongoFindManyArgs>(
    args?: Prisma.SelectSubset<T, UserMongoFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a UserMongo.
   * @param {UserMongoCreateArgs} args - Arguments to create a UserMongo.
   * @example
   * // Create one UserMongo
   * const UserMongo = await prisma.userMongo.create({
   *   data: {
   *     // ... data to create a UserMongo
   *   }
   * })
   *
   */
  create<T extends UserMongoCreateArgs>(
    args: Prisma.SelectSubset<T, UserMongoCreateArgs<ExtArgs>>
  ): Prisma.Prisma__UserMongoClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many UserMongos.
   * @param {UserMongoCreateManyArgs} args - Arguments to create many UserMongos.
   * @example
   * // Create many UserMongos
   * const userMongo = await prisma.userMongo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends UserMongoCreateManyArgs>(
    args?: Prisma.SelectSubset<T, UserMongoCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Delete a UserMongo.
   * @param {UserMongoDeleteArgs} args - Arguments to delete one UserMongo.
   * @example
   * // Delete one UserMongo
   * const UserMongo = await prisma.userMongo.delete({
   *   where: {
   *     // ... filter to delete one UserMongo
   *   }
   * })
   *
   */
  delete<T extends UserMongoDeleteArgs>(
    args: Prisma.SelectSubset<T, UserMongoDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__UserMongoClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one UserMongo.
   * @param {UserMongoUpdateArgs} args - Arguments to update one UserMongo.
   * @example
   * // Update one UserMongo
   * const userMongo = await prisma.userMongo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends UserMongoUpdateArgs>(
    args: Prisma.SelectSubset<T, UserMongoUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__UserMongoClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more UserMongos.
   * @param {UserMongoDeleteManyArgs} args - Arguments to filter UserMongos to delete.
   * @example
   * // Delete a few UserMongos
   * const { count } = await prisma.userMongo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends UserMongoDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, UserMongoDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more UserMongos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMongoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserMongos
   * const userMongo = await prisma.userMongo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends UserMongoUpdateManyArgs>(
    args: Prisma.SelectSubset<T, UserMongoUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create or update one UserMongo.
   * @param {UserMongoUpsertArgs} args - Arguments to update or create a UserMongo.
   * @example
   * // Update or create a UserMongo
   * const userMongo = await prisma.userMongo.upsert({
   *   create: {
   *     // ... data to create a UserMongo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserMongo we want to update
   *   }
   * })
   */
  upsert<T extends UserMongoUpsertArgs>(
    args: Prisma.SelectSubset<T, UserMongoUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__UserMongoClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserMongoPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more UserMongos that matches the filter.
   * @param {UserMongoFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const userMongo = await prisma.userMongo.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.UserMongoFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>;

  /**
   * Perform aggregation operations on a UserMongo.
   * @param {UserMongoAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const userMongo = await prisma.userMongo.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.UserMongoAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>;

  /**
   * Count the number of UserMongos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMongoCountArgs} args - Arguments to filter UserMongos to count.
   * @example
   * // Count the number of UserMongos
   * const count = await prisma.userMongo.count({
   *   where: {
   *     // ... the filter for the UserMongos we want to count
   *   }
   * })
   **/
  count<T extends UserMongoCountArgs>(
    args?: Prisma.Subset<T, UserMongoCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserMongoCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a UserMongo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMongoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends UserMongoAggregateArgs>(
    args: Prisma.Subset<T, UserMongoAggregateArgs>
  ): Prisma.PrismaPromise<GetUserMongoAggregateType<T>>;

  /**
   * Group by UserMongo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserMongoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends UserMongoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserMongoGroupByArgs['orderBy'] }
      : { orderBy?: UserMongoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, UserMongoGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors ? GetUserMongoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the UserMongo model
   */
  readonly fields: UserMongoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserMongo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserMongoClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the UserMongo model
 */
export interface UserMongoFieldRefs {
  readonly id: Prisma.FieldRef<'UserMongo', 'BigInt'>;
  readonly version: Prisma.FieldRef<'UserMongo', 'BigInt'>;
  readonly username: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly email: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly password: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly enabled: Prisma.FieldRef<'UserMongo', 'Boolean'>;
  readonly accountLocked: Prisma.FieldRef<'UserMongo', 'Boolean'>;
  readonly accountExpired: Prisma.FieldRef<'UserMongo', 'Boolean'>;
  readonly credentialsExpired: Prisma.FieldRef<'UserMongo', 'Boolean'>;
  readonly deleted: Prisma.FieldRef<'UserMongo', 'Boolean'>;
  readonly external: Prisma.FieldRef<'UserMongo', 'Boolean'>;
  readonly role: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly employeeState: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly nextBirthday: Prisma.FieldRef<'UserMongo', 'DateTime'>;
  readonly requireTotp: Prisma.FieldRef<'UserMongo', 'Boolean'>;
  readonly countInvalidLogin: Prisma.FieldRef<'UserMongo', 'Int'>;
  readonly dateLocked: Prisma.FieldRef<'UserMongo', 'DateTime'>;
  readonly lastIP: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly countLogin: Prisma.FieldRef<'UserMongo', 'Int'>;
  readonly lastLogin: Prisma.FieldRef<'UserMongo', 'DateTime'>;
  readonly settings: Prisma.FieldRef<'UserMongo', 'Json'>;
  readonly ip: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly consecutiveFailedLoginAttempts: Prisma.FieldRef<'UserMongo', 'Int'>;
  readonly dateAcceptedLoginNotification: Prisma.FieldRef<'UserMongo', 'DateTime'>;
  readonly resetDate: Prisma.FieldRef<'UserMongo', 'DateTime'>;
  readonly resetIp: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly resetKey: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly dateChanged: Prisma.FieldRef<'UserMongo', 'DateTime'>;
  readonly lastReminder: Prisma.FieldRef<'UserMongo', 'DateTime'>;
  readonly emailVerified: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly dateCreated: Prisma.FieldRef<'UserMongo', 'DateTime'>;
  readonly onBoardingPercentComplete: Prisma.FieldRef<'UserMongo', 'Float'>;
  readonly stepsTotal: Prisma.FieldRef<'UserMongo', 'Int'>;
  readonly stepsCompleted: Prisma.FieldRef<'UserMongo', 'Int'>;
  readonly lang: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly verifikationKey: Prisma.FieldRef<'UserMongo', 'String'>;
  readonly class: Prisma.FieldRef<'UserMongo', 'String'>;
}

// Custom InputTypes
/**
 * UserMongo findUnique
 */
export type UserMongoFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * Filter, which UserMongo to fetch.
   */
  where: Prisma.UserMongoWhereUniqueInput;
};

/**
 * UserMongo findUniqueOrThrow
 */
export type UserMongoFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * Filter, which UserMongo to fetch.
   */
  where: Prisma.UserMongoWhereUniqueInput;
};

/**
 * UserMongo findFirst
 */
export type UserMongoFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * Filter, which UserMongo to fetch.
   */
  where?: Prisma.UserMongoWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserMongos to fetch.
   */
  orderBy?: Prisma.UserMongoOrderByWithRelationInput | Prisma.UserMongoOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UserMongos.
   */
  cursor?: Prisma.UserMongoWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserMongos from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserMongos.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserMongos.
   */
  distinct?: Prisma.UserMongoScalarFieldEnum | Prisma.UserMongoScalarFieldEnum[];
};

/**
 * UserMongo findFirstOrThrow
 */
export type UserMongoFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * Filter, which UserMongo to fetch.
   */
  where?: Prisma.UserMongoWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserMongos to fetch.
   */
  orderBy?: Prisma.UserMongoOrderByWithRelationInput | Prisma.UserMongoOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UserMongos.
   */
  cursor?: Prisma.UserMongoWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserMongos from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserMongos.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserMongos.
   */
  distinct?: Prisma.UserMongoScalarFieldEnum | Prisma.UserMongoScalarFieldEnum[];
};

/**
 * UserMongo findMany
 */
export type UserMongoFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * Filter, which UserMongos to fetch.
   */
  where?: Prisma.UserMongoWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserMongos to fetch.
   */
  orderBy?: Prisma.UserMongoOrderByWithRelationInput | Prisma.UserMongoOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing UserMongos.
   */
  cursor?: Prisma.UserMongoWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserMongos from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserMongos.
   */
  skip?: number;
  distinct?: Prisma.UserMongoScalarFieldEnum | Prisma.UserMongoScalarFieldEnum[];
};

/**
 * UserMongo create
 */
export type UserMongoCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * The data needed to create a UserMongo.
   */
  data: Prisma.XOR<Prisma.UserMongoCreateInput, Prisma.UserMongoUncheckedCreateInput>;
};

/**
 * UserMongo createMany
 */
export type UserMongoCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many UserMongos.
   */
  data: Prisma.UserMongoCreateManyInput | Prisma.UserMongoCreateManyInput[];
};

/**
 * UserMongo update
 */
export type UserMongoUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * The data needed to update a UserMongo.
   */
  data: Prisma.XOR<Prisma.UserMongoUpdateInput, Prisma.UserMongoUncheckedUpdateInput>;
  /**
   * Choose, which UserMongo to update.
   */
  where: Prisma.UserMongoWhereUniqueInput;
};

/**
 * UserMongo updateMany
 */
export type UserMongoUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update UserMongos.
   */
  data: Prisma.XOR<
    Prisma.UserMongoUpdateManyMutationInput,
    Prisma.UserMongoUncheckedUpdateManyInput
  >;
  /**
   * Filter which UserMongos to update
   */
  where?: Prisma.UserMongoWhereInput;
  /**
   * Limit how many UserMongos to update.
   */
  limit?: number;
};

/**
 * UserMongo upsert
 */
export type UserMongoUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * The filter to search for the UserMongo to update in case it exists.
   */
  where: Prisma.UserMongoWhereUniqueInput;
  /**
   * In case the UserMongo found by the `where` argument doesn't exist, create a new UserMongo with this data.
   */
  create: Prisma.XOR<Prisma.UserMongoCreateInput, Prisma.UserMongoUncheckedCreateInput>;
  /**
   * In case the UserMongo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserMongoUpdateInput, Prisma.UserMongoUncheckedUpdateInput>;
};

/**
 * UserMongo delete
 */
export type UserMongoDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
  /**
   * Filter which UserMongo to delete.
   */
  where: Prisma.UserMongoWhereUniqueInput;
};

/**
 * UserMongo deleteMany
 */
export type UserMongoDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UserMongos to delete
   */
  where?: Prisma.UserMongoWhereInput;
  /**
   * Limit how many UserMongos to delete.
   */
  limit?: number;
};

/**
 * UserMongo findRaw
 */
export type UserMongoFindRawArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue;
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue;
};

/**
 * UserMongo aggregateRaw
 */
export type UserMongoAggregateRawArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[];
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue;
};

/**
 * UserMongo without action
 */
export type UserMongoDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserMongo
   */
  select?: Prisma.UserMongoSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserMongo
   */
  omit?: Prisma.UserMongoOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserMongoInclude<ExtArgs> | null;
};
