/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `UserPlanUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model UserPlanUser
 *
 */
export type UserPlanUserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPlanUserPayload>;

export type UserPlanUserNullableCompositeFilter = {
  equals?: Prisma.UserPlanUserObjectEqualityInput | null;
  is?: Prisma.UserPlanUserWhereInput | null;
  isNot?: Prisma.UserPlanUserWhereInput | null;
  isSet?: boolean;
};

export type UserPlanUserOrderByInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  email?: Prisma.SortOrder;
  formalDisplayName?: Prisma.SortOrder;
};

export type UserPlanUserNullableCreateEnvelopeInput = {
  set?: Prisma.UserPlanUserCreateInput | null;
};

export type UserPlanUserNullableUpdateEnvelopeInput = {
  set?: Prisma.UserPlanUserCreateInput | null;
  upsert?: Prisma.UserPlanUserUpsertInput;
  unset?: boolean;
};

export type UserPlanUserWhereInput = {
  AND?: Prisma.UserPlanUserWhereInput | Prisma.UserPlanUserWhereInput[];
  OR?: Prisma.UserPlanUserWhereInput[];
  NOT?: Prisma.UserPlanUserWhereInput | Prisma.UserPlanUserWhereInput[];
  id?: Prisma.BigIntNullableFilter<'UserPlanUser'> | bigint | number | null;
  name?: Prisma.StringNullableFilter<'UserPlanUser'> | string | null;
  email?: Prisma.StringNullableFilter<'UserPlanUser'> | string | null;
  formalDisplayName?: Prisma.StringNullableFilter<'UserPlanUser'> | string | null;
};

export type UserPlanUserUpsertInput = {
  set: Prisma.UserPlanUserCreateInput | null;
  update: Prisma.UserPlanUserUpdateInput;
};

export type UserPlanUserUpdateInput = {
  id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  formalDisplayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type UserPlanUserSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    email?: boolean;
    formalDisplayName?: boolean;
  },
  ExtArgs['result']['userPlanUser']
>;

export type UserPlanUserSelectScalar = {
  id?: boolean;
  name?: boolean;
  email?: boolean;
  formalDisplayName?: boolean;
};

export type UserPlanUserOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'name' | 'email' | 'formalDisplayName',
  ExtArgs['result']['userPlanUser']
>;

export type $UserPlanUserPayload = {
  name: 'UserPlanUser';
  objects: {};
  scalars: {
    id: bigint | null;
    name: string | null;
    email: string | null;
    formalDisplayName: string | null;
  };
  composites: {};
};

export type UserPlanUserGetPayload<S extends boolean | null | undefined | UserPlanUserDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$UserPlanUserPayload, S>;

/**
 * Fields of the UserPlanUser model
 */
export interface UserPlanUserFieldRefs {
  readonly id: Prisma.FieldRef<'UserPlanUser', 'BigInt'>;
  readonly name: Prisma.FieldRef<'UserPlanUser', 'String'>;
  readonly email: Prisma.FieldRef<'UserPlanUser', 'String'>;
  readonly formalDisplayName: Prisma.FieldRef<'UserPlanUser', 'String'>;
}

// Custom InputTypes
/**
 * UserPlanUser without action
 */
export type UserPlanUserDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserPlanUser
   */
  select?: Prisma.UserPlanUserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserPlanUser
   */
  omit?: Prisma.UserPlanUserOmit<ExtArgs> | null;
};
