/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `UserProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model UserProfile
 *
 */
export type UserProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$UserProfilePayload>;

export type UserProfileNullableCompositeFilter = {
  equals?: Prisma.UserProfileObjectEqualityInput | null;
  is?: Prisma.UserProfileWhereInput | null;
  isNot?: Prisma.UserProfileWhereInput | null;
  isSet?: boolean;
};

export type UserProfileOrderByInput = {
  displayName?: Prisma.SortOrder;
};

export type UserProfileNullableCreateEnvelopeInput = {
  set?: Prisma.UserProfileCreateInput | null;
};

export type UserProfileNullableUpdateEnvelopeInput = {
  set?: Prisma.UserProfileCreateInput | null;
  upsert?: Prisma.UserProfileUpsertInput;
  unset?: boolean;
};

export type UserProfileWhereInput = {
  AND?: Prisma.UserProfileWhereInput | Prisma.UserProfileWhereInput[];
  OR?: Prisma.UserProfileWhereInput[];
  NOT?: Prisma.UserProfileWhereInput | Prisma.UserProfileWhereInput[];
  displayName?: Prisma.StringNullableFilter<'UserProfile'> | string | null;
};

export type UserProfileUpsertInput = {
  set: Prisma.UserProfileCreateInput | null;
  update: Prisma.UserProfileUpdateInput;
};

export type UserProfileUpdateInput = {
  displayName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type UserProfileSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    displayName?: boolean;
  },
  ExtArgs['result']['userProfile']
>;

export type UserProfileSelectScalar = {
  displayName?: boolean;
};

export type UserProfileOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<'displayName', ExtArgs['result']['userProfile']>;

export type $UserProfilePayload = {
  name: 'UserProfile';
  objects: {};
  scalars: {
    displayName: string | null;
  };
  composites: {};
};

export type UserProfileGetPayload<S extends boolean | null | undefined | UserProfileDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$UserProfilePayload, S>;

/**
 * Fields of the UserProfile model
 */
export interface UserProfileFieldRefs {
  readonly displayName: Prisma.FieldRef<'UserProfile', 'String'>;
}

// Custom InputTypes
/**
 * UserProfile without action
 */
export type UserProfileDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserProfile
   */
  select?: Prisma.UserProfileSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserProfile
   */
  omit?: Prisma.UserProfileOmit<ExtArgs> | null;
};
