/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `UserAddress` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model UserAddress
 *
 */
export type UserAddressModel = runtime.Types.Result.DefaultSelection<Prisma.$UserAddressPayload>;

export type UserAddressOrderByInput = {
  id?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  address?: Prisma.SortOrder;
  address2?: Prisma.SortOrder;
  zip?: Prisma.SortOrder;
  city?: Prisma.SortOrder;
  state?: Prisma.SortOrder;
  country?: Prisma.SortOrder;
  type?: Prisma.SortOrder;
};

export type UserAddressNullableCompositeFilter = {
  equals?: Prisma.UserAddressObjectEqualityInput | null;
  is?: Prisma.UserAddressWhereInput | null;
  isNot?: Prisma.UserAddressWhereInput | null;
  isSet?: boolean;
};

export type UserAddressWhereInput = {
  AND?: Prisma.UserAddressWhereInput | Prisma.UserAddressWhereInput[];
  OR?: Prisma.UserAddressWhereInput[];
  NOT?: Prisma.UserAddressWhereInput | Prisma.UserAddressWhereInput[];
  id?: Prisma.BigIntNullableFilter<'UserAddress'> | bigint | number | null;
  name?: Prisma.StringNullableFilter<'UserAddress'> | string | null;
  address?: Prisma.StringNullableFilter<'UserAddress'> | string | null;
  address2?: Prisma.StringNullableFilter<'UserAddress'> | string | null;
  zip?: Prisma.StringNullableFilter<'UserAddress'> | string | null;
  city?: Prisma.StringNullableFilter<'UserAddress'> | string | null;
  state?: Prisma.StringNullableFilter<'UserAddress'> | string | null;
  country?: Prisma.StringNullableFilter<'UserAddress'> | string | null;
  type?: Prisma.StringNullableFilter<'UserAddress'> | string | null;
};

export type UserAddressNullableUpdateEnvelopeInput = {
  set?: Prisma.UserAddressCreateInput | null;
  upsert?: Prisma.UserAddressUpsertInput;
  unset?: boolean;
};

export type UserAddressUpsertInput = {
  set: Prisma.UserAddressCreateInput | null;
  update: Prisma.UserAddressUpdateInput;
};

export type UserAddressUpdateInput = {
  id?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  address2?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  zip?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  state?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  country?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type UserAddressSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    name?: boolean;
    address?: boolean;
    address2?: boolean;
    zip?: boolean;
    city?: boolean;
    state?: boolean;
    country?: boolean;
    type?: boolean;
  },
  ExtArgs['result']['userAddress']
>;

export type UserAddressSelectScalar = {
  id?: boolean;
  name?: boolean;
  address?: boolean;
  address2?: boolean;
  zip?: boolean;
  city?: boolean;
  state?: boolean;
  country?: boolean;
  type?: boolean;
};

export type UserAddressOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'name' | 'address' | 'address2' | 'zip' | 'city' | 'state' | 'country' | 'type',
  ExtArgs['result']['userAddress']
>;

export type $UserAddressPayload = {
  name: 'UserAddress';
  objects: {};
  scalars: {
    id: bigint | null;
    name: string | null;
    address: string | null;
    address2: string | null;
    zip: string | null;
    city: string | null;
    state: string | null;
    country: string | null;
    type: string | null;
  };
  composites: {};
};

export type UserAddressGetPayload<S extends boolean | null | undefined | UserAddressDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$UserAddressPayload, S>;

/**
 * Fields of the UserAddress model
 */
export interface UserAddressFieldRefs {
  readonly id: Prisma.FieldRef<'UserAddress', 'BigInt'>;
  readonly name: Prisma.FieldRef<'UserAddress', 'String'>;
  readonly address: Prisma.FieldRef<'UserAddress', 'String'>;
  readonly address2: Prisma.FieldRef<'UserAddress', 'String'>;
  readonly zip: Prisma.FieldRef<'UserAddress', 'String'>;
  readonly city: Prisma.FieldRef<'UserAddress', 'String'>;
  readonly state: Prisma.FieldRef<'UserAddress', 'String'>;
  readonly country: Prisma.FieldRef<'UserAddress', 'String'>;
  readonly type: Prisma.FieldRef<'UserAddress', 'String'>;
}

// Custom InputTypes
/**
 * UserAddress without action
 */
export type UserAddressDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserAddress
   */
  select?: Prisma.UserAddressSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the UserAddress
   */
  omit?: Prisma.UserAddressOmit<ExtArgs> | null;
};
