/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `WatchedCategory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/library';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model WatchedCategory
 *
 */
export type WatchedCategoryModel =
  runtime.Types.Result.DefaultSelection<Prisma.$WatchedCategoryPayload>;

export type WatchedCategoryOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type WatchedCategoryCompositeListFilter = {
  equals?: Prisma.WatchedCategoryObjectEqualityInput[];
  every?: Prisma.WatchedCategoryWhereInput;
  some?: Prisma.WatchedCategoryWhereInput;
  none?: Prisma.WatchedCategoryWhereInput;
  isEmpty?: boolean;
  isSet?: boolean;
};

export type WatchedCategoryWhereInput = {
  AND?: Prisma.WatchedCategoryWhereInput | Prisma.WatchedCategoryWhereInput[];
  OR?: Prisma.WatchedCategoryWhereInput[];
  NOT?: Prisma.WatchedCategoryWhereInput | Prisma.WatchedCategoryWhereInput[];
  categoryId?: Prisma.BigIntNullableFilter<'WatchedCategory'> | bigint | number | null;
  date?: Prisma.DateTimeNullableFilter<'WatchedCategory'> | Date | string | null;
};

export type WatchedCategoryListUpdateEnvelopeInput = {
  set?: Prisma.WatchedCategoryCreateInput | Prisma.WatchedCategoryCreateInput[];
  push?: Prisma.WatchedCategoryCreateInput | Prisma.WatchedCategoryCreateInput[];
  updateMany?: Prisma.WatchedCategoryUpdateManyInput;
  deleteMany?: Prisma.WatchedCategoryDeleteManyInput;
};

export type WatchedCategoryUpdateManyInput = {
  where: Prisma.WatchedCategoryWhereInput;
  data: Prisma.WatchedCategoryUpdateInput;
};

export type WatchedCategoryDeleteManyInput = {
  where: Prisma.WatchedCategoryWhereInput;
};

export type WatchedCategoryUpdateInput = {
  categoryId?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null;
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type WatchedCategorySelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    categoryId?: boolean;
    date?: boolean;
  },
  ExtArgs['result']['watchedCategory']
>;

export type WatchedCategorySelectScalar = {
  categoryId?: boolean;
  date?: boolean;
};

export type WatchedCategoryOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<'categoryId' | 'date', ExtArgs['result']['watchedCategory']>;

export type $WatchedCategoryPayload = {
  name: 'WatchedCategory';
  objects: {};
  scalars: {
    categoryId: bigint | null;
    date: Date | null;
  };
  composites: {};
};

export type WatchedCategoryGetPayload<
  S extends boolean | null | undefined | WatchedCategoryDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$WatchedCategoryPayload, S>;

/**
 * Fields of the WatchedCategory model
 */
export interface WatchedCategoryFieldRefs {
  readonly categoryId: Prisma.FieldRef<'WatchedCategory', 'BigInt'>;
  readonly date: Prisma.FieldRef<'WatchedCategory', 'DateTime'>;
}

// Custom InputTypes
/**
 * WatchedCategory without action
 */
export type WatchedCategoryDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the WatchedCategory
   */
  select?: Prisma.WatchedCategorySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the WatchedCategory
   */
  omit?: Prisma.WatchedCategoryOmit<ExtArgs> | null;
};
