/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/index-browser';

export type * from '../models';
export type * from './prismaNamespace';

export const Decimal = runtime.Decimal;

export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as new (
    secret: never
  ) => typeof runtime.objectEnumValues.instances.DbNull,
  JsonNull: runtime.objectEnumValues.classes.JsonNull as new (
    secret: never
  ) => typeof runtime.objectEnumValues.instances.JsonNull,
  AnyNull: runtime.objectEnumValues.classes.AnyNull as new (
    secret: never
  ) => typeof runtime.objectEnumValues.instances.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull;
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull;
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull;

export const ModelName = {
  ExpertWeek: 'ExpertWeek',
  UserMongo: 'UserMongo',
  Appointment: 'Appointment',
  ShiftPlan: 'ShiftPlan',
  Treatment: 'Treatment',
  Consultation: 'Consultation',
  ConsultationData: 'ConsultationData',
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

/*
 * Enums
 */

export const ExpertWeekScalarFieldEnum = {
  id: 'id',
  version: 'version',
  userId: 'userId',
  type: 'type',
  slotsMo: 'slotsMo',
  slotsTu: 'slotsTu',
  slotsWe: 'slotsWe',
  slotsTh: 'slotsTh',
  slotsFr: 'slotsFr',
  slotsSa: 'slotsSa',
  slotsSu: 'slotsSu',
  dateChanged: 'dateChanged',
  dateCreated: 'dateCreated',
  class: 'class',
} as const;

export type ExpertWeekScalarFieldEnum =
  (typeof ExpertWeekScalarFieldEnum)[keyof typeof ExpertWeekScalarFieldEnum];

export const UserMongoScalarFieldEnum = {
  id: 'id',
  version: 'version',
  username: 'username',
  email: 'email',
  password: 'password',
  enabled: 'enabled',
  accountLocked: 'accountLocked',
  accountExpired: 'accountExpired',
  credentialsExpired: 'credentialsExpired',
  deleted: 'deleted',
  external: 'external',
  role: 'role',
  employeeState: 'employeeState',
  nextBirthday: 'nextBirthday',
  requireTotp: 'requireTotp',
  countInvalidLogin: 'countInvalidLogin',
  dateLocked: 'dateLocked',
  lastIP: 'lastIP',
  countLogin: 'countLogin',
  lastLogin: 'lastLogin',
  settings: 'settings',
  ip: 'ip',
  consecutiveFailedLoginAttempts: 'consecutiveFailedLoginAttempts',
  dateAcceptedLoginNotification: 'dateAcceptedLoginNotification',
  resetDate: 'resetDate',
  resetIp: 'resetIp',
  resetKey: 'resetKey',
  dateChanged: 'dateChanged',
  lastReminder: 'lastReminder',
  emailVerified: 'emailVerified',
  dateCreated: 'dateCreated',
  onBoardingPercentComplete: 'onBoardingPercentComplete',
  stepsTotal: 'stepsTotal',
  stepsCompleted: 'stepsCompleted',
  lang: 'lang',
  verifikationKey: 'verifikationKey',
  class: 'class',
} as const;

export type UserMongoScalarFieldEnum =
  (typeof UserMongoScalarFieldEnum)[keyof typeof UserMongoScalarFieldEnum];

export const AppointmentScalarFieldEnum = {
  id: 'id',
  version: 'version',
  start: 'start',
  until: 'until',
  adjustedStart: 'adjustedStart',
  adjustedUntil: 'adjustedUntil',
  actualStart: 'actualStart',
  actualUntil: 'actualUntil',
  loggedStart: 'loggedStart',
  loggedUntil: 'loggedUntil',
  verifiedStart: 'verifiedStart',
  verifiedUntil: 'verifiedUntil',
  billStart: 'billStart',
  billUntil: 'billUntil',
  dateStarted: 'dateStarted',
  dateDone: 'dateDone',
  dateStorno: 'dateStorno',
  firstContact: 'firstContact',
  dateCreated: 'dateCreated',
  dateChanged: 'dateChanged',
  title: 'title',
  comment: 'comment',
  state: 'state',
  type: 'type',
  billingType: 'billingType',
  paymentType: 'paymentType',
  priceType: 'priceType',
  treatmentId: 'treatmentId',
  minPatients: 'minPatients',
  actualPatients: 'actualPatients',
  billablePatients: 'billablePatients',
  payablePatients: 'payablePatients',
  billableBaseTime: 'billableBaseTime',
  workTimePlanned: 'workTimePlanned',
  workTimeActual: 'workTimeActual',
  workTimeIs: 'workTimeIs',
  requiredStaffCount: 'requiredStaffCount',
  addedStaffCount: 'addedStaffCount',
  backlogCount: 'backlogCount',
  adjustedStaffCount: 'adjustedStaffCount',
  assignedStaffCount: 'assignedStaffCount',
  reservedStaffCount: 'reservedStaffCount',
  missing: 'missing',
  finished: 'finished',
  countFurtherFollowUp: 'countFurtherFollowUp',
  countFurtherIfRequired: 'countFurtherIfRequired',
  countFurtherReferral: 'countFurtherReferral',
  countFurtherReferralOther: 'countFurtherReferralOther',
  period: 'period',
  changedById: 'changedById',
  createdById: 'createdById',
  stornoById: 'stornoById',
  planId: 'planId',
  shiftPlanId: 'shiftPlanId',
  expertOnly: 'expertOnly',
  jobSupport: 'jobSupport',
  treatmentRequireReport: 'treatmentRequireReport',
  assignedDisplayName: 'assignedDisplayName',
  unmatchedShiftCalls: 'unmatchedShiftCalls',
  unmatchedConsultationsCalls: 'unmatchedConsultationsCalls',
  class: 'class',
} as const;

export type AppointmentScalarFieldEnum =
  (typeof AppointmentScalarFieldEnum)[keyof typeof AppointmentScalarFieldEnum];

export const ShiftPlanScalarFieldEnum = {
  id: 'id',
  version: 'version',
  name: 'name',
  day: 'day',
  scheduling: 'scheduling',
  schedulingMulitplier: 'schedulingMulitplier',
  timeStart: 'timeStart',
  timeEnd: 'timeEnd',
  minPatients: 'minPatients',
  count: 'count',
  lastDate: 'lastDate',
  priceType: 'priceType',
  dateChanged: 'dateChanged',
  dateCreated: 'dateCreated',
  comment: 'comment',
  class: 'class',
} as const;

export type ShiftPlanScalarFieldEnum =
  (typeof ShiftPlanScalarFieldEnum)[keyof typeof ShiftPlanScalarFieldEnum];

export const TreatmentScalarFieldEnum = {
  id: 'id',
  version: 'version',
  hour: 'hour',
  day: 'day',
  bookNumber: 'bookNumber',
  jNumber: 'jNumber',
  type: 'type',
  state: 'state',
  dateStorno: 'dateStorno',
  reportingPath: 'reportingPath',
  archived: 'archived',
  dateChanged: 'dateChanged',
  dateCreated: 'dateCreated',
  closed: 'closed',
  countTotal: 'countTotal',
  countFinished: 'countFinished',
  dateInitial: 'dateInitial',
  countPlanned: 'countPlanned',
  comment: 'comment',
  dateAcceptedPTLeitung: 'dateAcceptedPTLeitung',
  dateAcceptedPT: 'dateAcceptedPT',
  dateAcceptedLocation: 'dateAcceptedLocation',
  dateStarted: 'dateStarted',
  dateStart: 'dateStart',
  dateLastAppointment: 'dateLastAppointment',
  reportCountInitial: 'reportCountInitial',
  reportCountRhytm: 'reportCountRhytm',
  minutes: 'minutes',
  class: 'class',
} as const;

export type TreatmentScalarFieldEnum =
  (typeof TreatmentScalarFieldEnum)[keyof typeof TreatmentScalarFieldEnum];

export const ConsultationScalarFieldEnum = {
  id: 'id',
  date: 'date',
  timeStart: 'timeStart',
  timeEnd: 'timeEnd',
  type: 'type',
  state: 'state',
  bookNumber: 'bookNumber',
  period: 'period',
  appointmentType: 'appointmentType',
  paymentType: 'paymentType',
  archived: 'archived',
  location: 'location',
  customer: 'customer',
  doctor: 'doctor',
  job: 'job',
  class: 'class',
} as const;

export type ConsultationScalarFieldEnum =
  (typeof ConsultationScalarFieldEnum)[keyof typeof ConsultationScalarFieldEnum];

export const ConsultationDataScalarFieldEnum = {
  id: 'id',
  version: 'version',
  date: 'date',
  timeStart: 'timeStart',
  timeEnd: 'timeEnd',
  dateSignedOff: 'dateSignedOff',
  archived: 'archived',
  type: 'type',
  state: 'state',
  base: 'base',
  body: 'body',
  warnings: 'warnings',
  onboarding: 'onboarding',
  standard: 'standard',
  signedOffBy: 'signedOffBy',
  appointment: 'appointment',
  location: 'location',
  period: 'period',
  appointmentType: 'appointmentType',
  customer: 'customer',
  job: 'job',
  paymentType: 'paymentType',
  doctor: 'doctor',
  history: 'history',
  document: 'document',
  incarceration: 'incarceration',
  referral: 'referral',
  psych: 'psych',
  treatment: 'treatment',
  noWarnings: 'noWarnings',
  comment: 'comment',
  requireReporting: 'requireReporting',
  bookNumber: 'bookNumber',
  basisWebDataId: 'basisWebDataId',
  class: 'class',
} as const;

export type ConsultationDataScalarFieldEnum =
  (typeof ConsultationDataScalarFieldEnum)[keyof typeof ConsultationDataScalarFieldEnum];

export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive',
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];
